"""vscode launcher

Revision ID: 0367150b9346
Revises: 3f1e5a5c2774
Create Date: 2025-05-27 13:52:40.194957

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0367150b9346"
down_revision: Union[str, None] = "3f1e5a5c2774"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "aspect",
        "embedding_model",
        existing_type=sa.VARCHAR(),
        server_default="default",
        nullable=False,
    )
    op.add_column("documenttopic", sa.Column("distance", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("documenttopic", "distance")
    op.alter_column(
        "aspect",
        "embedding_model",
        existing_type=sa.VARCHAR(),
        nullable=True,
        server_default=None,
    )
    # ### end Alembic commands ###
