"""Add timeline analysis

Revision ID: 233bcdbdc177
Revises: 058eeaf4aa8d
Create Date: 2024-01-29 15:40:47.435077

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "233bcdbdc177"
down_revision: Union[str, None] = "058eeaf4aa8d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "timelineanalysis",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("concepts", sa.String(), server_default="[]", nullable=False),
        sa.Column("settings", sa.String(), server_default="{}", nullable=False),
        sa.Column(
            "created", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column(
            "updated", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["project_id"], ["project.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_timelineanalysis_id"), "timelineanalysis", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_timelineanalysis_name"), "timelineanalysis", ["name"], unique=False
    )
    op.create_index(
        op.f("ix_timelineanalysis_project_id"),
        "timelineanalysis",
        ["project_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_timelineanalysis_user_id"),
        "timelineanalysis",
        ["user_id"],
        unique=False,
    )
    # ### end Alembic commands ###
