"""add timeline analysis type

Revision ID: 313ed5adfe76
Revises: dea7e35f31bd
Create Date: 2025-02-19 13:05:46.325254

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "313ed5adfe76"
down_revision: Union[str, None] = "dea7e35f31bd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "timelineanalysis",
        sa.Column("timeline_analysis_type", sa.String(), nullable=True),
    )
    op.execute(
        "UPDATE timelineanalysis SET timeline_analysis_type = 'document' WHERE timeline_analysis_type IS NULL"
    )
    op.alter_column(
        "timelineanalysis",
        "timeline_analysis_type",
        existing_type=sa.String(),
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("timelineanalysis", "timeline_analysis_type")
    # ### end Alembic commands ###
