"""add topic info interpretation

Revision ID: 3c5ca479f52d
Revises: 313ed5adfe76
Create Date: 2025-03-25 13:33:30.040577

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3c5ca479f52d"
down_revision: Union[str, None] = "313ed5adfe76"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "topicinfo",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("doc_count", sa.Integer(), nullable=True),
        sa.Column("topic_words", sa.String(), server_default="[]", nullable=False),
        sa.Column("topic_documents", sa.String(), server_default="[]", nullable=False),
        sa.Column(
            "created", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["project_id"], ["project.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_topicinfo_created"), "topicinfo", ["created"], unique=False
    )
    op.create_index(
        op.f("ix_topicinfo_doc_count"), "topicinfo", ["doc_count"], unique=False
    )
    op.create_index(op.f("ix_topicinfo_id"), "topicinfo", ["id"], unique=False)
    op.create_index(op.f("ix_topicinfo_name"), "topicinfo", ["name"], unique=False)
    op.create_index(
        op.f("ix_topicinfo_project_id"), "topicinfo", ["project_id"], unique=False
    )
    op.create_table(
        "topicinterpretation",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("prompt_name", sa.String(), nullable=True),
        sa.Column("topic_name", sa.String(), nullable=True),
        sa.Column("reasoning", sa.String(), nullable=True),
        sa.Column(
            "created", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("topic_info_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["topic_info_id"], ["topicinfo.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_topicinterpretation_created"),
        "topicinterpretation",
        ["created"],
        unique=False,
    )
    op.create_index(
        op.f("ix_topicinterpretation_id"), "topicinterpretation", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_topicinterpretation_prompt_name"),
        "topicinterpretation",
        ["prompt_name"],
        unique=False,
    )
    op.create_index(
        op.f("ix_topicinterpretation_reasoning"),
        "topicinterpretation",
        ["reasoning"],
        unique=False,
    )
    op.create_index(
        op.f("ix_topicinterpretation_topic_info_id"),
        "topicinterpretation",
        ["topic_info_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_topicinterpretation_topic_name"),
        "topicinterpretation",
        ["topic_name"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_topicinterpretation_topic_name"), table_name="topicinterpretation"
    )
    op.drop_index(
        op.f("ix_topicinterpretation_topic_info_id"), table_name="topicinterpretation"
    )
    op.drop_index(
        op.f("ix_topicinterpretation_reasoning"), table_name="topicinterpretation"
    )
    op.drop_index(
        op.f("ix_topicinterpretation_prompt_name"), table_name="topicinterpretation"
    )
    op.drop_index(op.f("ix_topicinterpretation_id"), table_name="topicinterpretation")
    op.drop_index(
        op.f("ix_topicinterpretation_created"), table_name="topicinterpretation"
    )
    op.drop_table("topicinterpretation")
    op.drop_index(op.f("ix_topicinfo_project_id"), table_name="topicinfo")
    op.drop_index(op.f("ix_topicinfo_name"), table_name="topicinfo")
    op.drop_index(op.f("ix_topicinfo_id"), table_name="topicinfo")
    op.drop_index(op.f("ix_topicinfo_doc_count"), table_name="topicinfo")
    op.drop_index(op.f("ix_topicinfo_created"), table_name="topicinfo")
    op.drop_table("topicinfo")
    # ### end Alembic commands ###
