"""vscode launcher

Revision ID: 415da3a9c74e
Revises: 42c759c92f5b
Create Date: 2025-05-29 20:26:13.448922

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "415da3a9c74e"
down_revision: Union[str, None] = "42c759c92f5b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "aspect",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("doc_embedding_prompt", sa.Text(), nullable=False),
        sa.Column("doc_modification_prompt", sa.Text(), nullable=True),
        sa.Column("is_hierarchical", sa.Boolean(), nullable=False),
        sa.Column("most_recent_job_id", sa.String(), nullable=True),
        sa.Column(
            "embedding_model", sa.String(), server_default="default", nullable=False
        ),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["project_id"], ["project.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_aspect_id"), "aspect", ["id"], unique=False)
    op.create_index(
        op.f("ix_aspect_project_id"), "aspect", ["project_id"], unique=False
    )
    op.create_table(
        "documentaspect",
        sa.Column("sdoc_id", sa.Integer(), nullable=False),
        sa.Column("aspect_id", sa.Integer(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("embedding_uuid", sa.String(), nullable=True),
        sa.Column("x", sa.Float(), nullable=True),
        sa.Column("y", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(["aspect_id"], ["aspect.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["sdoc_id"], ["sourcedocument.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("sdoc_id", "aspect_id"),
    )
    op.create_index(
        op.f("ix_documentaspect_aspect_id"),
        "documentaspect",
        ["aspect_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_documentaspect_embedding_uuid"),
        "documentaspect",
        ["embedding_uuid"],
        unique=False,
    )
    op.create_index(
        op.f("ix_documentaspect_sdoc_id"), "documentaspect", ["sdoc_id"], unique=False
    )
    op.create_table(
        "topic",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("top_words", sa.ARRAY(sa.String()), nullable=True),
        sa.Column("top_word_scores", sa.ARRAY(sa.Float()), nullable=True),
        sa.Column("level", sa.Integer(), nullable=False),
        sa.Column("color", sa.String(), nullable=False),
        sa.Column("top_docs", sa.ARRAY(sa.Integer()), nullable=True),
        sa.Column("x", sa.Float(), nullable=True),
        sa.Column("y", sa.Float(), nullable=True),
        sa.Column("parent_topic_id", sa.Integer(), nullable=True),
        sa.Column("aspect_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["aspect_id"], ["aspect.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["parent_topic_id"], ["topic.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_topic_aspect_id"), "topic", ["aspect_id"], unique=False)
    op.create_index(op.f("ix_topic_id"), "topic", ["id"], unique=False)
    op.create_index(
        op.f("ix_topic_parent_topic_id"), "topic", ["parent_topic_id"], unique=False
    )
    op.create_table(
        "documenttopic",
        sa.Column("sdoc_id", sa.Integer(), nullable=False),
        sa.Column("topic_id", sa.Integer(), nullable=False),
        sa.Column("distance", sa.Float(), nullable=True),
        sa.Column("is_accepted", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["sdoc_id"], ["sourcedocument.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["topic_id"], ["topic.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("sdoc_id", "topic_id"),
    )
    op.create_index(
        op.f("ix_documenttopic_sdoc_id"), "documenttopic", ["sdoc_id"], unique=False
    )
    op.create_index(
        op.f("ix_documenttopic_topic_id"), "documenttopic", ["topic_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_documenttopic_topic_id"), table_name="documenttopic")
    op.drop_index(op.f("ix_documenttopic_sdoc_id"), table_name="documenttopic")
    op.drop_table("documenttopic")
    op.drop_index(op.f("ix_topic_parent_topic_id"), table_name="topic")
    op.drop_index(op.f("ix_topic_id"), table_name="topic")
    op.drop_index(op.f("ix_topic_aspect_id"), table_name="topic")
    op.drop_table("topic")
    op.drop_index(op.f("ix_documentaspect_sdoc_id"), table_name="documentaspect")
    op.drop_index(op.f("ix_documentaspect_embedding_uuid"), table_name="documentaspect")
    op.drop_index(op.f("ix_documentaspect_aspect_id"), table_name="documentaspect")
    op.drop_table("documentaspect")
    op.drop_index(op.f("ix_aspect_project_id"), table_name="aspect")
    op.drop_index(op.f("ix_aspect_id"), table_name="aspect")
    op.drop_table("aspect")
    # ### end Alembic commands ###
