"""vscode launcher

Revision ID: 416737c34449
Revises: 415da3a9c74e
Create Date: 2025-05-30 08:00:14.048840

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "416737c34449"
down_revision: Union[str, None] = "415da3a9c74e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("topic", "color")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "topic", sa.Column("color", sa.VARCHAR(), autoincrement=False, nullable=False)
    )
    # ### end Alembic commands ###
