"""add project metadata description

Revision ID: 45549c9c4ff2
Revises: 2b91203d1bb6
Create Date: 2024-09-16 08:41:55.296647

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "45549c9c4ff2"
down_revision: Union[str, None] = "2b91203d1bb6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # add new column
    op.add_column(
        "projectmetadata", sa.Column("description", sa.String(), nullable=True)
    )

    # edit all existing rows to have a description
    op.execute(
        """
        UPDATE projectmetadata
        SET description = 'Placeholder description'
        WHERE description IS NULL
        """
    )

    # make the column not nullable
    op.alter_column("projectmetadata", "description", nullable=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("projectmetadata", "description")
    # ### end Alembic commands ###
