"""add topic info

Revision ID: 462d6b81af38
Revises: c970e0892bee
Create Date: 2025-03-03 18:08:58.602798

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "462d6b81af38"
down_revision: Union[str, None] = "c970e0892bee"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
