"""store SDOC content in SQL DB

Revision ID: 4b18cbe91b1e
Revises:
Create Date: 2023-11-03 14:29:34.434063

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "4b18cbe91b1e"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("sourcedocument", sa.Column("name", sa.String(), nullable=True))
    op.add_column("sourcedocument", sa.Column("html", sa.String(), nullable=True))
    op.add_column(
        "sourcedocument",
        sa.Column("token_starts", postgresql.ARRAY(sa.Integer()), nullable=True),
    )
    op.add_column(
        "sourcedocument",
        sa.Column("token_ends", postgresql.ARRAY(sa.Integer()), nullable=True),
    )
    op.add_column(
        "sourcedocument",
        sa.Column("sentence_starts", postgresql.ARRAY(sa.Integer()), nullable=True),
    )
    op.add_column(
        "sourcedocument",
        sa.Column("sentence_ends", postgresql.ARRAY(sa.Integer()), nullable=True),
    )
    op.alter_column(
        "sourcedocument", "content", existing_type=sa.VARCHAR(), nullable=True
    )
    op.create_index(
        op.f("ix_sourcedocument_name"), "sourcedocument", ["name"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_sourcedocument_name"), table_name="sourcedocument")
    op.alter_column(
        "sourcedocument", "content", existing_type=sa.VARCHAR(), nullable=False
    )
    op.drop_column("sourcedocument", "sentence_ends")
    op.drop_column("sourcedocument", "sentence_starts")
    op.drop_column("sourcedocument", "token_ends")
    op.drop_column("sourcedocument", "token_starts")
    op.drop_column("sourcedocument", "html")
    op.drop_column("sourcedocument", "name")
    # ### end Alembic commands ###
