"""Add token time starts and ends to sdoc data
Revision ID: 4eb64db5a67a
Revises: f3108bb5e496
Create Date: 2025-01-09 17:00:29.037251

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4eb64db5a67a"
down_revision: Union[str, None] = "f3108bb5e496"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "sourcedocumentdata",
        sa.Column("token_time_starts", postgresql.ARRAY(sa.Integer()), nullable=True),
    )
    op.add_column(
        "sourcedocumentdata",
        sa.Column("token_time_ends", postgresql.ARRAY(sa.Integer()), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("sourcedocumentdata", "token_time_ends")
    op.drop_column("sourcedocumentdata", "token_time_starts")
    # ### end Alembic commands ###
