"""vscode launcher

Revision ID: 523e193d91a0
Revises: 241cfa625db2
Create Date: 2025-02-19 15:02:00.342999

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "523e193d91a0"
down_revision: Union[str, None] = "241cfa625db2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "documenttagrecommendationjob",
        sa.Column("task_id", sa.Integer(), nullable=False),
        sa.Column("model_name", sa.String(), nullable=True),
        sa.Column(
            "created", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["project_id"], ["project.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("task_id"),
    )
    op.create_index(
        op.f("ix_documenttagrecommendationjob_created"),
        "documenttagrecommendationjob",
        ["created"],
        unique=False,
    )
    op.create_index(
        op.f("ix_documenttagrecommendationjob_model_name"),
        "documenttagrecommendationjob",
        ["model_name"],
        unique=False,
    )
    op.create_index(
        op.f("ix_documenttagrecommendationjob_project_id"),
        "documenttagrecommendationjob",
        ["project_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_documenttagrecommendationjob_task_id"),
        "documenttagrecommendationjob",
        ["task_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_documenttagrecommendationjob_user_id"),
        "documenttagrecommendationjob",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "documenttagrecommendationlink",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("recommendation_task_id", sa.Integer(), nullable=False),
        sa.Column("source_document_id", sa.Integer(), nullable=False),
        sa.Column("predicted_tag_id", sa.Integer(), nullable=False),
        sa.Column("prediction_score", sa.Float(), nullable=True),
        sa.Column("is_accepted", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(
            ["predicted_tag_id"], ["documenttag.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["recommendation_task_id"],
            ["documenttagrecommendationjob.task_id"],
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["source_document_id"], ["sourcedocument.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_documenttagrecommendationlink_id"),
        "documenttagrecommendationlink",
        ["id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_documenttagrecommendationlink_is_accepted"),
        "documenttagrecommendationlink",
        ["is_accepted"],
        unique=False,
    )
    op.create_index(
        op.f("ix_documenttagrecommendationlink_prediction_score"),
        "documenttagrecommendationlink",
        ["prediction_score"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_documenttagrecommendationlink_prediction_score"),
        table_name="documenttagrecommendationlink",
    )
    op.drop_index(
        op.f("ix_documenttagrecommendationlink_is_accepted"),
        table_name="documenttagrecommendationlink",
    )
    op.drop_index(
        op.f("ix_documenttagrecommendationlink_id"),
        table_name="documenttagrecommendationlink",
    )
    op.drop_table("documenttagrecommendationlink")
    op.drop_index(
        op.f("ix_documenttagrecommendationjob_user_id"),
        table_name="documenttagrecommendationjob",
    )
    op.drop_index(
        op.f("ix_documenttagrecommendationjob_task_id"),
        table_name="documenttagrecommendationjob",
    )
    op.drop_index(
        op.f("ix_documenttagrecommendationjob_project_id"),
        table_name="documenttagrecommendationjob",
    )
    op.drop_index(
        op.f("ix_documenttagrecommendationjob_model_name"),
        table_name="documenttagrecommendationjob",
    )
    op.drop_index(
        op.f("ix_documenttagrecommendationjob_created"),
        table_name="documenttagrecommendationjob",
    )
    op.drop_table("documenttagrecommendationjob")
    # ### end Alembic commands ###
