"""remove word frequencies from sdocdata

Revision ID: 53ec37ba68dd
Revises: 45549c9c4ff2
Create Date: 2024-09-17 11:13:19.039284

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "53ec37ba68dd"
down_revision: Union[str, None] = "45549c9c4ff2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("sourcedocumentdata", "word_frequencies")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "sourcedocumentdata",
        sa.Column(
            "word_frequencies",
            sa.VARCHAR(),
            server_default=sa.text("'[]'::character varying"),
            autoincrement=False,
            nullable=False,
        ),
    )
    # ### end Alembic commands ###
