"""vscode launcher

Revision ID: 6a181426fd2a
Revises: 462d6b81af38
Create Date: 2025-03-04 12:34:44.618806

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6a181426fd2a"
down_revision: Union[str, None] = "462d6b81af38"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "topicinfo",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("score", sa.Float(), nullable=True),
        sa.Column("topic_words", sa.String(), server_default="[]", nullable=False),
        sa.Column(
            "created", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["project_id"], ["project.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_topicinfo_created"), "topicinfo", ["created"], unique=False
    )
    op.create_index(op.f("ix_topicinfo_id"), "topicinfo", ["id"], unique=False)
    op.create_index(op.f("ix_topicinfo_name"), "topicinfo", ["name"], unique=False)
    op.create_index(
        op.f("ix_topicinfo_project_id"), "topicinfo", ["project_id"], unique=False
    )
    op.create_index(op.f("ix_topicinfo_score"), "topicinfo", ["score"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_topicinfo_score"), table_name="topicinfo")
    op.drop_index(op.f("ix_topicinfo_project_id"), table_name="topicinfo")
    op.drop_index(op.f("ix_topicinfo_name"), table_name="topicinfo")
    op.drop_index(op.f("ix_topicinfo_id"), table_name="topicinfo")
    op.drop_index(op.f("ix_topicinfo_created"), table_name="topicinfo")
    op.drop_table("topicinfo")
    # ### end Alembic commands ###
