"""memo updated and created columns are now non-nullable
Revision ID: 7393d4227260
Revises: b2e6991379f5
Create Date: 2024-10-17 20:14:45.219331

"""

from typing import Sequence, Union

from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "7393d4227260"
down_revision: Union[str, None] = "b2e6991379f5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.alter_column(
        "memo",
        "created",
        existing_type=postgresql.TIMESTAMP(),
        nullable=False,
        existing_server_default="now()",
    )
    op.alter_column(
        "memo",
        "updated",
        existing_type=postgresql.TIMESTAMP(),
        nullable=False,
        existing_server_default="now()",
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "memo",
        "updated",
        existing_type=postgresql.TIMESTAMP(),
        nullable=True,
        existing_server_default="now()",
    )
    op.alter_column(
        "memo",
        "created",
        existing_type=postgresql.TIMESTAMP(),
        nullable=True,
        existing_server_default="now()",
    )
    # ### end Alembic commands ###
