"""vscode launcher

Revision ID: 7c177a2d7177
Revises: c970e0892bee
Create Date: 2025-03-11 13:23:56.447578

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7c177a2d7177"
down_revision: Union[str, None] = "c970e0892bee"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "topicinfo",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("doc_count", sa.Integer(), nullable=True),
        sa.Column("topic_words", sa.String(), server_default="[]", nullable=False),
        sa.Column(
            "created", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["project_id"], ["project.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_topicinfo_created"), "topicinfo", ["created"], unique=False
    )
    op.create_index(
        op.f("ix_topicinfo_doc_count"), "topicinfo", ["doc_count"], unique=False
    )
    op.create_index(op.f("ix_topicinfo_id"), "topicinfo", ["id"], unique=False)
    op.create_index(op.f("ix_topicinfo_name"), "topicinfo", ["name"], unique=False)
    op.create_index(
        op.f("ix_topicinfo_project_id"), "topicinfo", ["project_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_topicinfo_project_id"), table_name="topicinfo")
    op.drop_index(op.f("ix_topicinfo_name"), table_name="topicinfo")
    op.drop_index(op.f("ix_topicinfo_id"), table_name="topicinfo")
    op.drop_index(op.f("ix_topicinfo_doc_count"), table_name="topicinfo")
    op.drop_index(op.f("ix_topicinfo_created"), table_name="topicinfo")
    op.drop_table("topicinfo")
    # ### end Alembic commands ###
