"""add check constraint for objecthandle

Revision ID: 7d873a4d37fe
Revises: 8ba3801ce92a
Create Date: 2024-09-30 14:36:09.677899

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7d873a4d37fe"
down_revision: Union[str, None] = "8ba3801ce92a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_check_constraint(
        constraint_name="CC_object_handle_refers_to_exactly_one_instance",
        table_name="objecthandle",
        condition=sa.text(
            """(
                CASE WHEN user_id IS NULL THEN 0 ELSE 1 END
                + CASE WHEN project_id IS NULL THEN 0 ELSE 1 END
                + CASE WHEN code_id IS NULL THEN 0 ELSE 1 END
                + CASE WHEN memo_id IS NULL THEN 0 ELSE 1 END
                + CASE WHEN source_document_id IS NULL THEN 0 ELSE 1 END
                + CASE WHEN span_annotation_id IS NULL THEN 0 ELSE 1 END
                + CASE WHEN bbox_annotation_id IS NULL THEN 0 ELSE 1 END
                + CASE WHEN span_group_id IS NULL THEN 0 ELSE 1 END
                + CASE WHEN document_tag_id IS NULL THEN 0 ELSE 1 END
                + CASE WHEN action_id IS NULL THEN 0 ELSE 1 END
            ) = 1"""
        ),
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
