"""Remove the user_id column from the code table and add a new column is_system.
Revision ID: 8ba3801ce92a
Revises: 85d69d90d3e4
Create Date: 2024-09-27 09:10:07.491978

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8ba3801ce92a"
down_revision: Union[str, None] = "85d69d90d3e4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # we add the is_system column
    op.add_column("code", sa.Column("is_system", sa.Boolean(), nullable=True))

    # set the is_system column to False for all existing rows
    op.execute("UPDATE code SET is_system = False")

    # set the is_system column to True for all rows where the user_id is 1
    op.execute("UPDATE code SET is_system = True WHERE user_id = 1")

    # make the is_system column not nullable
    op.alter_column("code", "is_system", nullable=False)

    # we change the unique constraint to be only on the project_id and name
    op.drop_constraint(
        "UC_name_unique_per_user_parent_and_project", "code", type_="unique"
    )
    op.create_unique_constraint(
        "UC_name_unique_per_project", "code", ["project_id", "name"]
    )

    # we remove the user_id column
    op.drop_index("ix_code_user_id", table_name="code")
    op.drop_constraint("code_user_id_fkey", "code", type_="foreignkey")
    op.drop_column("code", "user_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "code", sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=True)
    )
    op.create_foreign_key(
        "code_user_id_fkey", "code", "user", ["user_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_constraint("UC_name_unique_per_project", "code", type_="unique")
    op.create_index("ix_code_user_id", "code", ["user_id"], unique=False)
    op.create_unique_constraint(
        "UC_name_unique_per_user_parent_and_project",
        "code",
        ["user_id", "project_id", "name", "parent_id"],
    )
    op.drop_column("code", "is_system")
    # ### end Alembic commands ###
