"""vscode launcher

Revision ID: a7c7a2ce64be
Revises: 416737c34449
Create Date: 2025-05-31 10:28:58.752071

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a7c7a2ce64be"
down_revision: Union[str, None] = "416737c34449"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "topic",
        sa.Column(
            "is_outlier", sa.Boolean(), nullable=False, server_default=sa.text("false")
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("topic", "is_outlier")
    # ### end Alembic commands ###
