"""Folder Management System

Revision ID: b248f2f9a3ed
Revises: 42c759c92f5b
Create Date: 2025-07-19 18:49:37.505003

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b248f2f9a3ed"
down_revision: Union[str, None] = "42c759c92f5b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "folder",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column(
            "folder_type",
            sa.Enum("NORMAL", "SDOC_FOLDER", name="foldertype"),
            nullable=False,
        ),
        sa.Column(
            "created", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("parent_id", sa.Integer(), nullable=True),
        sa.Column("project_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["parent_id"], ["folder.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["project_id"], ["project.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "parent_id", "name", name="UC_unique_folder_name_in_parent"
        ),
    )
    op.create_index(op.f("ix_folder_created"), "folder", ["created"], unique=False)
    op.create_index(
        op.f("ix_folder_folder_type"), "folder", ["folder_type"], unique=False
    )
    op.create_index(op.f("ix_folder_id"), "folder", ["id"], unique=False)
    op.create_index(op.f("ix_folder_name"), "folder", ["name"], unique=False)
    op.create_index(op.f("ix_folder_parent_id"), "folder", ["parent_id"], unique=False)
    op.create_index(
        op.f("ix_folder_project_id"), "folder", ["project_id"], unique=False
    )
    op.add_column(
        "sourcedocument", sa.Column("folder_id", sa.Integer(), nullable=False)
    )
    op.create_index(
        op.f("ix_sourcedocument_folder_id"),
        "sourcedocument",
        ["folder_id"],
        unique=False,
    )
    op.create_foreign_key(
        "fk_sourcedocument_folder_id",
        "sourcedocument",
        "folder",
        ["folder_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "fk_sourcedocument_folder_id", "sourcedocument", type_="foreignkey"
    )
    op.drop_index(op.f("ix_sourcedocument_folder_id"), table_name="sourcedocument")
    op.drop_column("sourcedocument", "folder_id")
    op.drop_index(op.f("ix_folder_project_id"), table_name="folder")
    op.drop_index(op.f("ix_folder_parent_id"), table_name="folder")
    op.drop_index(op.f("ix_folder_name"), table_name="folder")
    op.drop_index(op.f("ix_folder_id"), table_name="folder")
    op.drop_index(op.f("ix_folder_folder_type"), table_name="folder")
    op.drop_index(op.f("ix_folder_created"), table_name="folder")
    op.drop_table("folder")
    # ### end Alembic commands ###
