"""add topic interpretation

Revision ID: bd6b0c7d7a9a
Revises: 01953786e8a3
Create Date: 2025-03-24 12:31:47.455804

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "bd6b0c7d7a9a"
down_revision: Union[str, None] = "01953786e8a3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "topicinterpretation",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("prompt_name", sa.String(), nullable=True),
        sa.Column("topic_name", sa.String(), nullable=True),
        sa.Column("reasoning", sa.String(), nullable=True),
        sa.Column(
            "created", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("topic_info_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["topic_info_id"], ["topicinfo.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_topicinterpretation_created"),
        "topicinterpretation",
        ["created"],
        unique=False,
    )
    op.create_index(
        op.f("ix_topicinterpretation_id"), "topicinterpretation", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_topicinterpretation_prompt_name"),
        "topicinterpretation",
        ["prompt_name"],
        unique=False,
    )
    op.create_index(
        op.f("ix_topicinterpretation_reasoning"),
        "topicinterpretation",
        ["reasoning"],
        unique=False,
    )
    op.create_index(
        op.f("ix_topicinterpretation_topic_info_id"),
        "topicinterpretation",
        ["topic_info_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_topicinterpretation_topic_name"),
        "topicinterpretation",
        ["topic_name"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_topicinterpretation_topic_name"), table_name="topicinterpretation"
    )
    op.drop_index(
        op.f("ix_topicinterpretation_topic_info_id"), table_name="topicinterpretation"
    )
    op.drop_index(
        op.f("ix_topicinterpretation_reasoning"), table_name="topicinterpretation"
    )
    op.drop_index(
        op.f("ix_topicinterpretation_prompt_name"), table_name="topicinterpretation"
    )
    op.drop_index(op.f("ix_topicinterpretation_id"), table_name="topicinterpretation")
    op.drop_index(
        op.f("ix_topicinterpretation_created"), table_name="topicinterpretation"
    )
    op.drop_table("topicinterpretation")
    # ### end Alembic commands ###
