"""vscode launcher

Revision ID: bf5a2c0290a7
Revises: a7c7a2ce64be
Create Date: 2025-05-31 15:36:39.220069

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "bf5a2c0290a7"
down_revision: Union[str, None] = "a7c7a2ce64be"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_documentaspect_embedding_uuid", table_name="documentaspect")
    op.drop_column("documentaspect", "embedding_uuid")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "documentaspect",
        sa.Column("embedding_uuid", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.create_index(
        "ix_documentaspect_embedding_uuid",
        "documentaspect",
        ["embedding_uuid"],
        unique=False,
    )
    # ### end Alembic commands ###
