"""add sdoc job status table and missing codes to existing projects

Revision ID: c970e0892bee
Revises: 241cfa625db2
Create Date: 2025-02-26 15:28:35.202746

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.orm import sessionmaker

from alembic import op
from app.core.data.crud.code import crud_code

# revision identifiers, used by Alembic.
revision: str = "c970e0892bee"
down_revision: Union[str, None] = "241cfa625db2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sourcedocumentjobstatus",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("type", sa.Integer(), nullable=False),
        sa.Column("status", sa.Integer(), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["id"], ["sourcedocument.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id", "type"),
    )
    op.create_index(
        op.f("ix_sourcedocumentjobstatus_id"),
        "sourcedocumentjobstatus",
        ["id"],
        unique=False,
    )
    # ### end Alembic commands ###

    conn = op.get_bind()

    # 1. Read all existing project ids
    projects = conn.execute(sa.text("SELECT id FROM project")).fetchall()

    # 2. Create missing quotation codes for each existing project
    db = sessionmaker(bind=conn)()
    for row in projects:
        crud_code.create_system_codes_for_project(db=db, proj_id=row.id)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_sourcedocumentjobstatus_id"), table_name="sourcedocumentjobstatus"
    )
    op.drop_table("sourcedocumentjobstatus")
    # ### end Alembic commands ###
    # ### end Alembic commands ###
