"""add sdoc job status table

Revision ID: c970e0892bee
Revises: 523e193d91a0
Create Date: 2025-02-26 15:28:35.202746

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c970e0892bee"
down_revision: Union[str, None] = "523e193d91a0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sourcedocumentjobstatus",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("type", sa.Integer(), nullable=False),
        sa.Column("status", sa.Integer(), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["id"], ["sourcedocument.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id", "type"),
    )
    op.create_index(
        op.f("ix_sourcedocumentjobstatus_id"),
        "sourcedocumentjobstatus",
        ["id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_sourcedocumentjobstatus_id"), table_name="sourcedocumentjobstatus"
    )
    op.drop_table("sourcedocumentjobstatus")
    # ### end Alembic commands ###
