"""vscode launcher

Revision ID: d7e768a5b23d
Revises: f3108bb5e496
Create Date: 2025-01-22 08:51:22.353360

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d7e768a5b23d"
down_revision: Union[str, None] = "f3108bb5e496"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "documenttagrecommendation",
        sa.Column("task_id", sa.Integer(), nullable=False),
        sa.Column("model_name", sa.String(), nullable=True),
        sa.Column(
            "created", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["project_id"], ["project.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("task_id"),
    )
    op.create_index(
        op.f("ix_documenttagrecommendation_created"),
        "documenttagrecommendation",
        ["created"],
        unique=False,
    )
    op.create_index(
        op.f("ix_documenttagrecommendation_model_name"),
        "documenttagrecommendation",
        ["model_name"],
        unique=False,
    )
    op.create_index(
        op.f("ix_documenttagrecommendation_project_id"),
        "documenttagrecommendation",
        ["project_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_documenttagrecommendation_task_id"),
        "documenttagrecommendation",
        ["task_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_documenttagrecommendation_user_id"),
        "documenttagrecommendation",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "documenttagrecommendationlink",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("recommendation_task_id", sa.Integer(), nullable=False),
        sa.Column("source_document_id", sa.Integer(), nullable=False),
        sa.Column("predicted_tag_id", sa.Integer(), nullable=False),
        sa.Column("prediction_score", sa.Float(), nullable=True),
        sa.Column("is_accepted", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(
            ["predicted_tag_id"], ["documenttag.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["recommendation_task_id"],
            ["documenttagrecommendation.task_id"],
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["source_document_id"], ["sourcedocument.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_documenttagrecommendationlink_id"),
        "documenttagrecommendationlink",
        ["id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_documenttagrecommendationlink_is_accepted"),
        "documenttagrecommendationlink",
        ["is_accepted"],
        unique=False,
    )
    op.create_index(
        op.f("ix_documenttagrecommendationlink_prediction_score"),
        "documenttagrecommendationlink",
        ["prediction_score"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_documenttagrecommendationlink_prediction_score"),
        table_name="documenttagrecommendationlink",
    )
    op.drop_index(
        op.f("ix_documenttagrecommendationlink_is_accepted"),
        table_name="documenttagrecommendationlink",
    )
    op.drop_index(
        op.f("ix_documenttagrecommendationlink_id"),
        table_name="documenttagrecommendationlink",
    )
    op.drop_table("documenttagrecommendationlink")
    op.drop_index(
        op.f("ix_documenttagrecommendation_user_id"),
        table_name="documenttagrecommendation",
    )
    op.drop_index(
        op.f("ix_documenttagrecommendation_task_id"),
        table_name="documenttagrecommendation",
    )
    op.drop_index(
        op.f("ix_documenttagrecommendation_project_id"),
        table_name="documenttagrecommendation",
    )
    op.drop_index(
        op.f("ix_documenttagrecommendation_model_name"),
        table_name="documenttagrecommendation",
    )
    op.drop_index(
        op.f("ix_documenttagrecommendation_created"),
        table_name="documenttagrecommendation",
    )
    op.drop_table("documenttagrecommendation")
    # ### end Alembic commands ###
