"""add_enabled_column_to_code

Revision ID: dea7e35f31bd
Revises: c970e0892bef
Create Date: 2025-03-06 12:26:04.598391

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "dea7e35f31bd"
down_revision: Union[str, None] = "c970e0892bef"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "code",
        sa.Column("enabled", sa.Boolean(), nullable=False, server_default=str(True)),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("code", "enabled")
    # ### end Alembic commands ###
