"""introduced_cota

Revision ID: e0a8fb361b1e
Revises: ea297732c5f8
Create Date: 2024-01-26 10:50:01.483063

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e0a8fb361b1e"
down_revision: Union[str, None] = "ea297732c5f8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "conceptovertimeanalysis",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("concepts", sa.String(), server_default="[]", nullable=False),
        sa.Column("search_space", sa.String(), server_default="[]", nullable=False),
        sa.Column(
            "timeline_settings", sa.String(), server_default="{}", nullable=False
        ),
        sa.Column(
            "training_settings", sa.String(), server_default="{}", nullable=False
        ),
        sa.Column(
            "created", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column(
            "updated", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["project_id"], ["project.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_conceptovertimeanalysis_id"),
        "conceptovertimeanalysis",
        ["id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_conceptovertimeanalysis_name"),
        "conceptovertimeanalysis",
        ["name"],
        unique=False,
    )
    op.create_index(
        op.f("ix_conceptovertimeanalysis_project_id"),
        "conceptovertimeanalysis",
        ["project_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_conceptovertimeanalysis_user_id"),
        "conceptovertimeanalysis",
        ["user_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_conceptovertimeanalysis_user_id"), table_name="conceptovertimeanalysis"
    )
    op.drop_index(
        op.f("ix_conceptovertimeanalysis_project_id"),
        table_name="conceptovertimeanalysis",
    )
    op.drop_index(
        op.f("ix_conceptovertimeanalysis_name"), table_name="conceptovertimeanalysis"
    )
    op.drop_index(
        op.f("ix_conceptovertimeanalysis_id"), table_name="conceptovertimeanalysis"
    )
    op.drop_table("conceptovertimeanalysis")
    # ### end Alembic commands ###
