"""update cota

Revision ID: e0a8fb361b1e
Revises: 902d2d7fe2e5
Create Date: 2024-01-19 13:44:32.870389

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e0a8fb361b1e"
down_revision: Union[str, None] = "902d2d7fe2e5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "conceptovertimeanalysis",
        sa.Column(
            "timeline_settings", sa.String(), server_default="{}", nullable=False
        ),
    )
    op.add_column(
        "conceptovertimeanalysis",
        sa.Column(
            "training_settings", sa.String(), server_default="{}", nullable=False
        ),
    )
    op.drop_column("conceptovertimeanalysis", "settings")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "conceptovertimeanalysis",
        sa.Column(
            "settings",
            sa.VARCHAR(),
            server_default=sa.text("'{}'::character varying"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column("conceptovertimeanalysis", "training_settings")
    op.drop_column("conceptovertimeanalysis", "timeline_settings")
    # ### end Alembic commands ###
