repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: requirements-txt-fixer
      - id: trailing-whitespace
  # Ruff
  - repo: local
    hooks:
      - id: ruff-lint-backend
        name: "Ruff Lint (backend)"
        entry: bash -c 'source backend/.venv/bin/activate && ruff check --fix --config=backend/pyproject.toml "$@"' --
        language: system
        files: ^backend/.*\.py$
      - id: ruff-format-backend
        name: "Ruff Format (backend)"
        entry: bash -c 'source backend/.venv/bin/activate && ruff format --config=backend/pyproject.toml "$@"' --
        language: system
        files: ^backend/.*\.py$
      - id: ruff-lint-ray
        name: "Ruff Lint (ray)"
        entry: bash -c 'source backend/.venv/bin/activate && ruff check --fix --config=ray/pyproject.toml "$@"' --
        language: system
        files: ^ray/.*\.py$
      - id: ruff-format-ray
        name: "Ruff Format (ray)"
        entry: bash -c 'source backend/.venv/bin/activate && ruff format --config=ray/pyproject.toml "$@"' --
        language: system
        files: ^ray/.*\.py$
  # Pyright
  - repo: local
    hooks:
      - id: pyright-backend
        name: "Pyright (backend)"
        entry: bash -c 'source backend/.venv/bin/activate && pyright --project backend "$@"' --
        language: system
        files: ^backend/.*\.py$
  # ESLint
  - repo: local
    hooks:
      - id: eslint
        name: "ESLint (frontend)"
        entry: bash -c 'cd frontend && npx eslint --max-warnings=0 --no-warn-ignored --config=eslint.config.mjs "${@#frontend/}"' --
        language: system
        files: ^frontend/.*\.[jt]sx?$ # *.js, *.jsx, *.ts and *.tsx
  # Prettier
  - repo: local
    hooks:
      - id: prettier
        name: "Prettier"
        entry: frontend/node_modules/.bin/prettier
        language: system
        files: \.([jt]sx?|json|ya?ml)$ # *.js, *.jsx, *.ts, *.tsx, *.json, *.yml, *.yaml
        args:
          [
            "--write",
            "--ignore-unknown",
            "--config",
            ".prettierrc.yaml",
            "--cache-location",
            "frontend/node_modules/.cache/prettier",
            "--list-different",
          ]
  - repo: https://github.com/scop/pre-commit-shfmt
    rev: v3.13.1-1
    hooks:
      - id: shfmt

exclude: ^tools/
