FROM uhhlt/dwts_backend_deps:debian_dev_latest
MAINTAINER Florian Schneider florian.schneider-1@uni-hamburg.de

COPY . /dwts_code
WORKDIR /dwts_code/src

ENV C_FORCE_ROOT=1

RUN chmod +x "celery_text_worker_entrypoint.sh"

CMD ["/tini", "--", "/dwts_code/src/celery_text_worker_entrypoint.sh"]
