FROM nvidia/cuda:11.7.1-cudnn8-runtime-ubuntu22.04 as dev_build
MAINTAINER Florian Schneider florian.schneider-1@uni-hamburg.de

COPY --from=openjdk:8-jre-slim /usr/local/openjdk-8 /usr/local/openjdk-8

ENV JAVA_HOME /usr/local/openjdk-8

RUN update-alternatives --install /usr/bin/java java /usr/local/openjdk-8/bin/java 1

ARG DWTS_ENV

ENV DWTS_ENV=${DWTS_ENV} \
  # python:
  PYTHONFAULTHANDLER=1 \
  PYTHONUNBUFFERED=1 \
  PYTHONHASHSEED=random \
  PYTHONDONTWRITEBYTECODE=1 \
  # pip:
  PIP_NO_CACHE_DIR=off \
  PIP_DISABLE_PIP_VERSION_CHECK=on \
  PIP_DEFAULT_TIMEOUT=100 \
  # poetry:
  POETRY_VERSION=1.1.11 \
  POETRY_NO_INTERACTION=1 \
  POETRY_VIRTUALENVS_CREATE=false \
  POETRY_CACHE_DIR='/var/cache/pypoetry' \
  PATH="$PATH:/root/.local/bin:/root/.cargo/bin"

# System deps:
RUN apt-get update && apt-get upgrade -y \
      && apt-get install --no-install-recommends -y \
        bash \
        build-essential \
        curl \
        gettext \
        git \
        libpq-dev \
        wget \
        python3 \
        python3-venv \
        python3-pip \
        python3-dev \
        libmagic-dev

# install poetry
RUN curl -sSL 'https://install.python-poetry.org' | python3 - && poetry --version

# Install rust (for transformers and spacy)
RUN curl -sSf 'https://sh.rustup.rs' | bash -s -- -y \
    && echo 'source $HOME/.cargo/env' >> $HOME/.bashrc \
    && rustup --version

WORKDIR /dwts_code

# Copy only requirements, to cache them in docker layer
COPY ./poetry.lock ./pyproject.toml /dwts_code/

RUN python3 -m pip install --upgrade pip setuptools wheel

RUN echo "$DWTS_ENV" && poetry version \
  && poetry install --no-interaction --no-ansi \
  # Upgrading pip, it is insecure, remove after `pip@21.1`
  && poetry run pip install -U pip

# For development, Jupyter remote kernel
# Using inside the container:
# jupyter lab --ip=0.0.0.0 --allow-root --NotebookApp.custom_display_url=http://127.0.0.1:8888
ARG INSTALL_JUPYTER=false
RUN bash -c "if [ $INSTALL_JUPYTER == 'true' ] ; then pip install jupyterlab ; fi"

RUN python3 -m pip install --upgrade --force-reinstall torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cu116
RUN python3 -m pip install faiss-gpu
RUN python3 -m pip install spacy[cuda-autodetect]

# Add Tini
ARG TINI_VERSION=v0.19.0
# for Mac M1: tini-arm64 otherwise just tini
ARG TINI_BINARY=tini
ADD https://github.com/krallin/tini/releases/download/${TINI_VERSION}/${TINI_BINARY} /tini
RUN chmod +x /tini
