name: dwts
channels:
  - conda-forge
  - defaults
dependencies:
  - alembic=1.12.1
  - anyio=3.7.1
  - beautifulsoup4=4.12.2
  - black=23.9.1
  - celery=5.3.4
  - cssselect=1.2.0
  - debugpy=1.8.0
  - elasticsearch=7.17 #8.11
  - email_validator=2.1
  - fastapi-mail=1.4.1
  - fastapi=0.104.1
  - ffmpeg-python=0.2.0
  - frozendict=2.3.8
  - ftfy=6.1.3
  - httpx=0.25.1
  - isort=5.12.0
  - langdetect=1.0.9
  - loguru=0.7.2
  - matplotlib=3.8.2
  - multiprocess=0.70.15
  - omegaconf=2.3.0
  - pandas=2.1.3
  - passlib=1.7.4
  - pillow=10.1.0
  - pip=23.3.1
  - pre-commit=3.5.0
  - psycopg2-binary=2.9
  - pydantic=2.4.2
  - pytest=7.4.3
  - python-jose=3.3
  - python-magic=0.4.27
  - python-multipart=0.0.6
  - python=3.12.0
  - readability-lxml=0.8.1
  - redis-py=5.0.1
  - rope=1.9.0
  - sqlalchemy-utils=0.41.1
  - sqlalchemy=2.0.23
  - srsly=2.4.8
  - tika=1.24
  - tqdm=4.66.1
  - twisted=23.10.0
  - uvicorn=0.24.0
  - pip:
      - -r requirements.txt
