name: dwts
channels:
  - defaults
  - huggingface
  - pytorch
  - fastai
  - conda-forge
dependencies:
  - python=3.10
  - pytorch::pytorch=1.12
  - conda-forge::cudatoolkit=11.6
  - sentence-transformers=2.2
  - huggingface::transformers=4.21
  - pydantic=1.8
  - spacy=3.4
  - cupy=11.2 
  - fastapi=0.85
  - sqlalchemy=1.4
  - psycopg2-binary=2.9
  - redis-py=4.3
  - celery=5.2
  - loguru=0.6
  - omegaconf=2.2
  - uvicorn=0.19
  - langdetect=1.0
  - passlib=1.7
  - pillow=9.2.0
  - elasticsearch=7.17
  - python-magic=0.4
  - tika=1.24
  - python-jose=3.3
  - frozendict=2.3
  - email_validator=1.3
  - sqlalchemy-utils=0.38
  - timm=0.6
  - python-multipart=0.0.5
  - spacy-transformers=1.1
  - ftfy=6.1
  - beautifulsoup4=4.11.1
  - pip:
    - faiss-gpu==1.7.2