name: dwts
channels:
  - conda-forge
  - defaults
  - pytorch
  - fastai
dependencies:
  - python=3.10
  - conda-forge::pip=23.2.1
  - pytorch::pytorch=1.12
  - conda-forge::cudatoolkit=11.6
  - conda-forge::transformers=4.30.2
  - conda-forge::sentence-transformers=2.2.2
  - conda-forge::cupy=12.1.0
  - conda-forge::spacy=3.6.1
  - conda-forge::spacy-transformers=1.2.5
  - pydantic=1.8
  - fastapi=0.85
  - sqlalchemy=1.4
  - psycopg2-binary=2.9
  - redis-py=4.3
  - celery=5.2
  - loguru=0.6
  - omegaconf=2.2
  - uvicorn=0.19
  - langdetect=1.0
  - passlib=1.7
  - pillow=9.2.0
  - elasticsearch=7.17
  - python-magic=0.4
  - tika=1.24
  - python-jose=3.3
  - frozendict=2.3
  - email_validator=1.3
  - sqlalchemy-utils=0.38
  - timm=0.6
  - python-multipart=0.0.5
  - ftfy=6.1
  - beautifulsoup4=4.11.1
  - pytest=7.2.0
  - ffmpeg-python=0.2.0
  - conda-forge::pandas=1.5.3
  - conda-forge::readability-lxml=0.8.1
  - conda-forge::matplotlib=3.7.1
  - git=2.34.1
  - pip:
      - -r requirements.txt
