name: dwts
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - alembic=1.12.1
  - anyio=3.7.1
  - beautifulsoup4=4.11.1
  - black=23.9.1
  - celery=5.2
  - cssselect=1.2.0
  - debugpy=1.8.0
  - elasticsearch=7.17
  - email_validator=2.1
  - fastapi-mail=1.4.1
  - fastapi=0.108.0
  - ffmpeg-python=0.2.0
  - frozendict=2.3
  - ftfy=6.1
  - httpx=0.23.0
  - isort=5.12.0
  - langdetect=1.0
  - loguru=0.6
  - matplotlib=3.7.1
  - multiprocess=0.70.15
  - networkx=3.2.1
  - omegaconf=2.3.0
  - pandas=1.5.3
  - passlib=1.7
  - pillow=9.2.0
  - pip=23.3.2
  - pre-commit=3.3.3
  - psycopg2-binary=2.9
  - pydantic=2.5.3
  - pytest=7.4.3
  - python-jose=3.3
  - python-magic=0.4
  - python-multipart=0.0.5
  - python=3.11
  - pytorch
  - pytorch-cuda=11.8
  - readability-lxml=0.8.1
  - redis-py=4.3
  - rope=1.9.0
  - scikit-learn=1.3.2
  - sqlalchemy-utils=0.41.1
  - sqlalchemy=2.0.25
  - srsly=2.4.8
  - tqdm=4.66.1
  - twisted=22.10.0
  - umap-learn=0.5.5
  - uvicorn=0.23.2
  - conda-forge::transformers>=4.3
  - conda-forge::sentence-transformers>=2.2.2
  - setfit=1.0.3
  - pip:
      - -r requirements.txt
