version: "3.7"

services:
  postgres:
    image: "postgres:latest"
    environment:
      - POSTGRES_USER=dwtsuser
      - POSTGRES_PASSWORD=dwts123
    ports:
      - "5432:5432"
    volumes:
      - "postgres_data:/var/lib/postgresql/data"

  rabbitmq:
    image: "rabbitmq:management"
    environment:
      - RABBITMQ_DEFAULT_USER=dwtsuser
      - RABBITMQ_DEFAULT_PASS=dwts123
    ports:
      - "4369:4369"
      - "5672:5672"
      - "25672:25672"
      - "15672:15672"
    volumes:
      - "rabbitmq_data:/var/lib/rabbitmq/data"

  redis:
    image: "redis:latest"
    environment:
      - REDIS_PASSWORD=dwts123
    ports:
      - "6379:6379"
    volumes:
      - "redis_data:/var/lib/redis/data"
    command: redis-server --requirepass dwts123

  celery-flower:
    image: gregsi/latest-celery-flower-docker:latest
    environment:
      - AMQP_USERNAME=dwtsuser
      - AMQP_PASSWORD=dwts123
      - AMQP_ADMIN_USERNAME=dwtsuser
      - AMQP_ADMIN_PASSWORD=dwts123
      - AMQP_HOST=rabbitmq
      - AMQP_PORT=5672
      - AMQP_ADMIN_HOST=rabbitmq
      - AMQP_ADMIN_PORT=15672
      - FLOWER_BASIC_AUTH=user:test
    ports:
      - "5555:5555"
    depends_on:
      - rabbitmq
      - redis

volumes:
  rabbitmq_data:
    driver: local
  redis_data:
    driver: local
  postgres_data:
    driver: local