"""delete version table

Revision ID: 00e56404d2b2
Revises: 7d873a4d37fe
Create Date: 2024-10-02 09:46:29.039660

"""

from typing import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "00e56404d2b2"
down_revision: str | None = "7d873a4d37fe"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("version")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "version",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("version", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("id", name="version_pkey"),
    )
    # ### end Alembic commands ###
