"""vscode launcher

Revision ID: 01f3fdf5c875
Revises: 1b21abe44adb
Create Date: 2025-08-14 09:38:50.596537

"""

from typing import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "01f3fdf5c875"
down_revision: str | None = "1b21abe44adb"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "sourcedocument",
        sa.Column("extract_archive", sa.Integer(), server_default="0", nullable=False),
    )
    op.add_column(
        "sourcedocument",
        sa.Column("pdf_checking", sa.Integer(), server_default="0", nullable=False),
    )
    op.add_column(
        "sourcedocument",
        sa.Column("sdoc_init", sa.Integer(), server_default="0", nullable=False),
    )
    op.add_column(
        "sourcedocument",
        sa.Column("extract_html", sa.Integer(), server_default="0", nullable=False),
    )
    op.add_column(
        "sourcedocument",
        sa.Column("text_extraction", sa.Integer(), server_default="0", nullable=False),
    )
    op.add_column(
        "sourcedocument",
        sa.Column(
            "text_language_detection", sa.Integer(), server_default="0", nullable=False
        ),
    )
    op.add_column(
        "sourcedocument",
        sa.Column("text_spacy", sa.Integer(), server_default="0", nullable=False),
    )
    op.add_column(
        "sourcedocument",
        sa.Column("text_es_index", sa.Integer(), server_default="0", nullable=False),
    )
    op.add_column(
        "sourcedocument",
        sa.Column(
            "text_sentence_embedding", sa.Integer(), server_default="0", nullable=False
        ),
    )
    op.add_column(
        "sourcedocument",
        sa.Column(
            "text_html_mapping", sa.Integer(), server_default="0", nullable=False
        ),
    )
    op.add_column(
        "sourcedocument",
        sa.Column("image_caption", sa.Integer(), server_default="0", nullable=False),
    )
    op.add_column(
        "sourcedocument",
        sa.Column("image_embedding", sa.Integer(), server_default="0", nullable=False),
    )
    op.add_column(
        "sourcedocument",
        sa.Column(
            "image_metadata_extraction",
            sa.Integer(),
            server_default="0",
            nullable=False,
        ),
    )
    op.add_column(
        "sourcedocument",
        sa.Column("image_thumbnail", sa.Integer(), server_default="0", nullable=False),
    )
    op.add_column(
        "sourcedocument",
        sa.Column(
            "image_object_detection", sa.Integer(), server_default="0", nullable=False
        ),
    )
    op.add_column(
        "sourcedocument",
        sa.Column("audio_metadata", sa.Integer(), server_default="0", nullable=False),
    )
    op.add_column(
        "sourcedocument",
        sa.Column("audio_thumbnail", sa.Integer(), server_default="0", nullable=False),
    )
    op.add_column(
        "sourcedocument",
        sa.Column(
            "audio_transcription", sa.Integer(), server_default="0", nullable=False
        ),
    )
    op.add_column(
        "sourcedocument",
        sa.Column("video_metadata", sa.Integer(), server_default="0", nullable=False),
    )
    op.add_column(
        "sourcedocument",
        sa.Column("video_thumbnail", sa.Integer(), server_default="0", nullable=False),
    )
    op.add_column(
        "sourcedocument",
        sa.Column(
            "video_audio_extraction", sa.Integer(), server_default="0", nullable=False
        ),
    )
    op.add_column(
        "sourcedocument",
        sa.Column(
            "processed_jobs",
            sa.Integer(),
            sa.Computed(
                "sdoc_init + extract_html + text_extraction + text_language_detection + text_spacy + text_es_index + text_sentence_embedding + text_html_mapping + image_caption + image_embedding + image_metadata_extraction + image_thumbnail + image_object_detection + audio_metadata + audio_thumbnail + audio_transcription + video_metadata + video_thumbnail + video_audio_extraction",
                persisted=True,
            ),
            nullable=False,
        ),
    )
    op.drop_index("ix_sourcedocument_status", table_name="sourcedocument")
    op.create_index(
        op.f("ix_sourcedocument_processed_jobs"),
        "sourcedocument",
        ["processed_jobs"],
        unique=False,
    )
    op.drop_column("sourcedocument", "status")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "sourcedocument",
        sa.Column("status", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.drop_index(op.f("ix_sourcedocument_processed_jobs"), table_name="sourcedocument")
    op.create_index(
        "ix_sourcedocument_status", "sourcedocument", ["status"], unique=False
    )
    op.drop_column("sourcedocument", "processed_jobs")
    op.drop_column("sourcedocument", "video_audio_extraction")
    op.drop_column("sourcedocument", "video_thumbnail")
    op.drop_column("sourcedocument", "video_metadata")
    op.drop_column("sourcedocument", "audio_transcription")
    op.drop_column("sourcedocument", "audio_thumbnail")
    op.drop_column("sourcedocument", "audio_metadata")
    op.drop_column("sourcedocument", "image_object_detection")
    op.drop_column("sourcedocument", "image_thumbnail")
    op.drop_column("sourcedocument", "image_metadata_extraction")
    op.drop_column("sourcedocument", "image_embedding")
    op.drop_column("sourcedocument", "image_caption")
    op.drop_column("sourcedocument", "text_html_mapping")
    op.drop_column("sourcedocument", "text_sentence_embedding")
    op.drop_column("sourcedocument", "text_es_index")
    op.drop_column("sourcedocument", "text_spacy")
    op.drop_column("sourcedocument", "text_language_detection")
    op.drop_column("sourcedocument", "text_extraction")
    op.drop_column("sourcedocument", "extract_html")
    op.drop_column("sourcedocument", "sdoc_init")
    op.drop_column("sourcedocument", "pdf_checking")
    op.drop_column("sourcedocument", "extract_archive")
    # ### end Alembic commands ###
