"""add history table

Revision ID: 02320d77b8dd
Revises: 7e88b47a2f6c
Create Date: 2025-12-11 15:04:12.210086

"""

from typing import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "02320d77b8dd"
down_revision: str | None = "7e88b47a2f6c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "perspectivehistory",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("history_number", sa.Integer(), nullable=False),
        sa.Column("is_undone", sa.Boolean(), nullable=False),
        sa.Column("undo_data", sa.JSON(), nullable=False),
        sa.Column("redo_data", sa.JSON(), nullable=False),
        sa.Column("aspect_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["aspect_id"],
            ["aspect.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("perspectivehistory")
    # ### end Alembic commands ###
