"""add classifier tables

Revision ID: 07c06f167688
Revises: b1b3562f9a29
Create Date: 2025-09-03 08:30:02.451890

"""

from typing import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "07c06f167688"
down_revision: str | None = "b1b3562f9a29"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "classifier",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("base_model", sa.String(), nullable=False),
        sa.Column("type", sa.String(), nullable=False),
        sa.Column("path", sa.String(), nullable=False),
        sa.Column("labelid2classid", sa.JSON(), nullable=False),
        sa.Column("train_params", sa.JSON(), nullable=False),
        sa.Column("train_loss", sa.JSON(), nullable=False),
        sa.Column("train_data_stats", sa.JSON(), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["project_id"], ["project.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("project_id", "name", name="UC_unique_name_in_project"),
    )
    op.create_index(
        op.f("ix_classifier_base_model"), "classifier", ["base_model"], unique=False
    )
    op.create_index(
        op.f("ix_classifier_created"), "classifier", ["created"], unique=False
    )
    op.create_index(op.f("ix_classifier_id"), "classifier", ["id"], unique=False)
    op.create_index(op.f("ix_classifier_name"), "classifier", ["name"], unique=False)
    op.create_index(
        op.f("ix_classifier_project_id"), "classifier", ["project_id"], unique=False
    )
    op.create_index(op.f("ix_classifier_type"), "classifier", ["type"], unique=False)
    op.create_table(
        "classifiercodelinktable",
        sa.Column("classifier_id", sa.Integer(), nullable=False),
        sa.Column("code_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["classifier_id"], ["classifier.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["code_id"],
            ["code.id"],
        ),
        sa.PrimaryKeyConstraint("classifier_id", "code_id"),
    )
    op.create_table(
        "classifierevaluation",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("f1", sa.Float(), nullable=False),
        sa.Column("precision", sa.Float(), nullable=False),
        sa.Column("recall", sa.Float(), nullable=False),
        sa.Column("accuracy", sa.Float(), nullable=False),
        sa.Column("eval_data_stats", sa.JSON(), nullable=False),
        sa.Column("classifier_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["classifier_id"], ["classifier.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_classifierevaluation_classifier_id"),
        "classifierevaluation",
        ["classifier_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_classifierevaluation_created"),
        "classifierevaluation",
        ["created"],
        unique=False,
    )
    op.create_index(
        op.f("ix_classifierevaluation_id"), "classifierevaluation", ["id"], unique=False
    )
    op.create_table(
        "classifiertaglinktable",
        sa.Column("classifier_id", sa.Integer(), nullable=False),
        sa.Column("tag_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["classifier_id"], ["classifier.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["tag_id"],
            ["tag.id"],
        ),
        sa.PrimaryKeyConstraint("classifier_id", "tag_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("classifiertaglinktable")
    op.drop_index(op.f("ix_classifierevaluation_id"), table_name="classifierevaluation")
    op.drop_index(
        op.f("ix_classifierevaluation_created"), table_name="classifierevaluation"
    )
    op.drop_index(
        op.f("ix_classifierevaluation_classifier_id"), table_name="classifierevaluation"
    )
    op.drop_table("classifierevaluation")
    op.drop_table("classifiercodelinktable")
    op.drop_index(op.f("ix_classifier_type"), table_name="classifier")
    op.drop_index(op.f("ix_classifier_project_id"), table_name="classifier")
    op.drop_index(op.f("ix_classifier_name"), table_name="classifier")
    op.drop_index(op.f("ix_classifier_id"), table_name="classifier")
    op.drop_index(op.f("ix_classifier_created"), table_name="classifier")
    op.drop_index(op.f("ix_classifier_base_model"), table_name="classifier")
    op.drop_table("classifier")
    # ### end Alembic commands ###
