"""remove users from analyses

Revision ID: 15b53f767991
Revises: cd64a8c51a1a
Create Date: 2025-07-25 12:26:49.763795

"""

from typing import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "15b53f767991"
down_revision: str | None = "cd64a8c51a1a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_conceptovertimeanalysis_user_id", table_name="conceptovertimeanalysis"
    )
    op.drop_constraint(
        "conceptovertimeanalysis_user_id_fkey",
        "conceptovertimeanalysis",
        type_="foreignkey",
    )
    op.drop_column("conceptovertimeanalysis", "user_id")
    op.drop_index("ix_timelineanalysis_user_id", table_name="timelineanalysis")
    op.drop_constraint(
        "timelineanalysis_user_id_fkey", "timelineanalysis", type_="foreignkey"
    )
    op.drop_column("timelineanalysis", "user_id")
    op.drop_index("ix_whiteboard_user_id", table_name="whiteboard")
    op.drop_constraint("whiteboard_user_id_fkey", "whiteboard", type_="foreignkey")
    op.drop_column("whiteboard", "user_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "whiteboard",
        sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.create_foreign_key(
        "whiteboard_user_id_fkey",
        "whiteboard",
        "user",
        ["user_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_index("ix_whiteboard_user_id", "whiteboard", ["user_id"], unique=False)
    op.add_column(
        "timelineanalysis",
        sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.create_foreign_key(
        "timelineanalysis_user_id_fkey",
        "timelineanalysis",
        "user",
        ["user_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_index(
        "ix_timelineanalysis_user_id", "timelineanalysis", ["user_id"], unique=False
    )
    op.add_column(
        "conceptovertimeanalysis",
        sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.create_foreign_key(
        "conceptovertimeanalysis_user_id_fkey",
        "conceptovertimeanalysis",
        "user",
        ["user_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_index(
        "ix_conceptovertimeanalysis_user_id",
        "conceptovertimeanalysis",
        ["user_id"],
        unique=False,
    )
    # ### end Alembic commands ###
