"""code changelog

Revision ID: 18e1fd5996f5
Revises: a7d974acc6f2
Create Date: 2026-07-24 10:23:08.946379

"""

from typing import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "18e1fd5996f5"
down_revision: str | None = "a7d974acc6f2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("code", sa.Column("change_set_id", sa.Uuid(), nullable=True))
    op.add_column("code", sa.Column("change_kind", sa.String(), nullable=True))
    op.add_column("code", sa.Column("previous_code_id", sa.Integer(), nullable=True))
    op.add_column("code", sa.Column("merged_from_code_id", sa.Integer(), nullable=True))

    # Historical snapshots predate explicit operation grouping and predecessor
    # links. Give each one a stable, unique change set and reconstruct the previous
    # snapshot within its Main/branch scope. The first branch snapshot falls back to
    # its recorded Main merge base. Historical merges cannot be identified safely,
    # so they remain ordinary updates with no merged_from_code_id.
    op.execute(
        sa.text(
            """
            WITH ordered_snapshots AS (
                SELECT
                    id,
                    LAG(id) OVER (
                        PARTITION BY project_id, concept_id, branch_id
                        ORDER BY created NULLS FIRST, id
                    ) AS previous_scope_code_id
                FROM code
            )
            UPDATE code AS target
            SET
                change_set_id = CAST(
                    MD5('code-change-set:' || CAST(target.id AS text)) AS uuid
                ),
                previous_code_id = COALESCE(
                    ordered_snapshots.previous_scope_code_id,
                    target.base_main_code_id
                ),
                change_kind = CASE
                    WHEN target.is_deleted THEN 'delete'
                    WHEN COALESCE(
                        ordered_snapshots.previous_scope_code_id,
                        target.base_main_code_id
                    ) IS NULL THEN 'create'
                    ELSE 'update'
                END
            FROM ordered_snapshots
            WHERE target.id = ordered_snapshots.id
            """
        )
    )
    op.alter_column("code", "change_set_id", nullable=False)
    op.alter_column("code", "change_kind", nullable=False)
    op.create_index(op.f("ix_code_change_kind"), "code", ["change_kind"], unique=False)
    op.create_index(
        op.f("ix_code_change_set_id"), "code", ["change_set_id"], unique=False
    )
    op.create_index(
        op.f("ix_code_merged_from_code_id"),
        "code",
        ["merged_from_code_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_code_previous_code_id"), "code", ["previous_code_id"], unique=False
    )
    op.create_foreign_key(
        "FK_code_previous_code_id_code_id",
        "code",
        "code",
        ["previous_code_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        "FK_code_merged_from_code_id_code_id",
        "code",
        "code",
        ["merged_from_code_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "FK_code_merged_from_code_id_code_id", "code", type_="foreignkey"
    )
    op.drop_constraint("FK_code_previous_code_id_code_id", "code", type_="foreignkey")
    op.drop_index(op.f("ix_code_previous_code_id"), table_name="code")
    op.drop_index(op.f("ix_code_merged_from_code_id"), table_name="code")
    op.drop_index(op.f("ix_code_change_set_id"), table_name="code")
    op.drop_index(op.f("ix_code_change_kind"), table_name="code")
    op.drop_column("code", "merged_from_code_id")
    op.drop_column("code", "previous_code_id")
    op.drop_column("code", "change_kind")
    op.drop_column("code", "change_set_id")
    # ### end Alembic commands ###
