"""add last_refinement_job_id to cota

Revision ID: 1b21abe44adb
Revises: 6f484bc7d629
Create Date: 2025-08-05 15:14:25.001940

"""

from typing import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1b21abe44adb"
down_revision: str | None = "6f484bc7d629"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "conceptovertimeanalysis",
        sa.Column("last_refinement_job_id", sa.String(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("conceptovertimeanalysis", "last_refinement_job_id")
    # ### end Alembic commands ###
