"""remove analysistable

Revision ID: 241cfa625db2
Revises: 970c55224a39
Create Date: 2025-02-11 10:16:29.438178

"""

from typing import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "241cfa625db2"
down_revision: str | None = "970c55224a39"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_analysistable_created", table_name="analysistable")
    op.drop_index("ix_analysistable_id", table_name="analysistable")
    op.drop_index("ix_analysistable_project_id", table_name="analysistable")
    op.drop_index("ix_analysistable_user_id", table_name="analysistable")
    op.drop_table("analysistable")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "analysistable",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "created",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("title", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("content", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("table_type", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("project_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["project.id"],
            name="analysistable_project_id_fkey",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
            name="analysistable_user_id_fkey",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name="analysistable_pkey"),
    )
    op.create_index(
        "ix_analysistable_user_id", "analysistable", ["user_id"], unique=False
    )
    op.create_index(
        "ix_analysistable_project_id", "analysistable", ["project_id"], unique=False
    )
    op.create_index("ix_analysistable_id", "analysistable", ["id"], unique=False)
    op.create_index(
        "ix_analysistable_created", "analysistable", ["created"], unique=False
    )
    # ### end Alembic commands ###
