"""code versioning system

Revision ID: 28ac2cff18f1
Revises: 16b735a5f8f5
Create Date: 2026-07-23 10:15:51.258713

"""

from typing import Sequence
from uuid import uuid4

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "28ac2cff18f1"
down_revision: str | None = "16b735a5f8f5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "codebranch",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("is_archived", sa.Boolean(), nullable=False),
        sa.Column(
            "created", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("created_by_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["user.id"],
            name="FK_codebranch_created_by_id_user_id",
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["project.id"],
            name="FK_codebranch_project_id_project_id",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "UC_active_code_branch_name_per_project",
        "codebranch",
        ["project_id", "name"],
        unique=True,
        postgresql_where=sa.text("NOT is_archived"),
    )
    op.create_index(
        op.f("ix_codebranch_created"), "codebranch", ["created"], unique=False
    )
    op.create_index(
        op.f("ix_codebranch_created_by_id"),
        "codebranch",
        ["created_by_id"],
        unique=False,
    )
    op.create_index(op.f("ix_codebranch_id"), "codebranch", ["id"], unique=False)
    op.create_index(
        op.f("ix_codebranch_is_archived"), "codebranch", ["is_archived"], unique=False
    )
    op.create_index(op.f("ix_codebranch_name"), "codebranch", ["name"], unique=False)
    op.create_index(
        op.f("ix_codebranch_project_id"), "codebranch", ["project_id"], unique=False
    )
    op.add_column(
        "bboxannotation",
        sa.Column(
            "needs_review", sa.Boolean(), server_default=sa.false(), nullable=False
        ),
    )
    op.create_index(
        op.f("ix_bboxannotation_needs_review"),
        "bboxannotation",
        ["needs_review"],
        unique=False,
    )
    # New identity columns must be nullable/defaulted until existing rows have
    # been backfilled. Each pre-versioning row represents one Main concept.
    op.add_column("code", sa.Column("concept_id", sa.Uuid(), nullable=True))
    op.add_column(
        "code",
        sa.Column("is_active", sa.Boolean(), server_default=sa.true(), nullable=False),
    )
    op.add_column(
        "code",
        sa.Column(
            "is_deleted", sa.Boolean(), server_default=sa.false(), nullable=False
        ),
    )
    op.add_column("code", sa.Column("author_id", sa.Integer(), nullable=True))
    op.add_column("code", sa.Column("commit_message", sa.String(), nullable=True))
    op.add_column("code", sa.Column("branch_id", sa.Integer(), nullable=True))
    op.add_column("code", sa.Column("base_main_code_id", sa.Integer(), nullable=True))
    op.add_column("code", sa.Column("parent_concept_id", sa.Uuid(), nullable=True))

    connection = op.get_bind()
    code_table = sa.table(
        "code",
        sa.column("id", sa.Integer()),
        sa.column("parent_id", sa.Integer()),
        sa.column("concept_id", sa.Uuid()),
        sa.column("parent_concept_id", sa.Uuid()),
    )
    existing_codes = connection.execute(
        sa.select(code_table.c.id, code_table.c.parent_id)
    ).all()
    concept_by_code_id = {code_id: uuid4() for code_id, _ in existing_codes}
    for code_id, parent_id in existing_codes:
        connection.execute(
            code_table.update()
            .where(code_table.c.id == code_id)
            .values(
                concept_id=concept_by_code_id[code_id],
                parent_concept_id=concept_by_code_id.get(parent_id),
            )
        )

    op.alter_column("code", "concept_id", existing_type=sa.Uuid(), nullable=False)
    op.alter_column(
        "code", "is_active", existing_type=sa.Boolean(), server_default=None
    )
    op.alter_column(
        "code", "is_deleted", existing_type=sa.Boolean(), server_default=None
    )
    op.drop_constraint(op.f("UC_code_name_unique_per_project"), "code", type_="unique")
    op.drop_index(op.f("ix_code_parent_id"), table_name="code")
    op.create_index(
        "UC_active_branch_code_concept",
        "code",
        ["project_id", "branch_id", "concept_id"],
        unique=True,
        postgresql_where=sa.text("branch_id IS NOT NULL AND is_active"),
    )
    op.create_index(
        "UC_active_branch_code_name",
        "code",
        ["project_id", "branch_id", "name"],
        unique=True,
        postgresql_where=sa.text(
            "branch_id IS NOT NULL AND is_active AND NOT is_deleted"
        ),
    )
    op.create_index(
        "UC_active_main_code_concept",
        "code",
        ["project_id", "concept_id"],
        unique=True,
        postgresql_where=sa.text("branch_id IS NULL AND is_active"),
    )
    op.create_index(
        "UC_active_main_code_name",
        "code",
        ["project_id", "name"],
        unique=True,
        postgresql_where=sa.text("branch_id IS NULL AND is_active AND NOT is_deleted"),
    )
    op.create_index(op.f("ix_code_author_id"), "code", ["author_id"], unique=False)
    op.create_index(
        op.f("ix_code_base_main_code_id"), "code", ["base_main_code_id"], unique=False
    )
    op.create_index(op.f("ix_code_branch_id"), "code", ["branch_id"], unique=False)
    op.create_index(op.f("ix_code_concept_id"), "code", ["concept_id"], unique=False)
    op.create_index(op.f("ix_code_is_active"), "code", ["is_active"], unique=False)
    op.create_index(op.f("ix_code_is_deleted"), "code", ["is_deleted"], unique=False)
    op.create_index(
        op.f("ix_code_parent_concept_id"), "code", ["parent_concept_id"], unique=False
    )
    op.drop_constraint(op.f("code_parent_code_id_fkey"), "code", type_="foreignkey")
    op.create_foreign_key(
        "FK_code_base_main_code_id_code_id",
        "code",
        "code",
        ["base_main_code_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        "FK_code_author_id_user_id",
        "code",
        "user",
        ["author_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        "FK_code_branch_id_codebranch_id",
        "code",
        "codebranch",
        ["branch_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_column("code", "parent_id")
    op.add_column(
        "sentenceannotation",
        sa.Column(
            "needs_review", sa.Boolean(), server_default=sa.false(), nullable=False
        ),
    )
    op.create_index(
        op.f("ix_sentenceannotation_needs_review"),
        "sentenceannotation",
        ["needs_review"],
        unique=False,
    )
    op.add_column(
        "spanannotation",
        sa.Column(
            "needs_review", sa.Boolean(), server_default=sa.false(), nullable=False
        ),
    )
    op.create_index(
        op.f("ix_spanannotation_needs_review"),
        "spanannotation",
        ["needs_review"],
        unique=False,
    )
    op.alter_column(
        "bboxannotation",
        "needs_review",
        existing_type=sa.Boolean(),
        server_default=None,
    )
    op.alter_column(
        "sentenceannotation",
        "needs_review",
        existing_type=sa.Boolean(),
        server_default=None,
    )
    op.alter_column(
        "spanannotation",
        "needs_review",
        existing_type=sa.Boolean(),
        server_default=None,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_spanannotation_needs_review"), table_name="spanannotation")
    op.drop_column("spanannotation", "needs_review")
    op.drop_index(
        op.f("ix_sentenceannotation_needs_review"), table_name="sentenceannotation"
    )
    op.drop_column("sentenceannotation", "needs_review")
    op.add_column(
        "code", sa.Column("parent_id", sa.INTEGER(), autoincrement=False, nullable=True)
    )
    op.drop_constraint("FK_code_branch_id_codebranch_id", "code", type_="foreignkey")
    op.drop_constraint("FK_code_author_id_user_id", "code", type_="foreignkey")
    op.drop_constraint("FK_code_base_main_code_id_code_id", "code", type_="foreignkey")
    op.create_foreign_key(
        op.f("code_parent_code_id_fkey"),
        "code",
        "code",
        ["parent_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_index(op.f("ix_code_parent_concept_id"), table_name="code")
    op.drop_index(op.f("ix_code_is_deleted"), table_name="code")
    op.drop_index(op.f("ix_code_is_active"), table_name="code")
    op.drop_index(op.f("ix_code_concept_id"), table_name="code")
    op.drop_index(op.f("ix_code_branch_id"), table_name="code")
    op.drop_index(op.f("ix_code_base_main_code_id"), table_name="code")
    op.drop_index(op.f("ix_code_author_id"), table_name="code")
    op.drop_index(
        "UC_active_main_code_name",
        table_name="code",
        postgresql_where=sa.text("branch_id IS NULL AND is_active AND NOT is_deleted"),
    )
    op.drop_index(
        "UC_active_main_code_concept",
        table_name="code",
        postgresql_where=sa.text("branch_id IS NULL AND is_active"),
    )
    op.drop_index(
        "UC_active_branch_code_name",
        table_name="code",
        postgresql_where=sa.text(
            "branch_id IS NOT NULL AND is_active AND NOT is_deleted"
        ),
    )
    op.drop_index(
        "UC_active_branch_code_concept",
        table_name="code",
        postgresql_where=sa.text("branch_id IS NOT NULL AND is_active"),
    )
    op.create_index(op.f("ix_code_parent_id"), "code", ["parent_id"], unique=False)
    op.create_unique_constraint(
        op.f("UC_code_name_unique_per_project"),
        "code",
        ["project_id", "name"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_column("code", "parent_concept_id")
    op.drop_column("code", "base_main_code_id")
    op.drop_column("code", "branch_id")
    op.drop_column("code", "commit_message")
    op.drop_column("code", "author_id")
    op.drop_column("code", "is_deleted")
    op.drop_column("code", "is_active")
    op.drop_column("code", "concept_id")
    op.drop_index(op.f("ix_bboxannotation_needs_review"), table_name="bboxannotation")
    op.drop_column("bboxannotation", "needs_review")
    op.drop_index(op.f("ix_codebranch_project_id"), table_name="codebranch")
    op.drop_index(op.f("ix_codebranch_name"), table_name="codebranch")
    op.drop_index(op.f("ix_codebranch_is_archived"), table_name="codebranch")
    op.drop_index(op.f("ix_codebranch_id"), table_name="codebranch")
    op.drop_index(op.f("ix_codebranch_created_by_id"), table_name="codebranch")
    op.drop_index(op.f("ix_codebranch_created"), table_name="codebranch")
    op.drop_index(
        "UC_active_code_branch_name_per_project",
        table_name="codebranch",
        postgresql_where=sa.text("NOT is_archived"),
    )
    op.drop_table("codebranch")
    # ### end Alembic commands ###
