"""add perspectives_action to perspectivehistory

Revision ID: 4e79b051e348
Revises: 02320d77b8dd
Create Date: 2025-12-17 13:02:39.967887

"""

from typing import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4e79b051e348"
down_revision: str | None = "02320d77b8dd"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "perspectivehistory",
        sa.Column("perspectives_action", sa.String(), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("perspectivehistory", "perspectives_action")
    # ### end Alembic commands ###
