"""Add token time starts and ends to sdoc data
Revision ID: 4eb64db5a67a
Revises: 050f9378a3e1
Create Date: 2025-01-09 17:00:29.037251

"""

from typing import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "4eb64db5a67a"
down_revision: str | None = "050f9378a3e1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # TODO: if anybody on production uses audio or video files
    # - read metadata word-level-transcriptions -> write to correpsonding new sdoc_data field
    # - read .transcript.txt files -> transfer to sdoc_data content & html of corresponding audio / video data
    # - if the transcript was annotated -> move all annotations to corresponding audio / video file annotations

    op.add_column(
        "sourcedocumentdata",
        sa.Column("token_time_starts", postgresql.ARRAY(sa.Integer()), nullable=True),
    )
    op.add_column(
        "sourcedocumentdata",
        sa.Column("token_time_ends", postgresql.ARRAY(sa.Integer()), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("sourcedocumentdata", "token_time_ends")
    op.drop_column("sourcedocumentdata", "token_time_starts")
    # ### end Alembic commands ###
