"""vscode launcher

Revision ID: 5ac5266784dd
Revises: 1b21abe44adb
Create Date: 2025-08-14 04:46:28.950223

"""

from typing import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5ac5266784dd"
down_revision: str | None = "1b21abe44adb"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "sourcedocument",
        sa.Column("sdoc_init", sa.Boolean(), server_default="false", nullable=False),
    )
    op.add_column(
        "sourcedocument",
        sa.Column(
            "extract_archive", sa.Boolean(), server_default="false", nullable=False
        ),
    )
    op.add_column(
        "sourcedocument",
        sa.Column("pdf_checking", sa.Boolean(), server_default="false", nullable=False),
    )
    op.add_column(
        "sourcedocument",
        sa.Column("extract_html", sa.Boolean(), server_default="false", nullable=False),
    )
    op.add_column(
        "sourcedocument",
        sa.Column(
            "text_extraction", sa.Boolean(), server_default="false", nullable=False
        ),
    )
    op.add_column(
        "sourcedocument",
        sa.Column(
            "text_language_detection",
            sa.Boolean(),
            server_default="false",
            nullable=False,
        ),
    )
    op.add_column(
        "sourcedocument",
        sa.Column("text_spacy", sa.Boolean(), server_default="false", nullable=False),
    )
    op.add_column(
        "sourcedocument",
        sa.Column(
            "text_es_index", sa.Boolean(), server_default="false", nullable=False
        ),
    )
    op.add_column(
        "sourcedocument",
        sa.Column(
            "text_sentence_embedding",
            sa.Boolean(),
            server_default="false",
            nullable=False,
        ),
    )
    op.add_column(
        "sourcedocument",
        sa.Column(
            "text_html_mapping", sa.Boolean(), server_default="false", nullable=False
        ),
    )
    op.add_column(
        "sourcedocument",
        sa.Column(
            "image_caption", sa.Boolean(), server_default="false", nullable=False
        ),
    )
    op.add_column(
        "sourcedocument",
        sa.Column(
            "image_embedding", sa.Boolean(), server_default="false", nullable=False
        ),
    )
    op.add_column(
        "sourcedocument",
        sa.Column(
            "image_metadata_extraction",
            sa.Boolean(),
            server_default="false",
            nullable=False,
        ),
    )
    op.add_column(
        "sourcedocument",
        sa.Column(
            "image_thumbnail", sa.Boolean(), server_default="false", nullable=False
        ),
    )
    op.add_column(
        "sourcedocument",
        sa.Column(
            "image_object_detection",
            sa.Boolean(),
            server_default="false",
            nullable=False,
        ),
    )
    op.add_column(
        "sourcedocument",
        sa.Column(
            "audio_metadata", sa.Boolean(), server_default="false", nullable=False
        ),
    )
    op.add_column(
        "sourcedocument",
        sa.Column(
            "audio_thumbnail", sa.Boolean(), server_default="false", nullable=False
        ),
    )
    op.add_column(
        "sourcedocument",
        sa.Column(
            "audio_transcription", sa.Boolean(), server_default="false", nullable=False
        ),
    )
    op.add_column(
        "sourcedocument",
        sa.Column(
            "video_metadata", sa.Boolean(), server_default="false", nullable=False
        ),
    )
    op.add_column(
        "sourcedocument",
        sa.Column(
            "video_thumbnail", sa.Boolean(), server_default="false", nullable=False
        ),
    )
    op.add_column(
        "sourcedocument",
        sa.Column(
            "video_audio_extraction",
            sa.Boolean(),
            server_default="false",
            nullable=False,
        ),
    )
    op.add_column(
        "sourcedocument",
        sa.Column(
            "processed",
            sa.Boolean(),
            sa.Computed(
                "CASE WHEN (doctype = 'text') THEN CASE WHEN (sdoc_init AND extract_html AND text_extraction AND text_es_index AND text_html_mapping AND text_language_detection AND text_spacy AND text_sentence_embedding) THEN true ELSE false END WHEN (doctype = 'image') THEN CASE WHEN (sdoc_init AND text_extraction AND text_es_index AND text_html_mapping AND text_language_detection AND text_spacy AND text_sentence_embedding AND image_caption AND image_embedding AND image_metadata_extraction AND image_object_detection AND image_thumbnail) THEN true ELSE false END WHEN (doctype = 'audio') THEN CASE WHEN (sdoc_init AND text_extraction AND text_es_index AND text_html_mapping AND text_language_detection AND text_spacy AND text_sentence_embedding AND audio_metadata AND audio_thumbnail AND audio_transcription) THEN true ELSE false END WHEN (doctype = 'video') THEN CASE WHEN (sdoc_init AND text_extraction AND text_es_index AND text_html_mapping AND text_language_detection AND text_spacy AND text_sentence_embedding AND audio_transcription AND video_audio_extraction AND video_metadata AND video_thumbnail) THEN true ELSE false END ELSE false END",
                persisted=True,
            ),
            nullable=False,
        ),
    )
    # FIXME: write migration
    op.drop_index("ix_sourcedocument_status", table_name="sourcedocument")
    op.create_index(
        op.f("ix_sourcedocument_processed"),
        "sourcedocument",
        ["processed"],
        unique=False,
    )
    op.drop_column("sourcedocument", "status")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "sourcedocument",
        sa.Column("status", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.drop_index(op.f("ix_sourcedocument_processed"), table_name="sourcedocument")
    op.create_index(
        "ix_sourcedocument_status", "sourcedocument", ["status"], unique=False
    )
    op.drop_column("sourcedocument", "processed")
    op.drop_column("sourcedocument", "video_audio_extraction")
    op.drop_column("sourcedocument", "video_thumbnail")
    op.drop_column("sourcedocument", "video_metadata")
    op.drop_column("sourcedocument", "audio_transcription")
    op.drop_column("sourcedocument", "audio_thumbnail")
    op.drop_column("sourcedocument", "audio_metadata")
    op.drop_column("sourcedocument", "image_object_detection")
    op.drop_column("sourcedocument", "image_thumbnail")
    op.drop_column("sourcedocument", "image_metadata_extraction")
    op.drop_column("sourcedocument", "image_embedding")
    op.drop_column("sourcedocument", "image_caption")
    op.drop_column("sourcedocument", "text_html_mapping")
    op.drop_column("sourcedocument", "text_sentence_embedding")
    op.drop_column("sourcedocument", "text_es_index")
    op.drop_column("sourcedocument", "text_spacy")
    op.drop_column("sourcedocument", "text_language_detection")
    op.drop_column("sourcedocument", "text_extraction")
    op.drop_column("sourcedocument", "extract_html")
    op.drop_column("sourcedocument", "pdf_checking")
    op.drop_column("sourcedocument", "extract_archive")
    op.drop_column("sourcedocument", "sdoc_init")
    # ### end Alembic commands ###
