"""codebook releases

Revision ID: 5b98d810b557
Revises: 18e1fd5996f5
Create Date: 2026-07-24 11:20:26.547023

"""

from typing import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5b98d810b557"
down_revision: str | None = "18e1fd5996f5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "codebookrelease",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("version", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column(
            "created", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["project.id"],
            name="FK_codebookrelease_project_id_project_id",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "project_id", "version", name="UC_codebook_release_version_per_project"
        ),
    )
    op.create_index(
        "IX_codebook_release_project_created",
        "codebookrelease",
        ["project_id", "created"],
        unique=False,
    )
    op.create_index(
        op.f("ix_codebookrelease_created"), "codebookrelease", ["created"], unique=False
    )
    op.create_index(
        op.f("ix_codebookrelease_id"), "codebookrelease", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_codebookrelease_project_id"),
        "codebookrelease",
        ["project_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_codebookrelease_version"), "codebookrelease", ["version"], unique=False
    )
    op.create_table(
        "codebookreleasecode",
        sa.Column("release_id", sa.Integer(), nullable=False),
        sa.Column("concept_id", sa.Uuid(), nullable=False),
        sa.Column("code_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["code_id"],
            ["code.id"],
            name="FK_codebookreleasecode_code_id_code_id",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["release_id"],
            ["codebookrelease.id"],
            name="FK_codebookreleasecode_release_id_codebookrelease_id",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("release_id", "concept_id"),
        sa.UniqueConstraint(
            "release_id", "code_id", name="UC_codebook_release_code_snapshot"
        ),
    )
    op.create_index(
        op.f("ix_codebookreleasecode_code_id"),
        "codebookreleasecode",
        ["code_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_codebookreleasecode_code_id"), table_name="codebookreleasecode"
    )
    op.drop_table("codebookreleasecode")
    op.drop_index(op.f("ix_codebookrelease_version"), table_name="codebookrelease")
    op.drop_index(op.f("ix_codebookrelease_project_id"), table_name="codebookrelease")
    op.drop_index(op.f("ix_codebookrelease_id"), table_name="codebookrelease")
    op.drop_index(op.f("ix_codebookrelease_created"), table_name="codebookrelease")
    op.drop_index("IX_codebook_release_project_created", table_name="codebookrelease")
    op.drop_table("codebookrelease")
    # ### end Alembic commands ###
