"""add tag unique constraint

Revision ID: 5bcc9d14725a
Revises: 00e56404d2b2
Create Date: 2024-10-07 13:03:01.694780

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5bcc9d14725a"
down_revision: Union[str, None] = "00e56404d2b2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("UC_name_unique_per_project", "code", type_="unique")
    op.create_unique_constraint(
        "UC_code_name_unique_per_project", "code", ["project_id", "name"]
    )
    op.create_unique_constraint(
        "UC_tag_name_unique_per_project", "documenttag", ["project_id", "name"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("UC_tag_name_unique_per_project", "documenttag", type_="unique")
    op.drop_constraint("UC_code_name_unique_per_project", "code", type_="unique")
    op.create_unique_constraint(
        "UC_name_unique_per_project", "code", ["project_id", "name"]
    )
    # ### end Alembic commands ###
