"""remove is_hierarchical column from aspect table

Revision ID: 6617866c6b24
Revises: 4e79b051e348
Create Date: 2025-12-17 13:57:21.059533

"""

from typing import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6617866c6b24"
down_revision: str | None = "4e79b051e348"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("aspect", "is_hierarchical")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "aspect",
        sa.Column("is_hierarchical", sa.BOOLEAN(), autoincrement=False, nullable=False),
    )
    # ### end Alembic commands ###
