"""add indices to wordfrequency

Revision ID: 6f484bc7d629
Revises: 7c617b019b45
Create Date: 2025-07-30 15:26:13.260886

"""

from typing import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6f484bc7d629"
down_revision: str | None = "7c617b019b45"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_wordfrequency_count"), "wordfrequency", ["count"], unique=False
    )
    op.create_index(
        op.f("ix_wordfrequency_sdoc_id"), "wordfrequency", ["sdoc_id"], unique=False
    )
    op.create_index(
        op.f("ix_wordfrequency_word"), "wordfrequency", ["word"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_wordfrequency_word"), table_name="wordfrequency")
    op.drop_index(op.f("ix_wordfrequency_sdoc_id"), table_name="wordfrequency")
    op.drop_index(op.f("ix_wordfrequency_count"), table_name="wordfrequency")
    # ### end Alembic commands ###
