"""add add raw_html to sourcedocumentdata

Revision ID: 7d121781ce13
Revises: 3eb39b9eb456
Create Date: 2025-11-24 15:08:28.438762

"""

from typing import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7d121781ce13"
down_revision: str | None = "3eb39b9eb456"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 1) add column as nullable so we can populate it from the existing `html` column
    op.add_column(
        "sourcedocumentdata", sa.Column("raw_html", sa.String(), nullable=True)
    )

    # 2) copy existing content from `html` into the new `raw_html` column
    # We'll do this in batches by project to make the migration friendlier on very
    # large tables and to provide progress output.
    bind = op.get_bind()

    # fetch all project ids
    projects = [
        row[0] for row in bind.execute(sa.text("SELECT id FROM project")).fetchall()
    ]
    print(f"Found {len(projects)} projects")

    for pid in projects:
        # count how many source documents belong to this project
        count = bind.execute(
            sa.text(
                "SELECT COUNT(*) FROM sourcedocumentdata sd JOIN sourcedocument s ON sd.id = s.id WHERE s.project_id = :pid"
            ),
            {"pid": pid},
        ).scalar()
        print(f"Processing project {pid}: {count} source document data rows")

        if count == 0:
            continue

        # Update rows for this project. Uses Postgres' UPDATE...FROM syntax.
        bind.execute(
            sa.text(
                "UPDATE sourcedocumentdata sd SET raw_html = sd.html FROM sourcedocument s WHERE sd.id = s.id AND s.project_id = :pid"
            ),
            {"pid": pid},
        )

    # 3) after the data copy, make the column non-nullable to enforce presence
    op.alter_column(
        "sourcedocumentdata",
        "raw_html",
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("sourcedocumentdata", "raw_html")
    # ### end Alembic commands ###
