"""remove cluster hierarchy

Revision ID: 7e88b47a2f6c
Revises: 781d4852a256
Create Date: 2025-12-11 09:22:57.085470

"""

from typing import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7e88b47a2f6c"
down_revision: str | None = "781d4852a256"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_cluster_parent_cluster_id", table_name="cluster")
    op.drop_constraint("cluster_parent_cluster_id_fkey", "cluster", type_="foreignkey")
    op.drop_column("cluster", "parent_cluster_id")
    op.drop_column("cluster", "level")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "cluster", sa.Column("level", sa.INTEGER(), autoincrement=False, nullable=False)
    )
    op.add_column(
        "cluster",
        sa.Column(
            "parent_cluster_id", sa.INTEGER(), autoincrement=False, nullable=True
        ),
    )
    op.create_foreign_key(
        "cluster_parent_cluster_id_fkey",
        "cluster",
        "cluster",
        ["parent_cluster_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_index(
        "ix_cluster_parent_cluster_id", "cluster", ["parent_cluster_id"], unique=False
    )
    # ### end Alembic commands ###
