"""memo search system rework

Revision ID: 9c56981db5cc
Revises: a2821ff663ec
Create Date: 2026-08-19 13:03:37.129737

"""

from typing import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9c56981db5cc"
down_revision: str | None = "a2821ff663ec"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "memofavoritelinktable",
        sa.Column("memo_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["memo_id"], ["memo.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("memo_id", "user_id"),
    )
    op.create_index(
        "ix_memofavoritelinktable_memo_id",
        "memofavoritelinktable",
        ["memo_id"],
        unique=False,
    )

    # Migrate existing starred flags to per-user favorites.
    # The old boolean could not record who starred, so the star is
    # attributed to the memo's author.
    op.execute(
        sa.text(
            """
            INSERT INTO memofavoritelinktable (memo_id, user_id)
            SELECT id, user_id
            FROM memo
            WHERE starred IS TRUE
            ON CONFLICT (memo_id, user_id) DO NOTHING
            """
        )
    )

    op.create_table(
        "searchview",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("entity_type", sa.String(), nullable=False),
        sa.Column("layout", sa.String(), nullable=False),
        sa.Column("filters", sa.JSON(), nullable=False),
        sa.Column("group_by", sa.JSON(), nullable=True),
        sa.Column("sorts", sa.JSON(), nullable=True),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column(
            "created", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["project_id"], ["project.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_searchview_user_project_entity_lower_name",
        "searchview",
        ["user_id", "project_id", "entity_type", sa.literal_column("lower(name)")],
        unique=True,
    )
    op.create_index(
        "idx_searchview_user_project_entity_position",
        "searchview",
        ["user_id", "project_id", "entity_type", "position"],
        unique=False,
    )
    op.create_index(op.f("ix_searchview_id"), "searchview", ["id"], unique=False)
    op.create_index(
        op.f("ix_searchview_project_id"), "searchview", ["project_id"], unique=False
    )
    op.create_index(
        op.f("ix_searchview_user_id"), "searchview", ["user_id"], unique=False
    )
    op.add_column("memo", sa.Column("icon", sa.String(length=64), nullable=True))

    # Only remove the exact untouched placeholder created for project members.
    # Renamed or edited project Memos are intentionally preserved as pages.
    op.execute(
        sa.text(
            """
            DELETE FROM memo
            USING objecthandle
            WHERE memo.attached_to_id = objecthandle.id
              AND objecthandle.project_id IS NOT NULL
              AND memo.title = 'Project Memo'
              AND memo.content = ''
              AND memo.content_json = ''
            """
        )
    )

    op.drop_index(op.f("ix_memo_starred"), table_name="memo")
    op.create_index(
        "idx_memo_project_updated", "memo", ["project_id", "updated"], unique=False
    )
    op.drop_column("memo", "starred")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # The untouched placeholder Memos deleted by upgrade cannot be reconstructed.
    op.add_column(
        "memo",
        sa.Column(
            "starred",
            sa.BOOLEAN(),
            server_default=sa.false(),
            autoincrement=False,
            nullable=False,
        ),
    )
    # Restore the starred flags from the memo authors' favorites.
    op.execute(
        sa.text(
            """
            UPDATE memo
            SET starred = TRUE
            WHERE EXISTS (
                SELECT 1
                FROM memofavoritelinktable
                WHERE memofavoritelinktable.memo_id = memo.id
                  AND memofavoritelinktable.user_id = memo.user_id
            )
            """
        )
    )
    op.drop_index("idx_memo_project_updated", table_name="memo")
    op.create_index(op.f("ix_memo_starred"), "memo", ["starred"], unique=False)
    op.drop_column("memo", "icon")
    op.drop_index(op.f("ix_searchview_user_id"), table_name="searchview")
    op.drop_index(op.f("ix_searchview_project_id"), table_name="searchview")
    op.drop_index(op.f("ix_searchview_id"), table_name="searchview")
    op.drop_index(
        "idx_searchview_user_project_entity_position", table_name="searchview"
    )
    op.drop_index(
        "idx_searchview_user_project_entity_lower_name", table_name="searchview"
    )
    op.drop_table("searchview")
    op.drop_index(
        "ix_memofavoritelinktable_memo_id", table_name="memofavoritelinktable"
    )
    op.drop_table("memofavoritelinktable")
    # ### end Alembic commands ###
