"""add class metrics column to classifier evaluation table

Revision ID: a2821ff663ec
Revises: 16b735a5f8f5
Create Date: 2026-08-10 10:43:02.943672

"""

from typing import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a2821ff663ec"
down_revision: str | None = "16b735a5f8f5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "classifierevaluation",
        sa.Column("class_metrics", sa.JSON(), server_default="[]", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("classifierevaluation", "class_metrics")
    # ### end Alembic commands ###
