"""add confusion matrix

Revision ID: a78b4d29b271
Revises: ce6c645c2f80
Create Date: 2026-09-06 07:30:01.388749

"""

from typing import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a78b4d29b271"
down_revision: str | None = "ce6c645c2f80"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "classifierevaluation",
        sa.Column("confusion_matrix", sa.JSON(), server_default="[]", nullable=False),
    )
    op.add_column(
        "classifierevaluation",
        sa.Column(
            "confusion_matrix_class_ids", sa.JSON(), server_default="[]", nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("classifierevaluation", "confusion_matrix_class_ids")
    op.drop_column("classifierevaluation", "confusion_matrix")
    # ### end Alembic commands ###
