"""vscode launcher

Revision ID: a7d974acc6f2
Revises: 28ac2cff18f1
Create Date: 2026-07-23 13:38:39.815849

"""

from typing import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a7d974acc6f2"
down_revision: str | None = "28ac2cff18f1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_bboxannotation_needs_review"), table_name="bboxannotation")
    op.drop_column("bboxannotation", "needs_review")
    op.drop_index(
        op.f("ix_sentenceannotation_needs_review"), table_name="sentenceannotation"
    )
    op.drop_column("sentenceannotation", "needs_review")
    op.drop_index(op.f("ix_spanannotation_needs_review"), table_name="spanannotation")
    op.drop_column("spanannotation", "needs_review")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "spanannotation",
        sa.Column(
            "needs_review",
            sa.BOOLEAN(),
            server_default=sa.false(),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.create_index(
        op.f("ix_spanannotation_needs_review"),
        "spanannotation",
        ["needs_review"],
        unique=False,
    )
    op.add_column(
        "sentenceannotation",
        sa.Column(
            "needs_review",
            sa.BOOLEAN(),
            server_default=sa.false(),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.create_index(
        op.f("ix_sentenceannotation_needs_review"),
        "sentenceannotation",
        ["needs_review"],
        unique=False,
    )
    op.add_column(
        "bboxannotation",
        sa.Column(
            "needs_review",
            sa.BOOLEAN(),
            server_default=sa.false(),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.create_index(
        op.f("ix_bboxannotation_needs_review"),
        "bboxannotation",
        ["needs_review"],
        unique=False,
    )
    # ### end Alembic commands ###
