"""add memo recnet table

Revision ID: b4d00d5e276b
Revises: 9c56981db5cc
Create Date: 2026-08-22 09:56:34.497908

"""

from typing import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b4d00d5e276b"
down_revision: str | None = "9c56981db5cc"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "memorecent",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("memo_id", sa.Integer(), nullable=False),
        sa.Column(
            "last_opened",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["memo_id"], ["memo.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id", "memo_id"),
    )
    op.create_index(
        "ix_memorecent_user_last_opened",
        "memorecent",
        ["user_id", "last_opened"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_memorecent_user_last_opened", table_name="memorecent")
    op.drop_table("memorecent")
    # ### end Alembic commands ###
