"""add apikey table

Revision ID: b6c6a1f6c0b9
Revises: 16b735a5f8f5
Create Date: 2026-08-12 12:38:48.139260

"""

from typing import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b6c6a1f6c0b9"
down_revision: str | None = "16b735a5f8f5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "apikey",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("prefix", sa.String(), nullable=False),
        sa.Column("hashed_key", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_apikey_hashed_key"), "apikey", ["hashed_key"], unique=True)
    op.create_index(op.f("ix_apikey_id"), "apikey", ["id"], unique=False)
    op.create_index(op.f("ix_apikey_user_id"), "apikey", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_apikey_user_id"), table_name="apikey")
    op.drop_index(op.f("ix_apikey_id"), table_name="apikey")
    op.drop_index(op.f("ix_apikey_hashed_key"), table_name="apikey")
    op.drop_table("apikey")
    # ### end Alembic commands ###
