"""update perspectives aspect with modality, pipeline_settings and tag_id

Revision ID: bd2222f8198d
Revises: 7d121781ce13
Create Date: 2025-12-03 13:36:30.892057

"""

from typing import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "bd2222f8198d"
down_revision: str | None = "7d121781ce13"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "aspect",
        sa.Column("modality", sa.String(), server_default="text", nullable=False),
    )
    op.add_column(
        "aspect",
        sa.Column(
            "pipeline_settings",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
    )
    op.add_column("aspect", sa.Column("tag_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "aspect", "tag", ["tag_id"], ["id"], ondelete="CASCADE")
    # ### end Alembic commands ###


def downgrade() -> None:
    pass
