"""add sdoc status

Revision ID: c6ad83dabcfa
Revises: 1b21abe44adb
Create Date: 2025-08-13 13:38:30.574721

"""

from typing import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c6ad83dabcfa"
down_revision: str | None = "1b21abe44adb"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sourcedocumentstatus",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("sdoc_init", sa.Boolean(), server_default="false", nullable=False),
        sa.Column(
            "extract_archive", sa.Boolean(), server_default="false", nullable=False
        ),
        sa.Column("pdf_checking", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("extract_html", sa.Boolean(), server_default="false", nullable=False),
        sa.Column(
            "text_extraction", sa.Boolean(), server_default="false", nullable=False
        ),
        sa.Column(
            "text_language_detection",
            sa.Boolean(),
            server_default="false",
            nullable=False,
        ),
        sa.Column("text_spacy", sa.Boolean(), server_default="false", nullable=False),
        sa.Column(
            "text_es_index", sa.Boolean(), server_default="false", nullable=False
        ),
        sa.Column(
            "text_sentence_embedding",
            sa.Boolean(),
            server_default="false",
            nullable=False,
        ),
        sa.Column(
            "text_html_mapping", sa.Boolean(), server_default="false", nullable=False
        ),
        sa.Column(
            "image_caption", sa.Boolean(), server_default="false", nullable=False
        ),
        sa.Column(
            "image_embedding", sa.Boolean(), server_default="false", nullable=False
        ),
        sa.Column(
            "image_metadata_extraction",
            sa.Boolean(),
            server_default="false",
            nullable=False,
        ),
        sa.Column(
            "image_thumbnail", sa.Boolean(), server_default="false", nullable=False
        ),
        sa.Column(
            "image_object_detection",
            sa.Boolean(),
            server_default="false",
            nullable=False,
        ),
        sa.Column(
            "audio_metadata", sa.Boolean(), server_default="false", nullable=False
        ),
        sa.Column(
            "audio_thumbnail", sa.Boolean(), server_default="false", nullable=False
        ),
        sa.Column(
            "audio_transcription", sa.Boolean(), server_default="false", nullable=False
        ),
        sa.Column(
            "video_metadata", sa.Boolean(), server_default="false", nullable=False
        ),
        sa.Column(
            "video_thumbnail", sa.Boolean(), server_default="false", nullable=False
        ),
        sa.Column(
            "video_audio_extraction",
            sa.Boolean(),
            server_default="false",
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["id"], ["sourcedocument.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_sourcedocumentstatus_id"), "sourcedocumentstatus", ["id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_sourcedocumentstatus_id"), table_name="sourcedocumentstatus")
    op.drop_table("sourcedocumentstatus")
    # ### end Alembic commands ###
