"""add selected properties to search view

Revision ID: ce6c645c2f80
Revises: b4d00d5e276b
Create Date: 2026-08-24 11:46:48.326862

"""

from typing import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ce6c645c2f80"
down_revision: str | None = "b4d00d5e276b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "searchview", sa.Column("selected_properties", sa.JSON(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("searchview", "selected_properties")
    # ### end Alembic commands ###
