"""add new json column to memo table

Revision ID: de0c6bd65d37
Revises: 7393d4227260
Create Date: 2024-10-24 08:15:41.653161

"""

from typing import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "de0c6bd65d37"
down_revision: str | None = "7393d4227260"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.add_column("memo", sa.Column("content_json", sa.String(), nullable=True))

    # update all existing memos: copy the content to the new content_json column
    op.execute("""
        UPDATE memo
        SET content_json = CONCAT('[{"id":"cf5fd551-9480-414b-abb0-e02718b83ff4","type":"paragraph","props":{"textColor":"default","backgroundColor":"default","textAlignment":"left"},"content":[{"type":"text","text":"', content, '","styles":{}}],"children":[]}]')
        WHERE content IS NOT NULL
    """)

    # update all existing memos: set the content_json column to default value
    op.execute("""
        UPDATE memo
        SET content_json = ''
        WHERE content IS NULL
    """)

    op.alter_column("memo", "content_json", nullable=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("memo", "content_json")
    # ### end Alembic commands ###
