import * as d3 from "d3";

export enum D3ColorScale {
  blues = "Blues",
  greens = "Greens",
  greys = "Greys",
  oranges = "Oranges",
  purples = "Purples",
  reds = "Reds",
  viridis = "Viridis",
  inferno = "Inferno",
  magma = "Magma",
  plasma = "Plasma",
  cividis = "Cividis",
  turbo = "Turbo",
  warm = "Warm",
  cool = "Cool",
  buGn = "BuGn",
  buPu = "BuPu",
  gnBu = "GnBu",
  orRd = "OrRd",
  puBuGn = "PuBuGn",
  puBu = "PuBu",
  puRd = "PuRd",
  rdPu = "RdPu",
  ylGnBu = "YlGnBu",
  ylGn = "YlGn",
  ylOrBr = "YlOrBr",
  ylOrRd = "YlOrRd",
}

export const d3ColorSchemes: Record<D3ColorScale, (value: number) => string> = {
  [D3ColorScale.blues]: d3.interpolateBlues,
  [D3ColorScale.greens]: d3.interpolateGreens,
  [D3ColorScale.greys]: d3.interpolateGreys,
  [D3ColorScale.oranges]: d3.interpolateOranges,
  [D3ColorScale.purples]: d3.interpolatePurples,
  [D3ColorScale.reds]: d3.interpolateReds,
  [D3ColorScale.viridis]: d3.interpolateViridis,
  [D3ColorScale.inferno]: d3.interpolateInferno,
  [D3ColorScale.magma]: d3.interpolateMagma,
  [D3ColorScale.plasma]: d3.interpolatePlasma,
  [D3ColorScale.cividis]: d3.interpolateCividis,
  [D3ColorScale.turbo]: d3.interpolateTurbo,
  [D3ColorScale.warm]: d3.interpolateWarm,
  [D3ColorScale.cool]: d3.interpolateCool,
  [D3ColorScale.buGn]: d3.interpolateBuGn,
  [D3ColorScale.buPu]: d3.interpolateBuPu,
  [D3ColorScale.gnBu]: d3.interpolateGnBu,
  [D3ColorScale.orRd]: d3.interpolateOrRd,
  [D3ColorScale.puBuGn]: d3.interpolatePuBuGn,
  [D3ColorScale.puBu]: d3.interpolatePuBu,
  [D3ColorScale.puRd]: d3.interpolatePuRd,
  [D3ColorScale.rdPu]: d3.interpolateRdPu,
  [D3ColorScale.ylGnBu]: d3.interpolateYlGnBu,
  [D3ColorScale.ylGn]: d3.interpolateYlGn,
  [D3ColorScale.ylOrBr]: d3.interpolateYlOrBr,
  [D3ColorScale.ylOrRd]: d3.interpolateYlOrRd,
};
