api:
  port: ${oc.env:API_PORT, 5000}
  max_upload_file_size: 104857600 # 100 MB in bytes
  auth:
    jwt:
      token_url: /user/login
      ttl: ${oc.env:JWT_TTL, 600} # seconds
      algo: ${oc.env:JWT_ALGO, HS256}
      secret: ${oc.env:JWT_SECRET, ""}

repo:
  root_directory: /home/7schneid/gitrepos/dwts/docker/backend_repo
  content_server:
    https: False
    host: ${oc.env:CONTENT_SERVER_HOST, 127.0.0.1}
    port: ${oc.env:CONTENT_SERVER_EXPOSED, 13134}
    context_path: /

system_codes:
  # text codes from spacy NER models (spans)
  NAMED_ENTITY:
    desc: "A named entity"
    children:
      CARDINAL:
        desc: "Numerals that do not fall under another type"
      DATE:
        desc: "Absolute or relative dates or periods"
      EVENT:
        desc: "Named hurricanes, battles, wars, sports events, etc."
      FAC:
        desc: "Buildings, airports, highways, bridges, etc."
      GPE:
        desc: "Countries, cities, states"
      LANGUAGE:
        desc: "Any named language"
      LAW:
        desc: "Named documents made into laws."
      LOC:
        desc: "Non-GPE locations, mountain ranges, bodies of water"
      MONEY:
        desc: "Monetary values, including unit"
      NORP:
        desc: "Nationalities or religious or political groups"
      ORDINAL:
        desc: "'first', 'second', etc."
      ORG:
        desc: "Companies, agencies, institutions, etc."
      PERCENT:
        desc: "Percentage, including '%'"
      PERSON:
        desc: "People, including fictional"
      PRODUCT:
        desc: "Objects, vehicles, foods, etc. (not services)"
      QUANTITY:
        desc: "Measurements, as of weight or distance"
      TIME:
        desc: "Times smaller than a day"
      WORK_OF_ART:
        desc: "Titles of books, songs, etc."
      MISC:
        desc: "Miscellaneous entities, e.g. events, nationalities, products or works of art"
  SENTENCE:
    desc: "A sentence spanning multiple Tokens."
  # image codes from COCO 2017 (bbox)
  ACCESSORY:
    desc: Super Object Category from COCO 2017
    children:
      BACKPACK:
        desc: Object Category from COCO 2017
      EYE GLASSES:
        desc: Object Category from COCO 2017
      HANDBAG:
        desc: Object Category from COCO 2017
      HAT:
        desc: Object Category from COCO 2017
      SHOE:
        desc: Object Category from COCO 2017
      SUITCASE:
        desc: Object Category from COCO 2017
      TIE:
        desc: Object Category from COCO 2017
      UMBRELLA:
        desc: Object Category from COCO 2017
  ANIMAL:
    desc: Super Object Category from COCO 2017
    children:
      BEAR:
        desc: Object Category from COCO 2017
      BIRD:
        desc: Object Category from COCO 2017
      CAT:
        desc: Object Category from COCO 2017
      COW:
        desc: Object Category from COCO 2017
      DOG:
        desc: Object Category from COCO 2017
      ELEPHANT:
        desc: Object Category from COCO 2017
      GIRAFFE:
        desc: Object Category from COCO 2017
      HORSE:
        desc: Object Category from COCO 2017
      SHEEP:
        desc: Object Category from COCO 2017
      ZEBRA:
        desc: Object Category from COCO 2017
  APPLIANCE:
    desc: Super Object Category from COCO 2017
    children:
      BLENDER:
        desc: Object Category from COCO 2017
      MICROWAVE:
        desc: Object Category from COCO 2017
      OVEN:
        desc: Object Category from COCO 2017
      REFRIGERATOR:
        desc: Object Category from COCO 2017
      SINK:
        desc: Object Category from COCO 2017
      TOASTER:
        desc: Object Category from COCO 2017
  BACKGROUND:
    desc: Super Object Category from COCO 2017
  ELECTRONIC:
    desc: Super Object Category from COCO 2017
    children:
      CELL PHONE:
        desc: Object Category from COCO 2017
      KEYBOARD:
        desc: Object Category from COCO 2017
      LAPTOP:
        desc: Object Category from COCO 2017
      MOUSE:
        desc: Object Category from COCO 2017
      REMOTE:
        desc: Object Category from COCO 2017
      TV:
        desc: Object Category from COCO 2017
  FOOD:
    desc: Super Object Category from COCO 2017
    children:
      APPLE:
        desc: Object Category from COCO 2017
      BANANA:
        desc: Object Category from COCO 2017
      BROCCOLI:
        desc: Object Category from COCO 2017
      CAKE:
        desc: Object Category from COCO 2017
      CARROT:
        desc: Object Category from COCO 2017
      DONUT:
        desc: Object Category from COCO 2017
      HOT DOG:
        desc: Object Category from COCO 2017
      ORANGE:
        desc: Object Category from COCO 2017
      PIZZA:
        desc: Object Category from COCO 2017
      SANDWICH:
        desc: Object Category from COCO 2017
  FURNITURE:
    desc: Super Object Category from COCO 2017
    children:
      BED:
        desc: Object Category from COCO 2017
      CHAIR:
        desc: Object Category from COCO 2017
      COUCH:
        desc: Object Category from COCO 2017
      DESK:
        desc: Object Category from COCO 2017
      DINING TABLE:
        desc: Object Category from COCO 2017
      DOOR:
        desc: Object Category from COCO 2017
      MIRROR:
        desc: Object Category from COCO 2017
      POTTED PLANT:
        desc: Object Category from COCO 2017
      TOILET:
        desc: Object Category from COCO 2017
      WINDOW:
        desc: Object Category from COCO 2017
  INDOOR:
    desc: Super Object Category from COCO 2017
    children:
      BOOK:
        desc: Object Category from COCO 2017
      CLOCK:
        desc: Object Category from COCO 2017
      HAIR BRUSH:
        desc: Object Category from COCO 2017
      HAIR DRIER:
        desc: Object Category from COCO 2017
      SCISSORS:
        desc: Object Category from COCO 2017
      TEDDY BEAR:
        desc: Object Category from COCO 2017
      TOOTHBRUSH:
        desc: Object Category from COCO 2017
      VASE:
        desc: Object Category from COCO 2017
  KITCHEN:
    desc: Super Object Category from COCO 2017
    children:
      BOTTLE:
        desc: Object Category from COCO 2017
      BOWL:
        desc: Object Category from COCO 2017
      CUP:
        desc: Object Category from COCO 2017
      FORK:
        desc: Object Category from COCO 2017
      KNIFE:
        desc: Object Category from COCO 2017
      PLATE:
        desc: Object Category from COCO 2017
      SPOON:
        desc: Object Category from COCO 2017
      WINE GLASS:
        desc: Object Category from COCO 2017
  OUTDOOR:
    desc: Super Object Category from COCO 2017
    children:
      BENCH:
        desc: Object Category from COCO 2017
      FIRE HYDRANT:
        desc: Object Category from COCO 2017
      PARKING METER:
        desc: Object Category from COCO 2017
      STOP SIGN:
        desc: Object Category from COCO 2017
      STREET SIGN:
        desc: Object Category from COCO 2017
      TRAFFIC LIGHT:
        desc: Object Category from COCO 2017
  PERSON:
    desc: Super Object Category from COCO 2017
    children:
      PERSON:
        desc: Object Category from COCO 2017
  SPORTS:
    desc: Super Object Category from COCO 2017
    children:
      BASEBALL BAT:
        desc: Object Category from COCO 2017
      BASEBALL GLOVE:
        desc: Object Category from COCO 2017
      FRISBEE:
        desc: Object Category from COCO 2017
      KITE:
        desc: Object Category from COCO 2017
      SKATEBOARD:
        desc: Object Category from COCO 2017
      SKIS:
        desc: Object Category from COCO 2017
      SNOWBOARD:
        desc: Object Category from COCO 2017
      SPORTS BALL:
        desc: Object Category from COCO 2017
      SURFBOARD:
        desc: Object Category from COCO 2017
      TENNIS RACKET:
        desc: Object Category from COCO 2017
  VEHICLE:
    desc: Super Object Category from COCO 2017
    children:
      AIRPLANE:
        desc: Object Category from COCO 2017
      BICYCLE:
        desc: Object Category from COCO 2017
      BOAT:
        desc: Object Category from COCO 2017
      BUS:
        desc: Object Category from COCO 2017
      CAR:
        desc: Object Category from COCO 2017
      MOTORCYCLE:
        desc: Object Category from COCO 2017
      TRAIN:
        desc: Object Category from COCO 2017
      TRUCK:
        desc: Object Category from COCO 2017

docprepro:
  text:
    spacy:
      # note that the spacy models have to be installed in the env to use it! (docker!)
      models:
        en: "/spacy_models/en_core_web_trf-3.4.1"
        de: "/spacy_models/de_core_news_lg-3.4.0"
        it: "/spacy_models/it_core_news_lg-3.4.0"
        default: "en"

      device: cpu # cpu is faster if concurrency is high!
      max_text_length: 2000000 # in characters (1000000 is spaCy default)
    bulk_threshold: 100

  image:
    object_detection:
      model: "facebook/detr-resnet-101"
      confidence_threshold: 0.3
      device: cpu
    image_captioning:
      model: "nlpconnect/vit-gpt2-image-captioning"
      max_caption_length: 16
      num_beams: 4
      device: cpu

  simsearch:
    # see https://huggingface.co/sentence-transformers/clip-ViT-B-32-multilingual-v1
    image_encoder:
      model: "clip-ViT-B-32"
      batch_size: 32
      device: cpu
    text_encoder:
      model: "sentence-transformers/clip-ViT-B-32-multilingual-v1"
      batch_size: 32
      device: cpu
      min_sentence_length: 5

  celery:
    batch_size:
      text: 200
      image: 10
    backend:
      host: ${oc.env:REDIS_HOST, localhost}
      port: ${oc.env:REDIS_PORT, 6379}
      db: 0
      password: ${oc.env:REDIS_PASSWORD, dwts123}
    broker:
      host: ${oc.env:RABBITMQ_HOST, localhost}
      port: ${oc.env:RABBITMQ_PORT, 5672}
      user: ${oc.env:RABBITMQ_USER, dwtsuser}
      password: ${oc.env:RABBITMQ_PASSWORD, dwts123}


postgres:
  host: ${oc.env:POSTGRES_HOST, 127.0.0.1}
  port: ${oc.env:POSTGRES_PORT, 5432}
  db: ${oc.env:POSTGRES_DB, dwts}
  user: ${oc.env:POSTGRES_USER, dwtsuser}
  password: ${oc.env:POSTGRES_PASSWORD, dwts123}


redis:
  host: ${oc.env:REDIS_HOST, localhost}
  port: ${oc.env:REDIS_PORT, 6379}
  password: ${oc.env:REDIS_PASSWORD, dwts123}
  clients:
    feedback: 1 # name: redis db index -- DO NOT USE DB 0, it's reserved for RabbitMQ!

logging:
  max_file_size: 500 # MB
  level: ${oc.env:LOG_LEVEL, debug}

elasticsearch:
  host: ${oc.env:ES_HOST, 127.0.0.1}
  port: ${oc.env:ES_PORT, 9200}
  use_ssl: False
  verify_certs: False
  sniff_on_start: False
  sniff_on_connection_fail: False
  sniffer_timeout: 120
  index_mappings:
    docs: configs/default_sdoc_index_mapping.json
    memos: configs/default_memo_index_mapping.json
  index_settings:
    docs:
    memos:

faiss:
  # see https://github.com/facebookresearch/faiss/wiki/Guidelines-to-choose-an-index
  index_factory_string: "IDMap,Flat"
  index_search_metric: IP # or L2
  index_dimension: 512 # has to match the encoder dimensions!
  device: cpu
