api:
  port: 5500
  max_upload_file_size: 104857600 # 100 MB in bytes
  production_mode: 1
  auth:
    jwt:
      token_url: /authentication/login
      access_ttl: 10800 # 3h in seconds
      refresh_ttl: 2592000 # 30 days in seconds
      algo: HS256
      secret: ${oc.env:JWT_SECRET, ""}

system_user:
  first_name: SYSTEM
  last_name: USER
  email: ${oc.env:SYSTEM_USER_EMAIL, "SYSTEM@dats.org"}
  password: ${oc.env:SYSTEM_USER_PASSWORD, "12SYSTEM34"}

demo_user:
  first_name: DEMO
  last_name: USER
  email: demo@example.org
  password: demo

assistant_user:
  first_name: Assistant
  last_name: User
  email: assistant@dats.org
  password: ${oc.env:SYSTEM_USER_PASSWORD, "12SYSTEM34"}

ray:
  protocol: ${oc.env:RAY_PROTOCOL, http}
  host: ${oc.env:RAY_HOST, ray}
  port: ${oc.env:RAY_PORT, 8000}

repo:
  root_directory: /tmp/dats
  content_server:
    https: False
    host: lighttpd
    port: 80
    context_path: /

celery:
  backend:
    host: redis
    port: 6379
    db: 0
    password: ${oc.env:REDIS_PASSWORD, dats123}
  broker:
    host: rabbitmq
    port: 5672
    user: ${oc.env:RABBITMQ_USER, datsuser}
    password: ${oc.env:RABBITMQ_PASSWORD, dats123}
  preprocessing:
    extract_images_from_pdf: True
    extract_images_from_docx: True

vector_index:
  service: ${oc.env:VECTOR_INDEX, weaviate}

weaviate:
  host: weaviate
  port: 8080

typesense:
  host: typesense
  port: 8108
  api_key: ${oc.env:TYPESENSE_API_KEY, dats123}

qdrant:
  host: qdrant
  port: 6333
  grpc_port: 6334

postgres:
  host: postgres
  port: 5432
  db: ${oc.env:POSTGRES_DB, dats}
  user: ${oc.env:POSTGRES_USER, datsuser}
  password: ${oc.env:POSTGRES_PASSWORD, dats123}
  pool:
    pool_size: 32
    max_overflow: 16

mail:
  enabled: ${oc.env:MAIL_ENABLED, False}
  mail: ${oc.env:MAIL_FROM, dats@uni-hamburg.de}
  user: ${oc.env:MAIL_USERNAME, "user"}
  password: ${oc.env:MAIL_PASSWORD, "pass"}
  server: ${oc.env:MAIL_SERVER, exchange.uni-hamburg.de}
  port: ${oc.env:MAIL_PORT, 587}
  starttls: ${oc.env:MAIL_STARTTLS, True}
  ssl_tls: ${oc.env:MAIL_SSL_TLS, False}
  use_credentials: ${oc.env:MAIL_USE_CREDENTIALS, True}
  validate_certs: ${oc.env:MAIL_VALIDATE_CERTS, True}

redis:
  host: redis
  port: 6379
  password: ${oc.env:REDIS_PASSWORD, dats123}
  clients:
    export: 2
    crawler: 3
    trainer: 4
    cota: 5
    llm: 6
    import_: 7
    ml: 8

logging:
  max_file_size: 500 # MB
  level: ${oc.env:LOG_LEVEL, warning}

elasticsearch:
  host: elasticsearch
  port: 9200
  use_ssl: False
  verify_certs: False
  sniff_on_start: False
  sniff_on_connection_fail: False
  sniffer_timeout: 120
  index_mappings:
    docs: configs/default_sdoc_index_mapping.json
    memos: configs/default_memo_index_mapping.json
  index_settings:
    docs: configs/default_sdoc_index_settings.json
    memos: configs/default_memo_index_settings.json

ollama:
  host: ${oc.env:OLLAMA_HOST, ollama}
  port: ${oc.env:OLLAMA_PORT, 11434}
  model: ${oc.env:OLLAMA_MODEL, gemma2:9b-instruct-fp16}
  context_size: 8192

llm_assistant:
  sentence_annotation:
    few_shot_threshold: 4
    model_training_threshold: 100

project_metadata:
  text_url:
    key: "url"
    metatype: "STRING"
    read_only: True
    doctype: "text"
    description: "The URL of the document"
  text_language:
    key: "language"
    metatype: "STRING"
    read_only: True
    doctype: "text"
    description: "The language of the document"
  text_keywords:
    key: "keywords"
    metatype: "LIST"
    read_only: True
    doctype: "text"
    description: "Keywords extracted from the document"

  image_url:
    key: "url"
    metatype: "STRING"
    read_only: True
    doctype: "image"
    description: "The URL of the image"
  image_keywords:
    key: "keywords"
    metatype: "LIST"
    read_only: True
    doctype: "image"
    description: "Keywords extracted from the image's caption"
  image_caption:
    key: "caption"
    metatype: "STRING"
    read_only: True
    doctype: "image"
    description: "The caption of the image, generated by an image captioning model"
  image_width:
    key: "width"
    metatype: "NUMBER"
    read_only: True
    doctype: "image"
    description: "The width of the image in pixels"
  image_height:
    key: "height"
    metatype: "NUMBER"
    read_only: True
    doctype: "image"
    description: "The height of the image in pixels"
  image_format:
    key: "format"
    metatype: "STRING"
    read_only: True
    doctype: "image"
    description: "The format of the image"
  image_mode:
    key: "mode"
    metatype: "STRING"
    read_only: True
    doctype: "image"
    description: "The mode of the image"

  audio_url:
    key: "url"
    metatype: "STRING"
    read_only: True
    doctype: "audio"
    description: "The URL of the audio file"
  audio_language:
    key: "language"
    metatype: "STRING"
    read_only: True
    doctype: "audio"
    description: "The language of the audio"
  audio_transcription_keywords:
    key: "transcription_keywords"
    metatype: "LIST"
    read_only: True
    doctype: "audio"
    description: "Keywords extracted from the transcript"
  audio_duration:
    key: "duration"
    metatype: "NUMBER"
    read_only: True
    doctype: "audio"
    description: "The duration of the audio file in seconds"
  audio_format_name:
    key: "format_name"
    metatype: "LIST"
    read_only: True
    doctype: "audio"
    description: "The format of the audio file"
  audio_format_long_name:
    key: "format_long_name"
    metatype: "STRING"
    read_only: True
    doctype: "audio"
    description: "The long format name of the audio file"
  audio_size:
    key: "size"
    metatype: "NUMBER"
    read_only: True
    doctype: "audio"
    description: "The size of the audio file in bytes"
  audio_bit_rate:
    key: "bit_rate"
    metatype: "NUMBER"
    read_only: True
    doctype: "audio"
    description: "The bit rate of the audio file in bits per second"
  audio_tags:
    key: "tags"
    metatype: "STRING"
    read_only: True
    doctype: "audio"
    description: "Tags extracted from the audio file"

  video_url:
    key: "url"
    metatype: "STRING"
    read_only: True
    doctype: "video"
    description: "The URL of the video file"
  video_language:
    key: "language"
    metatype: "STRING"
    read_only: True
    doctype: "video"
    description: "The language of the video"
  video_transcription_keywords:
    key: "transcription_keywords"
    metatype: "LIST"
    read_only: True
    doctype: "video"
    description: "Keywords extracted from the transcript"
  video_width:
    key: "width"
    metatype: "NUMBER"
    read_only: True
    doctype: "video"
    description: "The width of the video in pixels"
  video_height:
    key: "height"
    metatype: "NUMBER"
    read_only: True
    doctype: "video"
    description: "The height of the video in pixels"
  video_duration:
    key: "duration"
    metatype: "NUMBER"
    read_only: True
    doctype: "video"
    description: "The duration of the video file in seconds"
  video_format_name:
    key: "format_name"
    metatype: "LIST"
    read_only: True
    doctype: "video"
    description: "The format of the video file"
  video_format_long_name:
    key: "format_long_name"
    metatype: "STRING"
    read_only: True
    doctype: "video"
    description: "The long format name of the video file"
  video_size:
    key: "size"
    metatype: "NUMBER"
    read_only: True
    doctype: "video"
    description: "The size of the video file in bytes"
  video_bit_rate:
    key: "bit_rate"
    metatype: "NUMBER"
    read_only: True
    doctype: "video"
    description: "The bit rate of the video file in bits per second"
  video_tags:
    key: "tags"
    metatype: "STRING"
    read_only: True
    doctype: "video"
    description: "Tags extracted from the video file"

system_codes:
  SYSTEM_CODE:
    desc: "A system code"
    children:
      # text codes from spacy NER models (spans)
      NAMED_ENTITY:
        desc: "A named entity"
        children:
          CARDINAL:
            desc: "Numerals that do not fall under another type"
          DATE:
            desc: "Absolute or relative dates or periods"
          EVENT:
            desc: "Named hurricanes, battles, wars, sports events, etc."
          FAC:
            desc: "Buildings, airports, highways, bridges, etc."
          GPE:
            desc: "Countries, cities, states"
          LANGUAGE:
            desc: "Any named language"
          LAW:
            desc: "Named documents made into laws."
          LOC:
            desc: "Non-GPE locations, mountain ranges, bodies of water"
          MONEY:
            desc: "Monetary values, including unit"
          NORP:
            desc: "Nationalities or religious or political groups"
          ORDINAL:
            desc: "'first', 'second', etc."
          ORG:
            desc: "Companies, agencies, institutions, etc."
          PERCENT:
            desc: "Percentage, including '%'"
          PERSON:
            desc: "People, including fictional"
          PRODUCT:
            desc: "Objects, vehicles, foods, etc. (not services)"
          QUANTITY:
            desc: "Measurements, as of weight or distance"
          TIME:
            desc: "Times smaller than a day"
          WORK_OF_ART:
            desc: "Titles of books, songs, etc."
          MISC:
            desc: "Miscellaneous entities, e.g. events, nationalities, products or works of art"
      # image codes from COCO 2017 (bbox)
      ACCESSORY:
        desc: Super Object Category from COCO 2017
        children:
          BACKPACK:
            desc: Object Category from COCO 2017
          EYE GLASSES:
            desc: Object Category from COCO 2017
          HANDBAG:
            desc: Object Category from COCO 2017
          HAT:
            desc: Object Category from COCO 2017
          SHOE:
            desc: Object Category from COCO 2017
          SUITCASE:
            desc: Object Category from COCO 2017
          TIE:
            desc: Object Category from COCO 2017
          UMBRELLA:
            desc: Object Category from COCO 2017
      ANIMAL:
        desc: Super Object Category from COCO 2017
        children:
          BEAR:
            desc: Object Category from COCO 2017
          BIRD:
            desc: Object Category from COCO 2017
          CAT:
            desc: Object Category from COCO 2017
          COW:
            desc: Object Category from COCO 2017
          DOG:
            desc: Object Category from COCO 2017
          ELEPHANT:
            desc: Object Category from COCO 2017
          GIRAFFE:
            desc: Object Category from COCO 2017
          HORSE:
            desc: Object Category from COCO 2017
          SHEEP:
            desc: Object Category from COCO 2017
          ZEBRA:
            desc: Object Category from COCO 2017
      APPLIANCE:
        desc: Super Object Category from COCO 2017
        children:
          BLENDER:
            desc: Object Category from COCO 2017
          MICROWAVE:
            desc: Object Category from COCO 2017
          OVEN:
            desc: Object Category from COCO 2017
          REFRIGERATOR:
            desc: Object Category from COCO 2017
          SINK:
            desc: Object Category from COCO 2017
          TOASTER:
            desc: Object Category from COCO 2017
      BACKGROUND:
        desc: Super Object Category from COCO 2017
      ELECTRONIC:
        desc: Super Object Category from COCO 2017
        children:
          CELL PHONE:
            desc: Object Category from COCO 2017
          KEYBOARD:
            desc: Object Category from COCO 2017
          LAPTOP:
            desc: Object Category from COCO 2017
          MOUSE:
            desc: Object Category from COCO 2017
          REMOTE:
            desc: Object Category from COCO 2017
          TV:
            desc: Object Category from COCO 2017
      FOOD:
        desc: Super Object Category from COCO 2017
        children:
          APPLE:
            desc: Object Category from COCO 2017
          BANANA:
            desc: Object Category from COCO 2017
          BROCCOLI:
            desc: Object Category from COCO 2017
          CAKE:
            desc: Object Category from COCO 2017
          CARROT:
            desc: Object Category from COCO 2017
          DONUT:
            desc: Object Category from COCO 2017
          HOT DOG:
            desc: Object Category from COCO 2017
          ORANGE:
            desc: Object Category from COCO 2017
          PIZZA:
            desc: Object Category from COCO 2017
          SANDWICH:
            desc: Object Category from COCO 2017
      FURNITURE:
        desc: Super Object Category from COCO 2017
        children:
          BED:
            desc: Object Category from COCO 2017
          CHAIR:
            desc: Object Category from COCO 2017
          COUCH:
            desc: Object Category from COCO 2017
          DESK:
            desc: Object Category from COCO 2017
          DINING TABLE:
            desc: Object Category from COCO 2017
          DOOR:
            desc: Object Category from COCO 2017
          MIRROR:
            desc: Object Category from COCO 2017
          POTTED PLANT:
            desc: Object Category from COCO 2017
          TOILET:
            desc: Object Category from COCO 2017
          WINDOW:
            desc: Object Category from COCO 2017
      INDOOR:
        desc: Super Object Category from COCO 2017
        children:
          BOOK:
            desc: Object Category from COCO 2017
          CLOCK:
            desc: Object Category from COCO 2017
          HAIR BRUSH:
            desc: Object Category from COCO 2017
          HAIR DRIER:
            desc: Object Category from COCO 2017
          SCISSORS:
            desc: Object Category from COCO 2017
          TEDDY BEAR:
            desc: Object Category from COCO 2017
          TOOTHBRUSH:
            desc: Object Category from COCO 2017
          VASE:
            desc: Object Category from COCO 2017
      KITCHEN:
        desc: Super Object Category from COCO 2017
        children:
          BOTTLE:
            desc: Object Category from COCO 2017
          BOWL:
            desc: Object Category from COCO 2017
          CUP:
            desc: Object Category from COCO 2017
          FORK:
            desc: Object Category from COCO 2017
          KNIFE:
            desc: Object Category from COCO 2017
          PLATE:
            desc: Object Category from COCO 2017
          SPOON:
            desc: Object Category from COCO 2017
          WINE GLASS:
            desc: Object Category from COCO 2017
      OUTDOOR:
        desc: Super Object Category from COCO 2017
        children:
          BENCH:
            desc: Object Category from COCO 2017
          FIRE HYDRANT:
            desc: Object Category from COCO 2017
          PARKING METER:
            desc: Object Category from COCO 2017
          STOP SIGN:
            desc: Object Category from COCO 2017
          STREET SIGN:
            desc: Object Category from COCO 2017
          TRAFFIC LIGHT:
            desc: Object Category from COCO 2017
      SPORTS:
        desc: Super Object Category from COCO 2017
        children:
          BASEBALL BAT:
            desc: Object Category from COCO 2017
          BASEBALL GLOVE:
            desc: Object Category from COCO 2017
          FRISBEE:
            desc: Object Category from COCO 2017
          KITE:
            desc: Object Category from COCO 2017
          SKATEBOARD:
            desc: Object Category from COCO 2017
          SKIS:
            desc: Object Category from COCO 2017
          SNOWBOARD:
            desc: Object Category from COCO 2017
          SPORTS BALL:
            desc: Object Category from COCO 2017
          SURFBOARD:
            desc: Object Category from COCO 2017
          TENNIS RACKET:
            desc: Object Category from COCO 2017
      VEHICLE:
        desc: Super Object Category from COCO 2017
        children:
          AIRPLANE:
            desc: Object Category from COCO 2017
          BICYCLE:
            desc: Object Category from COCO 2017
          BOAT:
            desc: Object Category from COCO 2017
          BUS:
            desc: Object Category from COCO 2017
          CAR:
            desc: Object Category from COCO 2017
          MOTORCYCLE:
            desc: Object Category from COCO 2017
          TRAIN:
            desc: Object Category from COCO 2017
          TRUCK:
            desc: Object Category from COCO 2017
      QUOTATIONS:
        desc: Quotation parts
        children:
          QUOTE:
            desc: the quotation uttered by the Speaker
            children:
              DIRECT:
                desc: actual words of an utterance, usually in quotation marks
              INDIRECT:
                desc: content-wise equivalent utterance using different words, usually part of a sentence together with a Frame
              REPORTED:
                desc: report of a speech action, possibly far from the original quote, usually a full sentence, no Frame
              FREE_INDIRECT:
                desc: mix of article author & actual speaker, typically construct with "sollen" (shall) or "müssen" (must), full sentence
              INDIRECT_FREE_INDIRECT:
                desc: content-wise equivalent utterance written in conjunctive mood, full sentence
          SPEAKER:
            desc: entity in the text that utters the quotation
          CUE:
            desc: words that are part of a Frame and signal a Quote construction
          ADDRESSEE:
            desc: entity in the text that the quotation is directed at
          FRAME:
            desc: part of a sentence including Cue & Speaker, but not the quotation

keyword_extraction:
  max_ngram_size: 2
  deduplication_threshold: 0.5
  keyword_proposals: 20
