api:
  port: 5000

repository_root: /tmp/dwts

system_codes:
  NAMED_ENTITY:
    desc: "A named entity"
    children:
      CARDINAL:
        desc: "Numerals that do not fall under another type"
      DATE:
        desc: "Absolute or relative dates or periods"
      EVENT:
        desc: "Named hurricanes, battles, wars, sports events, etc."
      FAC:
        desc: "Buildings, airports, highways, bridges, etc."
      GPE:
        desc: "Countries, cities, states"
      LANGUAGE:
        desc: "Any named language"
      LAW:
        desc: "Named documents made into laws."
      LOC:
        desc: "Non-GPE locations, mountain ranges, bodies of water"
      MONEY:
        desc: "Monetary values, including unit"
      NORP:
        desc: "Nationalities or religious or political groups"
      ORDINAL:
        desc: "'first', 'second', etc."
      ORG:
        desc: "Companies, agencies, institutions, etc."
      PERCENT:
        desc: "Percentage, including '%'"
      PERSON:
        desc: "People, including fictional"
      PRODUCT:
        desc: "Objects, vehicles, foods, etc. (not services)"
      QUANTITY:
        desc: "Measurements, as of weight or distance"
      TIME:
        desc: "Times smaller than a day"
      WORK_OF_ART:
        desc: "Titles of books, songs, etc."
  SENTENCE:
    desc: "A sentence spanning multiple Tokens."

docprepro:
  spacy:
    default_model: "en_core_web_trf"
    english_model: "en_core_web_trf"
    german_model: "de_core_news_lg"
  celery:
    backend:
      host: ${oc.env:CELERY_BACKEND_HOST, localhost}
      port: ${oc.env:CELERY_BACKEND_PORT, 6379}
      db: 0
      password: ${oc.env:CELERY_BACKEND_PASSWORD, dwts123}
    broker:
      host: ${oc.env:CELERY_BROKER_HOST, localhost}
      port: ${oc.env:CELERY_BROKER_PORT, 5672}
      user: ${oc.env:CELERY_BROKER_USER, dwtsuser}
      password: ${oc.env:CELERY_BROKER_PASSWORD, dwts123}


postgres:
  host: ${oc.env:DB_HOST, 127.0.0.1}
  port: ${oc.env:DB_PORT, 5432}
  db: ${oc.env:DB, dwts}
  user: ${oc.env:DB_USER, dwtsuser}
  password: ${oc.env:DB_PASSWORD, dwts123}

logging:
  max_file_size: 500 # MB
  level: DEBUG

elasticsearch:
  host: ${oc.env:ES_HOST, 127.0.0.1}
  port: ${oc.env:ES_PORT, 10194}
  use_ssl: False
  verify_certs: False
  sniff_on_start: False
  sniff_on_connection_fail: False
  sniffer_timeout: 120
  index_mappings:
    docs: configs/default_doc_index_mapping.json
    memos: configs/default_memo_index_mapping.json
  index_settings:
    docs:
    memos: