api:
  port: 5000

postgres:
  host: ${oc.env:DB_HOST, 127.0.0.1}
  port: ${oc.env:DB_PORT, 5432}
  db: ${oc.env:DB, dwts}
  user: ${oc.env:DB_USER, root}
  password: ${oc.env:DB_PASSWORD, rootpwd}

logging:
  path: /tmp/dwts_backend_logs
  max_file_size: 500 # MB
  level: DEBUG

elasticsearch:
  host: ${oc.env:ES_HOST, 127.0.0.1}
  port: ${oc.env:ES_PORT, 10194}
  use_ssl: False
  verify_certs: False
  sniff_on_start: False
  sniff_on_connection_fail: False
  sniffer_timeout: 120
  index_mappings:
    docs: configs/default_doc_index_mapping.json
    memos: configs/default_memo_index_mapping.json
  index_settings:
    docs:
    memos: