version: "3.3"

services:
  ray-whisper-compose-test:
    image: ray:WContainer
    command: /entry/entrypoint.sh
    # user: 60171:600
    volumes:
      - ./:/entry
    ports:
      - "${API_PORT:-8000}:8000"
      - "${DASHBOARD_PORT:-8265}:8265"
    networks:
      - ray_network
    shm_size: 10.24gb
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]

networks:
  ray_network: