services:
  elasticsearch:
    environment:
      - xpack.security.enabled=false # no auth
      - discovery.type=single-node # single node cluster
      - ES_JAVA_OPTS=-Xms8g -Xmx8g

  ray:
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ["0"] # use first gpu for production
              capabilities: [gpu]
