version: "3.3"

services:
  postgres:
    image: "postgres:15-alpine"
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-dwtsuser}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-dwts123}
    ports:
      - "${POSTGRES_EXPOSED:-5432}:5432"
    volumes:
      - "postgres_data_demo:/var/lib/postgresql/data"
    networks:
      - dwts_demo_network

  rabbitmq:
    image: "rabbitmq:3-management-alpine"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER:-dwtsuser}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD:-dwts123}
    ports:
      - "${RABBIT_EXPOSED:-5672}:5672"
    volumes:
      - "rabbitmq_data_demo:/var/lib/rabbitmq/data"
    networks:
      - dwts_demo_network

  redis:
    image: "redis:7-alpine"
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD:-dwts123}
    ports:
      - "${REDIS_EXPOSED:-6379}:6379"
    volumes:
      - "redis_data_demo:/var/lib/redis/data"
    command: redis-server --requirepass "${REDIS_PASSWORD:-dwts123}" --save 60 1
    networks:
      - dwts_demo_network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.3
    environment:
      # see https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-network.html
      # use 127.0.0.1 to access the ES node from OUTSIDE of the docker network (e.g. when ssh tunneling to ltdocker)
      # network.publish_host=127.0.0.1
      # http.publish_port=${ELASTICSEARCH_EXPOSED_PORT:-9200}
      - xpack.security.enabled=false # no auth
      - discovery.type=single-node # single node cluster
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - elasticsearch_data_demo:/usr/share/elasticsearch/data
    ports:
      - "${ELASTICSEARCH_EXPOSED:-9200}:9200"
    networks:
      - dwts_demo_network

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.3
    ports:
      - "${KIBANA_EXPOSED:-5601}:5601"
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
      ELASTICSEARCH_HOSTS: '["http://elasticsearch:9200"]'
    networks:
      - dwts_demo_network
    depends_on:
      - elasticsearch

  lighttpd:
    image: sebp/lighttpd
    volumes:
      - ./backend_repo:/var/www/localhost/htdocs
    ports:
      - "${CONTENT_SERVER_EXPOSED:-12345}:80"
    tty: true
    networks:
      - dwts_demo_network

  celery-text-worker:
    image: uhhlt/dwts_backend:${DWTS_BACKEND_DOCKER_VERSION:-debian_dev_latest}
    command: /dwts_code/src/celery_text_worker_entrypoint.sh
    user: ${UID:-1000}:${GID:-1000}
    environment:
      REDIS_HOST: ${REDIS_HOST:-redis}
      REDIS_PORT: ${REDIS_PORT:-6379}
      REDIS_PASSWORD: ${REDIS_PASSWORD:-dwts123}
      RABBITMQ_HOST: ${RABBITMQ_HOST:-rabbitmq}
      RABBITMQ_PORT: ${RABBITMQ_PORT:-5672}
      RABBITMQ_USER: ${RABBITMQ_USER:-dwtsuser}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD:-dwts123}
      POSTGRES_HOST: ${POSTGRES_HOST:-postgres}
      POSTGRES_PORT: ${POSTGRES_PORT:-5432}
      POSTGRES_DB: ${POSTGRES_DB:-dwts}
      POSTGRES_USER: ${POSTGRES_USER:-dwtsuser}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-dwts123}
      ES_HOST: ${ES_HOST:-elasticsearch}
      ES_PORT: ${ES_PORT:-9200}
      ES_MIN_HEALTH: ${ES_MIN_HEALTH:-75}
      LOG_LEVEL: ${LOG_LEVEL:-info}
      INSTALL_JUPYTER: ${INSTALL_JUPYTER:-false}
      API_PORT: ${API_PORT:-5500}
      CELERY_TEXT_WORKER_CONCURRENCY: ${CELERY_TEXT_WORKER_CONCURRENCY:-1}
      DWISE_BACKEND_CONFIG: ${DWISE_BACKEND_CONFIG:-/dwts_code/src/configs/default.yaml}
      HUGGINGFACE_HUB_CACHE: /models_cache
      TRANSFORMERS_CACHE: /models_cache
      TORCH_HOME: /models_cache
    volumes:
      - ../backend/src:/dwts_code/src
      - ./backend_repo:/tmp/dwts
      - ./spacy_models:/spacy_models
      - ./models_cache:/models_cache
      - ./tika:/tika
    depends_on:
      - rabbitmq
      - redis
      - postgres
    ports:
      - "${JUPYTER_TEXT_EXPOSED:-8889}:8888"
    restart: always
    links:
      - postgres
      - redis
      - rabbitmq
      - elasticsearch
    networks:
      - dwts_demo_network
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]

  celery-image-worker:
    image: uhhlt/dwts_backend:${DWTS_BACKEND_DOCKER_VERSION:-debian_dev_latest}
    command: /dwts_code/src/celery_image_worker_entrypoint.sh
    user: ${UID:-1000}:${GID:-1000}
    environment:
      REDIS_HOST: ${REDIS_HOST:-redis}
      REDIS_PORT: ${REDIS_PORT:-6379}
      REDIS_PASSWORD: ${REDIS_PASSWORD:-dwts123}
      RABBITMQ_HOST: ${RABBITMQ_HOST:-rabbitmq}
      RABBITMQ_PORT: ${RABBITMQ_PORT:-5672}
      RABBITMQ_USER: ${RABBITMQ_USER:-dwtsuser}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD:-dwts123}
      POSTGRES_HOST: ${POSTGRES_HOST:-postgres}
      POSTGRES_PORT: ${POSTGRES_PORT:-5432}
      POSTGRES_DB: ${POSTGRES_DB:-dwts}
      POSTGRES_USER: ${POSTGRES_USER:-dwtsuser}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-dwts123}
      ES_HOST: ${ES_HOST:-elasticsearch}
      ES_PORT: ${ES_PORT:-9200}
      ES_MIN_HEALTH: ${ES_MIN_HEALTH:-75}
      LOG_LEVEL: ${LOG_LEVEL:-info}
      INSTALL_JUPYTER: ${INSTALL_JUPYTER:-false}
      API_PORT: ${API_PORT:-5500}
      CELERY_IMAGE_WORKER_CONCURRENCY: ${CELERY_IMAGE_WORKER_CONCURRENCY:-1}
      DWISE_BACKEND_CONFIG: ${DWISE_BACKEND_CONFIG:-/dwts_code/src/configs/default.yaml}
      HUGGINGFACE_HUB_CACHE: /models_cache
      TRANSFORMERS_CACHE: /models_cache
      TORCH_HOME: /models_cache
    volumes:
      - ../backend/src:/dwts_code/src
      - ./backend_repo:/tmp/dwts
      - ./models_cache:/models_cache
    depends_on:
      - rabbitmq
      - redis
      - postgres
    ports:
      - "${JUPYTER_IMAGE_EXPOSED:-8880}:8888"
    restart: always
    links:
      - postgres
      - redis
      - rabbitmq
    networks:
      - dwts_demo_network
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]

  celery-audio-worker:
    image: uhhlt/dwts_backend:${DWTS_BACKEND_DOCKER_VERSION:-debian_dev_latest}
    command: /dwts_code/src/celery_audio_worker_entrypoint.sh
    user: ${UID:-1000}:${GID:-1000}
    environment:
      REDIS_HOST: ${REDIS_HOST:-redis}
      REDIS_PORT: ${REDIS_PORT:-6379}
      REDIS_PASSWORD: ${REDIS_PASSWORD:-dwts123}
      RABBITMQ_HOST: ${RABBITMQ_HOST:-rabbitmq}
      RABBITMQ_PORT: ${RABBITMQ_PORT:-5672}
      RABBITMQ_USER: ${RABBITMQ_USER:-dwtsuser}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD:-dwts123}
      POSTGRES_HOST: ${POSTGRES_HOST:-postgres}
      POSTGRES_PORT: ${POSTGRES_PORT:-5432}
      POSTGRES_DB: ${POSTGRES_DB:-dwts}
      POSTGRES_USER: ${POSTGRES_USER:-dwtsuser}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-dwts123}
      ES_HOST: ${ES_HOST:-elasticsearch}
      ES_PORT: ${ES_PORT:-9200}
      ES_MIN_HEALTH: ${ES_MIN_HEALTH:-75}
      LOG_LEVEL: ${LOG_LEVEL:-info}
      INSTALL_JUPYTER: ${INSTALL_JUPYTER:-false}
      API_PORT: ${API_PORT:-5500}
      CELERY_AUDIO_WORKER_CONCURRENCY: ${CELERY_AUDIO_WORKER_CONCURRENCY:-1}
      DWISE_BACKEND_CONFIG: ${DWISE_BACKEND_CONFIG:-/dwts_code/src/configs/default.yaml}
      HUGGINGFACE_HUB_CACHE: /models_cache
      TRANSFORMERS_CACHE: /models_cache
      TORCH_HOME: /models_cache
    volumes:
      - ../backend/src:/dwts_code/src
      - ./backend_repo:/tmp/dwts
      - ./models_cache:/models_cache
    depends_on:
      - rabbitmq
      - redis
      - postgres
    ports:
      - "${JUPYTER_AUDIO_EXPOSED:-8880}:8888"
    restart: always
    links:
      - postgres
      - redis
      - rabbitmq
    networks:
      - dwts_demo_network
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]

  celery-video-worker:
    image: uhhlt/dwts_backend:${DWTS_BACKEND_DOCKER_VERSION:-debian_dev_latest}
    command: /dwts_code/src/celery_video_worker_entrypoint.sh
    user: ${UID:-1000}:${GID:-1000}
    environment:
      REDIS_HOST: ${REDIS_HOST:-redis}
      REDIS_PORT: ${REDIS_PORT:-6379}
      REDIS_PASSWORD: ${REDIS_PASSWORD:-dwts123}
      RABBITMQ_HOST: ${RABBITMQ_HOST:-rabbitmq}
      RABBITMQ_PORT: ${RABBITMQ_PORT:-5672}
      RABBITMQ_USER: ${RABBITMQ_USER:-dwtsuser}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD:-dwts123}
      POSTGRES_HOST: ${POSTGRES_HOST:-postgres}
      POSTGRES_PORT: ${POSTGRES_PORT:-5432}
      POSTGRES_DB: ${POSTGRES_DB:-dwts}
      POSTGRES_USER: ${POSTGRES_USER:-dwtsuser}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-dwts123}
      ES_HOST: ${ES_HOST:-elasticsearch}
      ES_PORT: ${ES_PORT:-9200}
      ES_MIN_HEALTH: ${ES_MIN_HEALTH:-75}
      LOG_LEVEL: ${LOG_LEVEL:-info}
      INSTALL_JUPYTER: ${INSTALL_JUPYTER:-false}
      API_PORT: ${API_PORT:-5500}
      CELERY_VIDEO_WORKER_CONCURRENCY: ${CELERY_VIDEO_WORKER_CONCURRENCY:-1}
      DWISE_BACKEND_CONFIG: ${DWISE_BACKEND_CONFIG:-/dwts_code/src/configs/default.yaml}
      HUGGINGFACE_HUB_CACHE: /models_cache
      TRANSFORMERS_CACHE: /models_cache
      TORCH_HOME: /models_cache
    volumes:
      - ../backend/src:/dwts_code/src
      - ./backend_repo:/tmp/dwts
      - ./models_cache:/models_cache
    depends_on:
      - rabbitmq
      - redis
      - postgres
    ports:
      - "${JUPYTER_VIDEO_EXPOSED:-8880}:8888"
    restart: always
    links:
      - postgres
      - redis
      - rabbitmq
    networks:
      - dwts_demo_network
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]

  celery-background-jobs-worker:
    image: uhhlt/dwts_backend:${DWTS_BACKEND_DOCKER_VERSION:-debian_dev_latest}
    command: /dwts_code/src/celery_background_jobs_worker_entrypoint.sh
    user: ${UID:-1000}:${GID:-1000}
    environment:
      REDIS_HOST: ${REDIS_HOST:-redis}
      REDIS_PORT: ${REDIS_PORT:-6379}
      REDIS_PASSWORD: ${REDIS_PASSWORD:-dwts123}
      RABBITMQ_HOST: ${RABBITMQ_HOST:-rabbitmq}
      RABBITMQ_PORT: ${RABBITMQ_PORT:-5672}
      RABBITMQ_USER: ${RABBITMQ_USER:-dwtsuser}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD:-dwts123}
      POSTGRES_HOST: ${POSTGRES_HOST:-postgres}
      POSTGRES_PORT: ${POSTGRES_PORT:-5432}
      POSTGRES_DB: ${POSTGRES_DB:-dwts}
      POSTGRES_USER: ${POSTGRES_USER:-dwtsuser}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-dwts123}
      ES_HOST: ${ES_HOST:-elasticsearch}
      ES_PORT: ${ES_PORT:-9200}
      ES_MIN_HEALTH: ${ES_MIN_HEALTH:-75}
      LOG_LEVEL: ${LOG_LEVEL:-info}
      INSTALL_JUPYTER: ${INSTALL_JUPYTER:-false}
      API_PORT: ${API_PORT:-5500}
      CELERY_BACKGROUND_JOBS_WORKER_CONCURRENCY: ${CELERY_BACKGROUND_JOBS_WORKER_CONCURRENCY:-1}
      CELERY_DEBUG_MODE: ${CELERY_DEBUG_MODE:-0}
      DWISE_BACKEND_CONFIG: ${DWISE_BACKEND_CONFIG:-/dwts_code/src/configs/default.yaml}
      HUGGINGFACE_HUB_CACHE: /models_cache
      TRANSFORMERS_CACHE: /models_cache
      TORCH_HOME: /models_cache
    volumes:
      - ../backend/src:/dwts_code/src
      - ./backend_repo:/tmp/dwts
      - ./models_cache:/models_cache
      - ./tika:/tika
    depends_on:
      - rabbitmq
      - redis
      - postgres
    ports:
      - "${JUPYTER_BACKGROUND_JOBS_EXPOSED:-8880}:8888"
    restart: always
    links:
      - postgres
      - redis
      - rabbitmq
    networks:
      - dwts_demo_network
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]

  celery-simsearch-worker:
    image: uhhlt/dwts_backend:${DWTS_BACKEND_DOCKER_VERSION:-debian_dev_latest}
    command: /dwts_code/src/celery_simsearch_worker_entrypoint.sh
    user: ${UID:-1000}:${GID:-1000}
    environment:
      REDIS_HOST: ${REDIS_HOST:-redis}
      REDIS_PORT: ${REDIS_PORT:-6379}
      REDIS_PASSWORD: ${REDIS_PASSWORD:-dwts123}
      RABBITMQ_HOST: ${RABBITMQ_HOST:-rabbitmq}
      RABBITMQ_PORT: ${RABBITMQ_PORT:-5672}
      RABBITMQ_USER: ${RABBITMQ_USER:-dwtsuser}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD:-dwts123}
      POSTGRES_HOST: ${POSTGRES_HOST:-postgres}
      POSTGRES_PORT: ${POSTGRES_PORT:-5432}
      POSTGRES_DB: ${POSTGRES_DB:-dwts}
      POSTGRES_USER: ${POSTGRES_USER:-dwtsuser}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-dwts123}
      ES_HOST: ${ES_HOST:-elasticsearch}
      ES_PORT: ${ES_PORT:-9200}
      ES_MIN_HEALTH: ${ES_MIN_HEALTH:-75}
      LOG_LEVEL: ${LOG_LEVEL:-info}
      INSTALL_JUPYTER: ${INSTALL_JUPYTER:-false}
      API_PORT: ${API_PORT:-5500}
      CELERY_SIMSEARCH_WORKER_CONCURRENCY: ${CELERY_SIMSEARCH_WORKER_CONCURRENCY:-1}
      DWISE_BACKEND_CONFIG: ${DWISE_BACKEND_CONFIG:-/dwts_code/src/configs/default.yaml}
      HUGGINGFACE_HUB_CACHE: /models_cache
      TRANSFORMERS_CACHE: /models_cache
      TORCH_HOME: /models_cache
    volumes:
      - ../backend/src:/dwts_code/src
      - ./backend_repo:/tmp/dwts
      - ./models_cache:/models_cache
    depends_on:
      - rabbitmq
      - redis
      - postgres
    ports:
      - "${JUPYTER_SIMSEARCH_EXPOSED:-8880}:8888"
    restart: always
    links:
      - postgres
      - redis
      - rabbitmq
    networks:
      - dwts_demo_network
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]

  dwts-backend-api:
    image: uhhlt/dwts_backend:${DWTS_BACKEND_DOCKER_VERSION:-debian_dev_latest}
    command: /dwts_code/src/backend_api_entrypoint.sh
    user: ${UID:-1000}:${GID:-1000}
    environment:
      REDIS_HOST: ${REDIS_HOST:-redis}
      REDIS_PORT: ${REDIS_PORT:-6379}
      REDIS_PASSWORD: ${REDIS_PASSWORD:-dwts123}
      RABBITMQ_HOST: ${RABBITMQ_HOST:-rabbitmq}
      RABBITMQ_PORT: ${RABBITMQ_PORT:-5672}
      RABBITMQ_USER: ${RABBITMQ_USER:-dwtsuser}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD:-dwts123}
      POSTGRES_HOST: ${POSTGRES_HOST:-postgres}
      POSTGRES_PORT: ${POSTGRES_PORT:-5432}
      POSTGRES_DB: ${POSTGRES_DB:-dwts}
      POSTGRES_USER: ${POSTGRES_USER:-dwtsuser}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-dwts123}
      ES_HOST: ${ES_HOST:-elasticsearch}
      ES_PORT: ${ES_PORT:-9200}
      ES_MIN_HEALTH: ${ES_MIN_HEALTH:-75}
      LOG_LEVEL: ${LOG_LEVEL:-info}
      INSTALL_JUPYTER: ${INSTALL_JUPYTER:-false}
      API_PORT: ${API_PORT:-5500}
      CONTENT_SERVER_EXPOSED: ${CONTENT_SERVER_EXPOSED:-12345}
      JWT_TTL: ${JWT_TTL:-10080} # 10080 secs == 1 week
      JWT_SECRET: ${JWT_SECRET:-""}
      DWISE_BACKEND_CONFIG: ${DWISE_BACKEND_CONFIG:-/dwts_code/src/configs/default.yaml}
      API_PRODUCTION_MODE: ${API_PRODUCTION_MODE:-0}
      API_PRODUCTION_WORKERS: ${API_PRODUCTION_WORKERS:-10}
      HUGGINGFACE_HUB_CACHE: /models_cache
      TRANSFORMERS_CACHE: /models_cache
      TORCH_HOME: /models_cache
    volumes:
      - ../backend/src:/dwts_code/src
      - ./backend_repo:/tmp/dwts
      - ./models_cache:/models_cache
    depends_on:
      - elasticsearch
      - lighttpd
      - postgres
      - rabbitmq
      - redis
      - celery-text-worker
      - celery-image-worker
    ports:
      - "${API_EXPOSED:-5500}:${API_PORT}"
      - "${JUPYTER_API_EXPOSED:-8888}:8888"
    restart: always
    links:
      - postgres
      - redis
      - rabbitmq
      - celery-text-worker
      - celery-image-worker
      - celery-background-jobs-worker
      - elasticsearch
    networks:
      - dwts_demo_network

  dwts-frontend:
    image: uhhlt/dwts_frontend:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - dwts-backend-api
    ports:
      - "${FRONTEND_EXPOSED:-3000}:3000"
    networks:
      - dwts_demo_network

volumes:
  rabbitmq_data_demo:
    driver: local
  redis_data_demo:
    driver: local
  postgres_data_demo:
    driver: local
  elasticsearch_data_demo:
    driver: local

networks:
  dwts_demo_network:
