/* generated using openapi-typescript-codegen -- do not edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
export enum ExportJobType {
  ALL_DATA = "ALL_DATA",
  ALL_USERS = "ALL_USERS",
  ALL_SDOCS = "ALL_SDOCS",
  ALL_CODES = "ALL_CODES",
  ALL_TAGS = "ALL_TAGS",
  ALL_FOLDERS = "ALL_FOLDERS",
  ALL_SPAN_ANNOTATIONS = "ALL_SPAN_ANNOTATIONS",
  ALL_SENTENCE_ANNOTATIONS = "ALL_SENTENCE_ANNOTATIONS",
  ALL_BBOX_ANNOTATIONS = "ALL_BBOX_ANNOTATIONS",
  ALL_MEMOS = "ALL_MEMOS",
  ALL_PROJECT_METADATA = "ALL_PROJECT_METADATA",
  ALL_WHITEBOARDS = "ALL_WHITEBOARDS",
  ALL_TIMELINE_ANALYSES = "ALL_TIMELINE_ANALYSES",
  ALL_COTA = "ALL_COTA",
  SELECTED_SDOCS = "SELECTED_SDOCS",
  SELECTED_SPAN_ANNOTATIONS = "SELECTED_SPAN_ANNOTATIONS",
  SELECTED_SENTENCE_ANNOTATIONS = "SELECTED_SENTENCE_ANNOTATIONS",
  SELECTED_BBOX_ANNOTATIONS = "SELECTED_BBOX_ANNOTATIONS",
  SELECTED_MEMOS = "SELECTED_MEMOS",
  SELECTED_WHITEBOARDS = "SELECTED_WHITEBOARDS",
  SELECTED_TIMELINE_ANALYSES = "SELECTED_TIMELINE_ANALYSES",
  SELECTED_COTA = "SELECTED_COTA",
}
