/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */

export enum AnnotatedSegmentsColumns {
  ASC_SOURCE_SOURCE_DOCUMENT_FILENAME = "ASC_SOURCE_SOURCE_DOCUMENT_FILENAME",
  ASC_DOCUMENT_DOCUMENT_TAG_ID_LIST = "ASC_DOCUMENT_DOCUMENT_TAG_ID_LIST",
  ASC_CODE_ID = "ASC_CODE_ID",
  ASC_SPAN_TEXT = "ASC_SPAN_TEXT",
  ASC_MEMO_CONTENT = "ASC_MEMO_CONTENT",
}
