/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */

/**
 * An enumeration.
 */
export enum DBColumns {
  SPAN_TEXT = "SPAN_TEXT",
  SOURCE_DOCUMENT_ID = "SOURCE_DOCUMENT_ID",
  SOURCE_DOCUMENT_FILENAME = "SOURCE_DOCUMENT_FILENAME",
  METADATA = "METADATA",
  CODE_ID = "CODE_ID",
  CODE_ID_LIST = "CODE_ID_LIST",
  CODE_NAME = "CODE_NAME",
  DOCUMENT_TAG_ID = "DOCUMENT_TAG_ID",
  DOCUMENT_TAG_ID_LIST = "DOCUMENT_TAG_ID_LIST",
  DOCUMENT_TAG_TITLE = "DOCUMENT_TAG_TITLE",
  MEMO_ID = "MEMO_ID",
  MEMO_CONTENT = "MEMO_CONTENT",
  MEMO_TITLE = "MEMO_TITLE",
  USER_ID = "USER_ID",
  USER_ID_LIST = "USER_ID_LIST",
  SPAN_ANNOTATION_ID = "SPAN_ANNOTATION_ID",
  SPAN_ANNOTATION_ID_LIST = "SPAN_ANNOTATION_ID_LIST",
}
