/* generated using openapi-typescript-codegen -- do not edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
export enum ExportJobType {
  SINGLE_PROJECT_ALL_DATA = "SINGLE_PROJECT_ALL_DATA",
  SINGLE_PROJECT_ALL_TAGS = "SINGLE_PROJECT_ALL_TAGS",
  SINGLE_PROJECT_ALL_CODES = "SINGLE_PROJECT_ALL_CODES",
  SINGLE_PROJECT_SELECTED_SDOCS = "SINGLE_PROJECT_SELECTED_SDOCS",
  SINGLE_PROJECT_SELECTED_SPAN_ANNOTATIONS = "SINGLE_PROJECT_SELECTED_SPAN_ANNOTATIONS",
  SINGLE_USER_ALL_DATA = "SINGLE_USER_ALL_DATA",
  SINGLE_USER_ALL_MEMOS = "SINGLE_USER_ALL_MEMOS",
  SINGLE_USER_LOGBOOK = "SINGLE_USER_LOGBOOK",
  SINGLE_DOC_ALL_USER_ANNOTATIONS = "SINGLE_DOC_ALL_USER_ANNOTATIONS",
  SINGLE_DOC_SINGLE_USER_ANNOTATIONS = "SINGLE_DOC_SINGLE_USER_ANNOTATIONS",
}
