/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */

/**
 * An enumeration.
 */
export enum ExportJobType {
  SINGLE_PROJECT_ALL_DATA = "SINGLE_PROJECT_ALL_DATA",
  SINGLE_PROJECT_ALL_TAGS = "SINGLE_PROJECT_ALL_TAGS",
  SINGLE_USER_ALL_DATA = "SINGLE_USER_ALL_DATA",
  SINGLE_USER_ALL_CODES = "SINGLE_USER_ALL_CODES",
  SINGLE_USER_ALL_MEMOS = "SINGLE_USER_ALL_MEMOS",
  SINGLE_USER_LOGBOOK = "SINGLE_USER_LOGBOOK",
  SINGLE_DOC_ALL_USER_ANNOTATIONS = "SINGLE_DOC_ALL_USER_ANNOTATIONS",
  SINGLE_DOC_SINGLE_USER_ANNOTATIONS = "SINGLE_DOC_SINGLE_USER_ANNOTATIONS",
}
