/* generated using openapi-typescript-codegen -- do no edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
export enum ImportJobType {
  SINGLE_PROJECT_ALL_DATA = "SINGLE_PROJECT_ALL_DATA",
  SINGLE_PROJECT_ALL_USER = "SINGLE_PROJECT_ALL_USER",
  SINGLE_PROJECT_ALL_TAGS = "SINGLE_PROJECT_ALL_TAGS",
  SINGLE_PROJECT_SELECTED_SDOCS = "SINGLE_PROJECT_SELECTED_SDOCS",
  SINGLE_USER_ALL_DATA = "SINGLE_USER_ALL_DATA",
  SINGLE_PROJECT_ALL_METADATA = "SINGLE_PROJECT_ALL_METADATA",
  SINGLE_PROJECT_ALL_PROJECT_PROJECT_METADATA = "SINGLE_PROJECT_ALL_PROJECT_PROJECT_METADATA",
  SINGLE_PROJECT = "SINGLE_PROJECT",
  SINGLE_USER_ALL_CODES = "SINGLE_USER_ALL_CODES",
  SINGLE_USER_ALL_MEMOS = "SINGLE_USER_ALL_MEMOS",
  SINGLE_USER_LOGBOOK = "SINGLE_USER_LOGBOOK",
  SINGLE_DOC_ALL_USER_ANNOTATIONS = "SINGLE_DOC_ALL_USER_ANNOTATIONS",
  SINGLE_DOC_SINGLE_USER_ANNOTATIONS = "SINGLE_DOC_SINGLE_USER_ANNOTATIONS",
}
