/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */

export enum SearchColumns {
  SC_SOURCE_DOCUMENT_FILENAME = "SC_SOURCE_DOCUMENT_FILENAME",
  SC_SOURCE_DOCUMENT_TYPE = "SC_SOURCE_DOCUMENT_TYPE",
  SC_DOCUMENT_TAG_ID_LIST = "SC_DOCUMENT_TAG_ID_LIST",
  SC_CODE_ID_LIST = "SC_CODE_ID_LIST",
  SC_USER_ID_LIST = "SC_USER_ID_LIST",
  SC_SPAN_ANNOTATIONS = "SC_SPAN_ANNOTATIONS",
}
