/* generated using openapi-typescript-codegen -- do not edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
export enum WordFrequencyColumns {
  WF_WORD = "WF_WORD",
  WF_WORD_FREQUENCY = "WF_WORD_FREQUENCY",
  WF_WORD_PERCENT = "WF_WORD_PERCENT",
  WF_SOURCE_DOCUMENT_FREQUENCY = "WF_SOURCE_DOCUMENT_FREQUENCY",
  WF_SOURCE_DOCUMENT_PERCENT = "WF_SOURCE_DOCUMENT_PERCENT",
  WF_SOURCE_DOCUMENT_NAME = "WF_SOURCE_DOCUMENT_NAME",
  WF_TAG_ID_LIST = "WF_TAG_ID_LIST",
  WF_CODE_ID_LIST = "WF_CODE_ID_LIST",
  WF_USER_ID_LIST = "WF_USER_ID_LIST",
  WF_SPAN_ANNOTATIONS = "WF_SPAN_ANNOTATIONS",
}
