/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as PublicRouteImport } from "./routes/_public";
import { Route as AuthRouteImport } from "./routes/_auth";
import { Route as PublicIndexRouteImport } from "./routes/_public/index";
import { Route as PublicRegisterRouteImport } from "./routes/_public/register";
import { Route as PublicLoginRouteImport } from "./routes/_public/login";
import { Route as AuthProjectsRouteImport } from "./routes/_auth/projects";
import { Route as AuthMeRouteImport } from "./routes/_auth/me";
import { Route as AuthProjectProjectIdRouteRouteImport } from "./routes/_auth/project/$projectId/route";
import { Route as AuthProjectProjectIdSentencesearchRouteImport } from "./routes/_auth/project/$projectId/sentencesearch";
import { Route as AuthProjectProjectIdSearchRouteImport } from "./routes/_auth/project/$projectId/search";
import { Route as AuthProjectProjectIdLogbookRouteImport } from "./routes/_auth/project/$projectId/logbook";
import { Route as AuthProjectProjectIdImagesearchRouteImport } from "./routes/_auth/project/$projectId/imagesearch";
import { Route as AuthProjectProjectIdClassifierRouteImport } from "./routes/_auth/project/$projectId/classifier";
import { Route as AuthProjectProjectIdWhiteboardIndexRouteImport } from "./routes/_auth/project/$projectId/whiteboard/index";
import { Route as AuthProjectProjectIdPerspectivesIndexRouteImport } from "./routes/_auth/project/$projectId/perspectives/index";
import { Route as AuthProjectProjectIdAnnotationIndexRouteImport } from "./routes/_auth/project/$projectId/annotation/index";
import { Route as AuthProjectProjectIdAnalysisIndexRouteImport } from "./routes/_auth/project/$projectId/analysis/index";
import { Route as AuthProjectProjectIdWhiteboardWhiteboardIdRouteImport } from "./routes/_auth/project/$projectId/whiteboard/$whiteboardId";
import { Route as AuthProjectProjectIdToolsMlAutomationRouteImport } from "./routes/_auth/project/$projectId/tools/ml-automation";
import { Route as AuthProjectProjectIdToolsHealthRouteImport } from "./routes/_auth/project/$projectId/tools/health";
import { Route as AuthProjectProjectIdToolsDuplicateFinderRouteImport } from "./routes/_auth/project/$projectId/tools/duplicate-finder";
import { Route as AuthProjectProjectIdToolsDocumentSamplerRouteImport } from "./routes/_auth/project/$projectId/tools/document-sampler";
import { Route as AuthProjectProjectIdAnnotationSdocIdRouteImport } from "./routes/_auth/project/$projectId/annotation/$sdocId";
import { Route as AuthProjectProjectIdAnalysisWordFrequencyRouteImport } from "./routes/_auth/project/$projectId/analysis/word-frequency";
import { Route as AuthProjectProjectIdAnalysisTagRecommendationsRouteImport } from "./routes/_auth/project/$projectId/analysis/tag-recommendations";
import { Route as AuthProjectProjectIdAnalysisSpanAnnotationsRouteImport } from "./routes/_auth/project/$projectId/analysis/span-annotations";
import { Route as AuthProjectProjectIdAnalysisSentenceAnnotationsRouteImport } from "./routes/_auth/project/$projectId/analysis/sentence-annotations";
import { Route as AuthProjectProjectIdAnalysisCodeFrequencyRouteImport } from "./routes/_auth/project/$projectId/analysis/code-frequency";
import { Route as AuthProjectProjectIdAnalysisBboxAnnotationsRouteImport } from "./routes/_auth/project/$projectId/analysis/bbox-annotations";
import { Route as AuthProjectProjectIdAnalysisAnnotationScalingRouteImport } from "./routes/_auth/project/$projectId/analysis/annotation-scaling";
import { Route as AuthProjectProjectIdPerspectivesAspectIdRouteRouteImport } from "./routes/_auth/project/$projectId/perspectives/$aspectId/route";
import { Route as AuthProjectProjectIdPerspectivesAspectIdIndexRouteImport } from "./routes/_auth/project/$projectId/perspectives/$aspectId/index";
import { Route as AuthProjectProjectIdAnalysisTimelineIndexRouteImport } from "./routes/_auth/project/$projectId/analysis/timeline/index";
import { Route as AuthProjectProjectIdAnalysisConceptsOverTimeAnalysisIndexRouteImport } from "./routes/_auth/project/$projectId/analysis/concepts-over-time-analysis/index";
import { Route as AuthProjectProjectIdPerspectivesAspectIdMapRouteImport } from "./routes/_auth/project/$projectId/perspectives/$aspectId/map";
import { Route as AuthProjectProjectIdAnalysisTimelineAnalysisIdRouteImport } from "./routes/_auth/project/$projectId/analysis/timeline/$analysisId";
import { Route as AuthProjectProjectIdAnalysisConceptsOverTimeAnalysisCotaIdRouteImport } from "./routes/_auth/project/$projectId/analysis/concepts-over-time-analysis/$cotaId";

const PublicRoute = PublicRouteImport.update({
  id: "/_public",
  getParentRoute: () => rootRouteImport,
} as any);
const AuthRoute = AuthRouteImport.update({
  id: "/_auth",
  getParentRoute: () => rootRouteImport,
} as any);
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => PublicRoute,
} as any);
const PublicRegisterRoute = PublicRegisterRouteImport.update({
  id: "/register",
  path: "/register",
  getParentRoute: () => PublicRoute,
} as any);
const PublicLoginRoute = PublicLoginRouteImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => PublicRoute,
} as any);
const AuthProjectsRoute = AuthProjectsRouteImport.update({
  id: "/projects",
  path: "/projects",
  getParentRoute: () => AuthRoute,
} as any);
const AuthMeRoute = AuthMeRouteImport.update({
  id: "/me",
  path: "/me",
  getParentRoute: () => AuthRoute,
} as any);
const AuthProjectProjectIdRouteRoute = AuthProjectProjectIdRouteRouteImport.update({
  id: "/project/$projectId",
  path: "/project/$projectId",
  getParentRoute: () => AuthRoute,
} as any);
const AuthProjectProjectIdSentencesearchRoute = AuthProjectProjectIdSentencesearchRouteImport.update({
  id: "/sentencesearch",
  path: "/sentencesearch",
  getParentRoute: () => AuthProjectProjectIdRouteRoute,
} as any);
const AuthProjectProjectIdSearchRoute = AuthProjectProjectIdSearchRouteImport.update({
  id: "/search",
  path: "/search",
  getParentRoute: () => AuthProjectProjectIdRouteRoute,
} as any);
const AuthProjectProjectIdLogbookRoute = AuthProjectProjectIdLogbookRouteImport.update({
  id: "/logbook",
  path: "/logbook",
  getParentRoute: () => AuthProjectProjectIdRouteRoute,
} as any);
const AuthProjectProjectIdImagesearchRoute = AuthProjectProjectIdImagesearchRouteImport.update({
  id: "/imagesearch",
  path: "/imagesearch",
  getParentRoute: () => AuthProjectProjectIdRouteRoute,
} as any);
const AuthProjectProjectIdClassifierRoute = AuthProjectProjectIdClassifierRouteImport.update({
  id: "/classifier",
  path: "/classifier",
  getParentRoute: () => AuthProjectProjectIdRouteRoute,
} as any);
const AuthProjectProjectIdWhiteboardIndexRoute = AuthProjectProjectIdWhiteboardIndexRouteImport.update({
  id: "/whiteboard/",
  path: "/whiteboard/",
  getParentRoute: () => AuthProjectProjectIdRouteRoute,
} as any);
const AuthProjectProjectIdPerspectivesIndexRoute = AuthProjectProjectIdPerspectivesIndexRouteImport.update({
  id: "/perspectives/",
  path: "/perspectives/",
  getParentRoute: () => AuthProjectProjectIdRouteRoute,
} as any);
const AuthProjectProjectIdAnnotationIndexRoute = AuthProjectProjectIdAnnotationIndexRouteImport.update({
  id: "/annotation/",
  path: "/annotation/",
  getParentRoute: () => AuthProjectProjectIdRouteRoute,
} as any);
const AuthProjectProjectIdAnalysisIndexRoute = AuthProjectProjectIdAnalysisIndexRouteImport.update({
  id: "/analysis/",
  path: "/analysis/",
  getParentRoute: () => AuthProjectProjectIdRouteRoute,
} as any);
const AuthProjectProjectIdWhiteboardWhiteboardIdRoute = AuthProjectProjectIdWhiteboardWhiteboardIdRouteImport.update({
  id: "/whiteboard/$whiteboardId",
  path: "/whiteboard/$whiteboardId",
  getParentRoute: () => AuthProjectProjectIdRouteRoute,
} as any);
const AuthProjectProjectIdToolsMlAutomationRoute = AuthProjectProjectIdToolsMlAutomationRouteImport.update({
  id: "/tools/ml-automation",
  path: "/tools/ml-automation",
  getParentRoute: () => AuthProjectProjectIdRouteRoute,
} as any);
const AuthProjectProjectIdToolsHealthRoute = AuthProjectProjectIdToolsHealthRouteImport.update({
  id: "/tools/health",
  path: "/tools/health",
  getParentRoute: () => AuthProjectProjectIdRouteRoute,
} as any);
const AuthProjectProjectIdToolsDuplicateFinderRoute = AuthProjectProjectIdToolsDuplicateFinderRouteImport.update({
  id: "/tools/duplicate-finder",
  path: "/tools/duplicate-finder",
  getParentRoute: () => AuthProjectProjectIdRouteRoute,
} as any);
const AuthProjectProjectIdToolsDocumentSamplerRoute = AuthProjectProjectIdToolsDocumentSamplerRouteImport.update({
  id: "/tools/document-sampler",
  path: "/tools/document-sampler",
  getParentRoute: () => AuthProjectProjectIdRouteRoute,
} as any);
const AuthProjectProjectIdAnnotationSdocIdRoute = AuthProjectProjectIdAnnotationSdocIdRouteImport.update({
  id: "/annotation/$sdocId",
  path: "/annotation/$sdocId",
  getParentRoute: () => AuthProjectProjectIdRouteRoute,
} as any);
const AuthProjectProjectIdAnalysisWordFrequencyRoute = AuthProjectProjectIdAnalysisWordFrequencyRouteImport.update({
  id: "/analysis/word-frequency",
  path: "/analysis/word-frequency",
  getParentRoute: () => AuthProjectProjectIdRouteRoute,
} as any);
const AuthProjectProjectIdAnalysisTagRecommendationsRoute =
  AuthProjectProjectIdAnalysisTagRecommendationsRouteImport.update({
    id: "/analysis/tag-recommendations",
    path: "/analysis/tag-recommendations",
    getParentRoute: () => AuthProjectProjectIdRouteRoute,
  } as any);
const AuthProjectProjectIdAnalysisSpanAnnotationsRoute = AuthProjectProjectIdAnalysisSpanAnnotationsRouteImport.update({
  id: "/analysis/span-annotations",
  path: "/analysis/span-annotations",
  getParentRoute: () => AuthProjectProjectIdRouteRoute,
} as any);
const AuthProjectProjectIdAnalysisSentenceAnnotationsRoute =
  AuthProjectProjectIdAnalysisSentenceAnnotationsRouteImport.update({
    id: "/analysis/sentence-annotations",
    path: "/analysis/sentence-annotations",
    getParentRoute: () => AuthProjectProjectIdRouteRoute,
  } as any);
const AuthProjectProjectIdAnalysisCodeFrequencyRoute = AuthProjectProjectIdAnalysisCodeFrequencyRouteImport.update({
  id: "/analysis/code-frequency",
  path: "/analysis/code-frequency",
  getParentRoute: () => AuthProjectProjectIdRouteRoute,
} as any);
const AuthProjectProjectIdAnalysisBboxAnnotationsRoute = AuthProjectProjectIdAnalysisBboxAnnotationsRouteImport.update({
  id: "/analysis/bbox-annotations",
  path: "/analysis/bbox-annotations",
  getParentRoute: () => AuthProjectProjectIdRouteRoute,
} as any);
const AuthProjectProjectIdAnalysisAnnotationScalingRoute =
  AuthProjectProjectIdAnalysisAnnotationScalingRouteImport.update({
    id: "/analysis/annotation-scaling",
    path: "/analysis/annotation-scaling",
    getParentRoute: () => AuthProjectProjectIdRouteRoute,
  } as any);
const AuthProjectProjectIdPerspectivesAspectIdRouteRoute =
  AuthProjectProjectIdPerspectivesAspectIdRouteRouteImport.update({
    id: "/perspectives/$aspectId",
    path: "/perspectives/$aspectId",
    getParentRoute: () => AuthProjectProjectIdRouteRoute,
  } as any);
const AuthProjectProjectIdPerspectivesAspectIdIndexRoute =
  AuthProjectProjectIdPerspectivesAspectIdIndexRouteImport.update({
    id: "/",
    path: "/",
    getParentRoute: () => AuthProjectProjectIdPerspectivesAspectIdRouteRoute,
  } as any);
const AuthProjectProjectIdAnalysisTimelineIndexRoute = AuthProjectProjectIdAnalysisTimelineIndexRouteImport.update({
  id: "/analysis/timeline/",
  path: "/analysis/timeline/",
  getParentRoute: () => AuthProjectProjectIdRouteRoute,
} as any);
const AuthProjectProjectIdAnalysisConceptsOverTimeAnalysisIndexRoute =
  AuthProjectProjectIdAnalysisConceptsOverTimeAnalysisIndexRouteImport.update({
    id: "/analysis/concepts-over-time-analysis/",
    path: "/analysis/concepts-over-time-analysis/",
    getParentRoute: () => AuthProjectProjectIdRouteRoute,
  } as any);
const AuthProjectProjectIdPerspectivesAspectIdMapRoute = AuthProjectProjectIdPerspectivesAspectIdMapRouteImport.update({
  id: "/map",
  path: "/map",
  getParentRoute: () => AuthProjectProjectIdPerspectivesAspectIdRouteRoute,
} as any);
const AuthProjectProjectIdAnalysisTimelineAnalysisIdRoute =
  AuthProjectProjectIdAnalysisTimelineAnalysisIdRouteImport.update({
    id: "/analysis/timeline/$analysisId",
    path: "/analysis/timeline/$analysisId",
    getParentRoute: () => AuthProjectProjectIdRouteRoute,
  } as any);
const AuthProjectProjectIdAnalysisConceptsOverTimeAnalysisCotaIdRoute =
  AuthProjectProjectIdAnalysisConceptsOverTimeAnalysisCotaIdRouteImport.update({
    id: "/analysis/concepts-over-time-analysis/$cotaId",
    path: "/analysis/concepts-over-time-analysis/$cotaId",
    getParentRoute: () => AuthProjectProjectIdRouteRoute,
  } as any);

export interface FileRoutesByFullPath {
  "/": typeof PublicIndexRoute;
  "/me": typeof AuthMeRoute;
  "/projects": typeof AuthProjectsRoute;
  "/login": typeof PublicLoginRoute;
  "/register": typeof PublicRegisterRoute;
  "/project/$projectId": typeof AuthProjectProjectIdRouteRouteWithChildren;
  "/project/$projectId/classifier": typeof AuthProjectProjectIdClassifierRoute;
  "/project/$projectId/imagesearch": typeof AuthProjectProjectIdImagesearchRoute;
  "/project/$projectId/logbook": typeof AuthProjectProjectIdLogbookRoute;
  "/project/$projectId/search": typeof AuthProjectProjectIdSearchRoute;
  "/project/$projectId/sentencesearch": typeof AuthProjectProjectIdSentencesearchRoute;
  "/project/$projectId/perspectives/$aspectId": typeof AuthProjectProjectIdPerspectivesAspectIdRouteRouteWithChildren;
  "/project/$projectId/analysis/annotation-scaling": typeof AuthProjectProjectIdAnalysisAnnotationScalingRoute;
  "/project/$projectId/analysis/bbox-annotations": typeof AuthProjectProjectIdAnalysisBboxAnnotationsRoute;
  "/project/$projectId/analysis/code-frequency": typeof AuthProjectProjectIdAnalysisCodeFrequencyRoute;
  "/project/$projectId/analysis/sentence-annotations": typeof AuthProjectProjectIdAnalysisSentenceAnnotationsRoute;
  "/project/$projectId/analysis/span-annotations": typeof AuthProjectProjectIdAnalysisSpanAnnotationsRoute;
  "/project/$projectId/analysis/tag-recommendations": typeof AuthProjectProjectIdAnalysisTagRecommendationsRoute;
  "/project/$projectId/analysis/word-frequency": typeof AuthProjectProjectIdAnalysisWordFrequencyRoute;
  "/project/$projectId/annotation/$sdocId": typeof AuthProjectProjectIdAnnotationSdocIdRoute;
  "/project/$projectId/tools/document-sampler": typeof AuthProjectProjectIdToolsDocumentSamplerRoute;
  "/project/$projectId/tools/duplicate-finder": typeof AuthProjectProjectIdToolsDuplicateFinderRoute;
  "/project/$projectId/tools/health": typeof AuthProjectProjectIdToolsHealthRoute;
  "/project/$projectId/tools/ml-automation": typeof AuthProjectProjectIdToolsMlAutomationRoute;
  "/project/$projectId/whiteboard/$whiteboardId": typeof AuthProjectProjectIdWhiteboardWhiteboardIdRoute;
  "/project/$projectId/analysis/": typeof AuthProjectProjectIdAnalysisIndexRoute;
  "/project/$projectId/annotation/": typeof AuthProjectProjectIdAnnotationIndexRoute;
  "/project/$projectId/perspectives/": typeof AuthProjectProjectIdPerspectivesIndexRoute;
  "/project/$projectId/whiteboard/": typeof AuthProjectProjectIdWhiteboardIndexRoute;
  "/project/$projectId/analysis/concepts-over-time-analysis/$cotaId": typeof AuthProjectProjectIdAnalysisConceptsOverTimeAnalysisCotaIdRoute;
  "/project/$projectId/analysis/timeline/$analysisId": typeof AuthProjectProjectIdAnalysisTimelineAnalysisIdRoute;
  "/project/$projectId/perspectives/$aspectId/map": typeof AuthProjectProjectIdPerspectivesAspectIdMapRoute;
  "/project/$projectId/analysis/concepts-over-time-analysis/": typeof AuthProjectProjectIdAnalysisConceptsOverTimeAnalysisIndexRoute;
  "/project/$projectId/analysis/timeline/": typeof AuthProjectProjectIdAnalysisTimelineIndexRoute;
  "/project/$projectId/perspectives/$aspectId/": typeof AuthProjectProjectIdPerspectivesAspectIdIndexRoute;
}
export interface FileRoutesByTo {
  "/": typeof PublicIndexRoute;
  "/me": typeof AuthMeRoute;
  "/projects": typeof AuthProjectsRoute;
  "/login": typeof PublicLoginRoute;
  "/register": typeof PublicRegisterRoute;
  "/project/$projectId": typeof AuthProjectProjectIdRouteRouteWithChildren;
  "/project/$projectId/classifier": typeof AuthProjectProjectIdClassifierRoute;
  "/project/$projectId/imagesearch": typeof AuthProjectProjectIdImagesearchRoute;
  "/project/$projectId/logbook": typeof AuthProjectProjectIdLogbookRoute;
  "/project/$projectId/search": typeof AuthProjectProjectIdSearchRoute;
  "/project/$projectId/sentencesearch": typeof AuthProjectProjectIdSentencesearchRoute;
  "/project/$projectId/analysis/annotation-scaling": typeof AuthProjectProjectIdAnalysisAnnotationScalingRoute;
  "/project/$projectId/analysis/bbox-annotations": typeof AuthProjectProjectIdAnalysisBboxAnnotationsRoute;
  "/project/$projectId/analysis/code-frequency": typeof AuthProjectProjectIdAnalysisCodeFrequencyRoute;
  "/project/$projectId/analysis/sentence-annotations": typeof AuthProjectProjectIdAnalysisSentenceAnnotationsRoute;
  "/project/$projectId/analysis/span-annotations": typeof AuthProjectProjectIdAnalysisSpanAnnotationsRoute;
  "/project/$projectId/analysis/tag-recommendations": typeof AuthProjectProjectIdAnalysisTagRecommendationsRoute;
  "/project/$projectId/analysis/word-frequency": typeof AuthProjectProjectIdAnalysisWordFrequencyRoute;
  "/project/$projectId/annotation/$sdocId": typeof AuthProjectProjectIdAnnotationSdocIdRoute;
  "/project/$projectId/tools/document-sampler": typeof AuthProjectProjectIdToolsDocumentSamplerRoute;
  "/project/$projectId/tools/duplicate-finder": typeof AuthProjectProjectIdToolsDuplicateFinderRoute;
  "/project/$projectId/tools/health": typeof AuthProjectProjectIdToolsHealthRoute;
  "/project/$projectId/tools/ml-automation": typeof AuthProjectProjectIdToolsMlAutomationRoute;
  "/project/$projectId/whiteboard/$whiteboardId": typeof AuthProjectProjectIdWhiteboardWhiteboardIdRoute;
  "/project/$projectId/analysis": typeof AuthProjectProjectIdAnalysisIndexRoute;
  "/project/$projectId/annotation": typeof AuthProjectProjectIdAnnotationIndexRoute;
  "/project/$projectId/perspectives": typeof AuthProjectProjectIdPerspectivesIndexRoute;
  "/project/$projectId/whiteboard": typeof AuthProjectProjectIdWhiteboardIndexRoute;
  "/project/$projectId/analysis/concepts-over-time-analysis/$cotaId": typeof AuthProjectProjectIdAnalysisConceptsOverTimeAnalysisCotaIdRoute;
  "/project/$projectId/analysis/timeline/$analysisId": typeof AuthProjectProjectIdAnalysisTimelineAnalysisIdRoute;
  "/project/$projectId/perspectives/$aspectId/map": typeof AuthProjectProjectIdPerspectivesAspectIdMapRoute;
  "/project/$projectId/analysis/concepts-over-time-analysis": typeof AuthProjectProjectIdAnalysisConceptsOverTimeAnalysisIndexRoute;
  "/project/$projectId/analysis/timeline": typeof AuthProjectProjectIdAnalysisTimelineIndexRoute;
  "/project/$projectId/perspectives/$aspectId": typeof AuthProjectProjectIdPerspectivesAspectIdIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/_auth": typeof AuthRouteWithChildren;
  "/_public": typeof PublicRouteWithChildren;
  "/_auth/me": typeof AuthMeRoute;
  "/_auth/projects": typeof AuthProjectsRoute;
  "/_public/login": typeof PublicLoginRoute;
  "/_public/register": typeof PublicRegisterRoute;
  "/_public/": typeof PublicIndexRoute;
  "/_auth/project/$projectId": typeof AuthProjectProjectIdRouteRouteWithChildren;
  "/_auth/project/$projectId/classifier": typeof AuthProjectProjectIdClassifierRoute;
  "/_auth/project/$projectId/imagesearch": typeof AuthProjectProjectIdImagesearchRoute;
  "/_auth/project/$projectId/logbook": typeof AuthProjectProjectIdLogbookRoute;
  "/_auth/project/$projectId/search": typeof AuthProjectProjectIdSearchRoute;
  "/_auth/project/$projectId/sentencesearch": typeof AuthProjectProjectIdSentencesearchRoute;
  "/_auth/project/$projectId/perspectives/$aspectId": typeof AuthProjectProjectIdPerspectivesAspectIdRouteRouteWithChildren;
  "/_auth/project/$projectId/analysis/annotation-scaling": typeof AuthProjectProjectIdAnalysisAnnotationScalingRoute;
  "/_auth/project/$projectId/analysis/bbox-annotations": typeof AuthProjectProjectIdAnalysisBboxAnnotationsRoute;
  "/_auth/project/$projectId/analysis/code-frequency": typeof AuthProjectProjectIdAnalysisCodeFrequencyRoute;
  "/_auth/project/$projectId/analysis/sentence-annotations": typeof AuthProjectProjectIdAnalysisSentenceAnnotationsRoute;
  "/_auth/project/$projectId/analysis/span-annotations": typeof AuthProjectProjectIdAnalysisSpanAnnotationsRoute;
  "/_auth/project/$projectId/analysis/tag-recommendations": typeof AuthProjectProjectIdAnalysisTagRecommendationsRoute;
  "/_auth/project/$projectId/analysis/word-frequency": typeof AuthProjectProjectIdAnalysisWordFrequencyRoute;
  "/_auth/project/$projectId/annotation/$sdocId": typeof AuthProjectProjectIdAnnotationSdocIdRoute;
  "/_auth/project/$projectId/tools/document-sampler": typeof AuthProjectProjectIdToolsDocumentSamplerRoute;
  "/_auth/project/$projectId/tools/duplicate-finder": typeof AuthProjectProjectIdToolsDuplicateFinderRoute;
  "/_auth/project/$projectId/tools/health": typeof AuthProjectProjectIdToolsHealthRoute;
  "/_auth/project/$projectId/tools/ml-automation": typeof AuthProjectProjectIdToolsMlAutomationRoute;
  "/_auth/project/$projectId/whiteboard/$whiteboardId": typeof AuthProjectProjectIdWhiteboardWhiteboardIdRoute;
  "/_auth/project/$projectId/analysis/": typeof AuthProjectProjectIdAnalysisIndexRoute;
  "/_auth/project/$projectId/annotation/": typeof AuthProjectProjectIdAnnotationIndexRoute;
  "/_auth/project/$projectId/perspectives/": typeof AuthProjectProjectIdPerspectivesIndexRoute;
  "/_auth/project/$projectId/whiteboard/": typeof AuthProjectProjectIdWhiteboardIndexRoute;
  "/_auth/project/$projectId/analysis/concepts-over-time-analysis/$cotaId": typeof AuthProjectProjectIdAnalysisConceptsOverTimeAnalysisCotaIdRoute;
  "/_auth/project/$projectId/analysis/timeline/$analysisId": typeof AuthProjectProjectIdAnalysisTimelineAnalysisIdRoute;
  "/_auth/project/$projectId/perspectives/$aspectId/map": typeof AuthProjectProjectIdPerspectivesAspectIdMapRoute;
  "/_auth/project/$projectId/analysis/concepts-over-time-analysis/": typeof AuthProjectProjectIdAnalysisConceptsOverTimeAnalysisIndexRoute;
  "/_auth/project/$projectId/analysis/timeline/": typeof AuthProjectProjectIdAnalysisTimelineIndexRoute;
  "/_auth/project/$projectId/perspectives/$aspectId/": typeof AuthProjectProjectIdPerspectivesAspectIdIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/me"
    | "/projects"
    | "/login"
    | "/register"
    | "/project/$projectId"
    | "/project/$projectId/classifier"
    | "/project/$projectId/imagesearch"
    | "/project/$projectId/logbook"
    | "/project/$projectId/search"
    | "/project/$projectId/sentencesearch"
    | "/project/$projectId/perspectives/$aspectId"
    | "/project/$projectId/analysis/annotation-scaling"
    | "/project/$projectId/analysis/bbox-annotations"
    | "/project/$projectId/analysis/code-frequency"
    | "/project/$projectId/analysis/sentence-annotations"
    | "/project/$projectId/analysis/span-annotations"
    | "/project/$projectId/analysis/tag-recommendations"
    | "/project/$projectId/analysis/word-frequency"
    | "/project/$projectId/annotation/$sdocId"
    | "/project/$projectId/tools/document-sampler"
    | "/project/$projectId/tools/duplicate-finder"
    | "/project/$projectId/tools/health"
    | "/project/$projectId/tools/ml-automation"
    | "/project/$projectId/whiteboard/$whiteboardId"
    | "/project/$projectId/analysis/"
    | "/project/$projectId/annotation/"
    | "/project/$projectId/perspectives/"
    | "/project/$projectId/whiteboard/"
    | "/project/$projectId/analysis/concepts-over-time-analysis/$cotaId"
    | "/project/$projectId/analysis/timeline/$analysisId"
    | "/project/$projectId/perspectives/$aspectId/map"
    | "/project/$projectId/analysis/concepts-over-time-analysis/"
    | "/project/$projectId/analysis/timeline/"
    | "/project/$projectId/perspectives/$aspectId/";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | "/me"
    | "/projects"
    | "/login"
    | "/register"
    | "/project/$projectId"
    | "/project/$projectId/classifier"
    | "/project/$projectId/imagesearch"
    | "/project/$projectId/logbook"
    | "/project/$projectId/search"
    | "/project/$projectId/sentencesearch"
    | "/project/$projectId/analysis/annotation-scaling"
    | "/project/$projectId/analysis/bbox-annotations"
    | "/project/$projectId/analysis/code-frequency"
    | "/project/$projectId/analysis/sentence-annotations"
    | "/project/$projectId/analysis/span-annotations"
    | "/project/$projectId/analysis/tag-recommendations"
    | "/project/$projectId/analysis/word-frequency"
    | "/project/$projectId/annotation/$sdocId"
    | "/project/$projectId/tools/document-sampler"
    | "/project/$projectId/tools/duplicate-finder"
    | "/project/$projectId/tools/health"
    | "/project/$projectId/tools/ml-automation"
    | "/project/$projectId/whiteboard/$whiteboardId"
    | "/project/$projectId/analysis"
    | "/project/$projectId/annotation"
    | "/project/$projectId/perspectives"
    | "/project/$projectId/whiteboard"
    | "/project/$projectId/analysis/concepts-over-time-analysis/$cotaId"
    | "/project/$projectId/analysis/timeline/$analysisId"
    | "/project/$projectId/perspectives/$aspectId/map"
    | "/project/$projectId/analysis/concepts-over-time-analysis"
    | "/project/$projectId/analysis/timeline"
    | "/project/$projectId/perspectives/$aspectId";
  id:
    | "__root__"
    | "/_auth"
    | "/_public"
    | "/_auth/me"
    | "/_auth/projects"
    | "/_public/login"
    | "/_public/register"
    | "/_public/"
    | "/_auth/project/$projectId"
    | "/_auth/project/$projectId/classifier"
    | "/_auth/project/$projectId/imagesearch"
    | "/_auth/project/$projectId/logbook"
    | "/_auth/project/$projectId/search"
    | "/_auth/project/$projectId/sentencesearch"
    | "/_auth/project/$projectId/perspectives/$aspectId"
    | "/_auth/project/$projectId/analysis/annotation-scaling"
    | "/_auth/project/$projectId/analysis/bbox-annotations"
    | "/_auth/project/$projectId/analysis/code-frequency"
    | "/_auth/project/$projectId/analysis/sentence-annotations"
    | "/_auth/project/$projectId/analysis/span-annotations"
    | "/_auth/project/$projectId/analysis/tag-recommendations"
    | "/_auth/project/$projectId/analysis/word-frequency"
    | "/_auth/project/$projectId/annotation/$sdocId"
    | "/_auth/project/$projectId/tools/document-sampler"
    | "/_auth/project/$projectId/tools/duplicate-finder"
    | "/_auth/project/$projectId/tools/health"
    | "/_auth/project/$projectId/tools/ml-automation"
    | "/_auth/project/$projectId/whiteboard/$whiteboardId"
    | "/_auth/project/$projectId/analysis/"
    | "/_auth/project/$projectId/annotation/"
    | "/_auth/project/$projectId/perspectives/"
    | "/_auth/project/$projectId/whiteboard/"
    | "/_auth/project/$projectId/analysis/concepts-over-time-analysis/$cotaId"
    | "/_auth/project/$projectId/analysis/timeline/$analysisId"
    | "/_auth/project/$projectId/perspectives/$aspectId/map"
    | "/_auth/project/$projectId/analysis/concepts-over-time-analysis/"
    | "/_auth/project/$projectId/analysis/timeline/"
    | "/_auth/project/$projectId/perspectives/$aspectId/";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren;
  PublicRoute: typeof PublicRouteWithChildren;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/_public": {
      id: "/_public";
      path: "";
      fullPath: "/";
      preLoaderRoute: typeof PublicRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_auth": {
      id: "/_auth";
      path: "";
      fullPath: "/";
      preLoaderRoute: typeof AuthRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_public/": {
      id: "/_public/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof PublicIndexRouteImport;
      parentRoute: typeof PublicRoute;
    };
    "/_public/register": {
      id: "/_public/register";
      path: "/register";
      fullPath: "/register";
      preLoaderRoute: typeof PublicRegisterRouteImport;
      parentRoute: typeof PublicRoute;
    };
    "/_public/login": {
      id: "/_public/login";
      path: "/login";
      fullPath: "/login";
      preLoaderRoute: typeof PublicLoginRouteImport;
      parentRoute: typeof PublicRoute;
    };
    "/_auth/projects": {
      id: "/_auth/projects";
      path: "/projects";
      fullPath: "/projects";
      preLoaderRoute: typeof AuthProjectsRouteImport;
      parentRoute: typeof AuthRoute;
    };
    "/_auth/me": {
      id: "/_auth/me";
      path: "/me";
      fullPath: "/me";
      preLoaderRoute: typeof AuthMeRouteImport;
      parentRoute: typeof AuthRoute;
    };
    "/_auth/project/$projectId": {
      id: "/_auth/project/$projectId";
      path: "/project/$projectId";
      fullPath: "/project/$projectId";
      preLoaderRoute: typeof AuthProjectProjectIdRouteRouteImport;
      parentRoute: typeof AuthRoute;
    };
    "/_auth/project/$projectId/sentencesearch": {
      id: "/_auth/project/$projectId/sentencesearch";
      path: "/sentencesearch";
      fullPath: "/project/$projectId/sentencesearch";
      preLoaderRoute: typeof AuthProjectProjectIdSentencesearchRouteImport;
      parentRoute: typeof AuthProjectProjectIdRouteRoute;
    };
    "/_auth/project/$projectId/search": {
      id: "/_auth/project/$projectId/search";
      path: "/search";
      fullPath: "/project/$projectId/search";
      preLoaderRoute: typeof AuthProjectProjectIdSearchRouteImport;
      parentRoute: typeof AuthProjectProjectIdRouteRoute;
    };
    "/_auth/project/$projectId/logbook": {
      id: "/_auth/project/$projectId/logbook";
      path: "/logbook";
      fullPath: "/project/$projectId/logbook";
      preLoaderRoute: typeof AuthProjectProjectIdLogbookRouteImport;
      parentRoute: typeof AuthProjectProjectIdRouteRoute;
    };
    "/_auth/project/$projectId/imagesearch": {
      id: "/_auth/project/$projectId/imagesearch";
      path: "/imagesearch";
      fullPath: "/project/$projectId/imagesearch";
      preLoaderRoute: typeof AuthProjectProjectIdImagesearchRouteImport;
      parentRoute: typeof AuthProjectProjectIdRouteRoute;
    };
    "/_auth/project/$projectId/classifier": {
      id: "/_auth/project/$projectId/classifier";
      path: "/classifier";
      fullPath: "/project/$projectId/classifier";
      preLoaderRoute: typeof AuthProjectProjectIdClassifierRouteImport;
      parentRoute: typeof AuthProjectProjectIdRouteRoute;
    };
    "/_auth/project/$projectId/whiteboard/": {
      id: "/_auth/project/$projectId/whiteboard/";
      path: "/whiteboard";
      fullPath: "/project/$projectId/whiteboard/";
      preLoaderRoute: typeof AuthProjectProjectIdWhiteboardIndexRouteImport;
      parentRoute: typeof AuthProjectProjectIdRouteRoute;
    };
    "/_auth/project/$projectId/perspectives/": {
      id: "/_auth/project/$projectId/perspectives/";
      path: "/perspectives";
      fullPath: "/project/$projectId/perspectives/";
      preLoaderRoute: typeof AuthProjectProjectIdPerspectivesIndexRouteImport;
      parentRoute: typeof AuthProjectProjectIdRouteRoute;
    };
    "/_auth/project/$projectId/annotation/": {
      id: "/_auth/project/$projectId/annotation/";
      path: "/annotation";
      fullPath: "/project/$projectId/annotation/";
      preLoaderRoute: typeof AuthProjectProjectIdAnnotationIndexRouteImport;
      parentRoute: typeof AuthProjectProjectIdRouteRoute;
    };
    "/_auth/project/$projectId/analysis/": {
      id: "/_auth/project/$projectId/analysis/";
      path: "/analysis";
      fullPath: "/project/$projectId/analysis/";
      preLoaderRoute: typeof AuthProjectProjectIdAnalysisIndexRouteImport;
      parentRoute: typeof AuthProjectProjectIdRouteRoute;
    };
    "/_auth/project/$projectId/whiteboard/$whiteboardId": {
      id: "/_auth/project/$projectId/whiteboard/$whiteboardId";
      path: "/whiteboard/$whiteboardId";
      fullPath: "/project/$projectId/whiteboard/$whiteboardId";
      preLoaderRoute: typeof AuthProjectProjectIdWhiteboardWhiteboardIdRouteImport;
      parentRoute: typeof AuthProjectProjectIdRouteRoute;
    };
    "/_auth/project/$projectId/tools/ml-automation": {
      id: "/_auth/project/$projectId/tools/ml-automation";
      path: "/tools/ml-automation";
      fullPath: "/project/$projectId/tools/ml-automation";
      preLoaderRoute: typeof AuthProjectProjectIdToolsMlAutomationRouteImport;
      parentRoute: typeof AuthProjectProjectIdRouteRoute;
    };
    "/_auth/project/$projectId/tools/health": {
      id: "/_auth/project/$projectId/tools/health";
      path: "/tools/health";
      fullPath: "/project/$projectId/tools/health";
      preLoaderRoute: typeof AuthProjectProjectIdToolsHealthRouteImport;
      parentRoute: typeof AuthProjectProjectIdRouteRoute;
    };
    "/_auth/project/$projectId/tools/duplicate-finder": {
      id: "/_auth/project/$projectId/tools/duplicate-finder";
      path: "/tools/duplicate-finder";
      fullPath: "/project/$projectId/tools/duplicate-finder";
      preLoaderRoute: typeof AuthProjectProjectIdToolsDuplicateFinderRouteImport;
      parentRoute: typeof AuthProjectProjectIdRouteRoute;
    };
    "/_auth/project/$projectId/tools/document-sampler": {
      id: "/_auth/project/$projectId/tools/document-sampler";
      path: "/tools/document-sampler";
      fullPath: "/project/$projectId/tools/document-sampler";
      preLoaderRoute: typeof AuthProjectProjectIdToolsDocumentSamplerRouteImport;
      parentRoute: typeof AuthProjectProjectIdRouteRoute;
    };
    "/_auth/project/$projectId/annotation/$sdocId": {
      id: "/_auth/project/$projectId/annotation/$sdocId";
      path: "/annotation/$sdocId";
      fullPath: "/project/$projectId/annotation/$sdocId";
      preLoaderRoute: typeof AuthProjectProjectIdAnnotationSdocIdRouteImport;
      parentRoute: typeof AuthProjectProjectIdRouteRoute;
    };
    "/_auth/project/$projectId/analysis/word-frequency": {
      id: "/_auth/project/$projectId/analysis/word-frequency";
      path: "/analysis/word-frequency";
      fullPath: "/project/$projectId/analysis/word-frequency";
      preLoaderRoute: typeof AuthProjectProjectIdAnalysisWordFrequencyRouteImport;
      parentRoute: typeof AuthProjectProjectIdRouteRoute;
    };
    "/_auth/project/$projectId/analysis/tag-recommendations": {
      id: "/_auth/project/$projectId/analysis/tag-recommendations";
      path: "/analysis/tag-recommendations";
      fullPath: "/project/$projectId/analysis/tag-recommendations";
      preLoaderRoute: typeof AuthProjectProjectIdAnalysisTagRecommendationsRouteImport;
      parentRoute: typeof AuthProjectProjectIdRouteRoute;
    };
    "/_auth/project/$projectId/analysis/span-annotations": {
      id: "/_auth/project/$projectId/analysis/span-annotations";
      path: "/analysis/span-annotations";
      fullPath: "/project/$projectId/analysis/span-annotations";
      preLoaderRoute: typeof AuthProjectProjectIdAnalysisSpanAnnotationsRouteImport;
      parentRoute: typeof AuthProjectProjectIdRouteRoute;
    };
    "/_auth/project/$projectId/analysis/sentence-annotations": {
      id: "/_auth/project/$projectId/analysis/sentence-annotations";
      path: "/analysis/sentence-annotations";
      fullPath: "/project/$projectId/analysis/sentence-annotations";
      preLoaderRoute: typeof AuthProjectProjectIdAnalysisSentenceAnnotationsRouteImport;
      parentRoute: typeof AuthProjectProjectIdRouteRoute;
    };
    "/_auth/project/$projectId/analysis/code-frequency": {
      id: "/_auth/project/$projectId/analysis/code-frequency";
      path: "/analysis/code-frequency";
      fullPath: "/project/$projectId/analysis/code-frequency";
      preLoaderRoute: typeof AuthProjectProjectIdAnalysisCodeFrequencyRouteImport;
      parentRoute: typeof AuthProjectProjectIdRouteRoute;
    };
    "/_auth/project/$projectId/analysis/bbox-annotations": {
      id: "/_auth/project/$projectId/analysis/bbox-annotations";
      path: "/analysis/bbox-annotations";
      fullPath: "/project/$projectId/analysis/bbox-annotations";
      preLoaderRoute: typeof AuthProjectProjectIdAnalysisBboxAnnotationsRouteImport;
      parentRoute: typeof AuthProjectProjectIdRouteRoute;
    };
    "/_auth/project/$projectId/analysis/annotation-scaling": {
      id: "/_auth/project/$projectId/analysis/annotation-scaling";
      path: "/analysis/annotation-scaling";
      fullPath: "/project/$projectId/analysis/annotation-scaling";
      preLoaderRoute: typeof AuthProjectProjectIdAnalysisAnnotationScalingRouteImport;
      parentRoute: typeof AuthProjectProjectIdRouteRoute;
    };
    "/_auth/project/$projectId/perspectives/$aspectId": {
      id: "/_auth/project/$projectId/perspectives/$aspectId";
      path: "/perspectives/$aspectId";
      fullPath: "/project/$projectId/perspectives/$aspectId";
      preLoaderRoute: typeof AuthProjectProjectIdPerspectivesAspectIdRouteRouteImport;
      parentRoute: typeof AuthProjectProjectIdRouteRoute;
    };
    "/_auth/project/$projectId/perspectives/$aspectId/": {
      id: "/_auth/project/$projectId/perspectives/$aspectId/";
      path: "/";
      fullPath: "/project/$projectId/perspectives/$aspectId/";
      preLoaderRoute: typeof AuthProjectProjectIdPerspectivesAspectIdIndexRouteImport;
      parentRoute: typeof AuthProjectProjectIdPerspectivesAspectIdRouteRoute;
    };
    "/_auth/project/$projectId/analysis/timeline/": {
      id: "/_auth/project/$projectId/analysis/timeline/";
      path: "/analysis/timeline";
      fullPath: "/project/$projectId/analysis/timeline/";
      preLoaderRoute: typeof AuthProjectProjectIdAnalysisTimelineIndexRouteImport;
      parentRoute: typeof AuthProjectProjectIdRouteRoute;
    };
    "/_auth/project/$projectId/analysis/concepts-over-time-analysis/": {
      id: "/_auth/project/$projectId/analysis/concepts-over-time-analysis/";
      path: "/analysis/concepts-over-time-analysis";
      fullPath: "/project/$projectId/analysis/concepts-over-time-analysis/";
      preLoaderRoute: typeof AuthProjectProjectIdAnalysisConceptsOverTimeAnalysisIndexRouteImport;
      parentRoute: typeof AuthProjectProjectIdRouteRoute;
    };
    "/_auth/project/$projectId/perspectives/$aspectId/map": {
      id: "/_auth/project/$projectId/perspectives/$aspectId/map";
      path: "/map";
      fullPath: "/project/$projectId/perspectives/$aspectId/map";
      preLoaderRoute: typeof AuthProjectProjectIdPerspectivesAspectIdMapRouteImport;
      parentRoute: typeof AuthProjectProjectIdPerspectivesAspectIdRouteRoute;
    };
    "/_auth/project/$projectId/analysis/timeline/$analysisId": {
      id: "/_auth/project/$projectId/analysis/timeline/$analysisId";
      path: "/analysis/timeline/$analysisId";
      fullPath: "/project/$projectId/analysis/timeline/$analysisId";
      preLoaderRoute: typeof AuthProjectProjectIdAnalysisTimelineAnalysisIdRouteImport;
      parentRoute: typeof AuthProjectProjectIdRouteRoute;
    };
    "/_auth/project/$projectId/analysis/concepts-over-time-analysis/$cotaId": {
      id: "/_auth/project/$projectId/analysis/concepts-over-time-analysis/$cotaId";
      path: "/analysis/concepts-over-time-analysis/$cotaId";
      fullPath: "/project/$projectId/analysis/concepts-over-time-analysis/$cotaId";
      preLoaderRoute: typeof AuthProjectProjectIdAnalysisConceptsOverTimeAnalysisCotaIdRouteImport;
      parentRoute: typeof AuthProjectProjectIdRouteRoute;
    };
  }
}

interface AuthProjectProjectIdPerspectivesAspectIdRouteRouteChildren {
  AuthProjectProjectIdPerspectivesAspectIdMapRoute: typeof AuthProjectProjectIdPerspectivesAspectIdMapRoute;
  AuthProjectProjectIdPerspectivesAspectIdIndexRoute: typeof AuthProjectProjectIdPerspectivesAspectIdIndexRoute;
}

const AuthProjectProjectIdPerspectivesAspectIdRouteRouteChildren: AuthProjectProjectIdPerspectivesAspectIdRouteRouteChildren =
  {
    AuthProjectProjectIdPerspectivesAspectIdMapRoute: AuthProjectProjectIdPerspectivesAspectIdMapRoute,
    AuthProjectProjectIdPerspectivesAspectIdIndexRoute: AuthProjectProjectIdPerspectivesAspectIdIndexRoute,
  };

const AuthProjectProjectIdPerspectivesAspectIdRouteRouteWithChildren =
  AuthProjectProjectIdPerspectivesAspectIdRouteRoute._addFileChildren(
    AuthProjectProjectIdPerspectivesAspectIdRouteRouteChildren,
  );

interface AuthProjectProjectIdRouteRouteChildren {
  AuthProjectProjectIdClassifierRoute: typeof AuthProjectProjectIdClassifierRoute;
  AuthProjectProjectIdImagesearchRoute: typeof AuthProjectProjectIdImagesearchRoute;
  AuthProjectProjectIdLogbookRoute: typeof AuthProjectProjectIdLogbookRoute;
  AuthProjectProjectIdSearchRoute: typeof AuthProjectProjectIdSearchRoute;
  AuthProjectProjectIdSentencesearchRoute: typeof AuthProjectProjectIdSentencesearchRoute;
  AuthProjectProjectIdPerspectivesAspectIdRouteRoute: typeof AuthProjectProjectIdPerspectivesAspectIdRouteRouteWithChildren;
  AuthProjectProjectIdAnalysisAnnotationScalingRoute: typeof AuthProjectProjectIdAnalysisAnnotationScalingRoute;
  AuthProjectProjectIdAnalysisBboxAnnotationsRoute: typeof AuthProjectProjectIdAnalysisBboxAnnotationsRoute;
  AuthProjectProjectIdAnalysisCodeFrequencyRoute: typeof AuthProjectProjectIdAnalysisCodeFrequencyRoute;
  AuthProjectProjectIdAnalysisSentenceAnnotationsRoute: typeof AuthProjectProjectIdAnalysisSentenceAnnotationsRoute;
  AuthProjectProjectIdAnalysisSpanAnnotationsRoute: typeof AuthProjectProjectIdAnalysisSpanAnnotationsRoute;
  AuthProjectProjectIdAnalysisTagRecommendationsRoute: typeof AuthProjectProjectIdAnalysisTagRecommendationsRoute;
  AuthProjectProjectIdAnalysisWordFrequencyRoute: typeof AuthProjectProjectIdAnalysisWordFrequencyRoute;
  AuthProjectProjectIdAnnotationSdocIdRoute: typeof AuthProjectProjectIdAnnotationSdocIdRoute;
  AuthProjectProjectIdToolsDocumentSamplerRoute: typeof AuthProjectProjectIdToolsDocumentSamplerRoute;
  AuthProjectProjectIdToolsDuplicateFinderRoute: typeof AuthProjectProjectIdToolsDuplicateFinderRoute;
  AuthProjectProjectIdToolsHealthRoute: typeof AuthProjectProjectIdToolsHealthRoute;
  AuthProjectProjectIdToolsMlAutomationRoute: typeof AuthProjectProjectIdToolsMlAutomationRoute;
  AuthProjectProjectIdWhiteboardWhiteboardIdRoute: typeof AuthProjectProjectIdWhiteboardWhiteboardIdRoute;
  AuthProjectProjectIdAnalysisIndexRoute: typeof AuthProjectProjectIdAnalysisIndexRoute;
  AuthProjectProjectIdAnnotationIndexRoute: typeof AuthProjectProjectIdAnnotationIndexRoute;
  AuthProjectProjectIdPerspectivesIndexRoute: typeof AuthProjectProjectIdPerspectivesIndexRoute;
  AuthProjectProjectIdWhiteboardIndexRoute: typeof AuthProjectProjectIdWhiteboardIndexRoute;
  AuthProjectProjectIdAnalysisConceptsOverTimeAnalysisCotaIdRoute: typeof AuthProjectProjectIdAnalysisConceptsOverTimeAnalysisCotaIdRoute;
  AuthProjectProjectIdAnalysisTimelineAnalysisIdRoute: typeof AuthProjectProjectIdAnalysisTimelineAnalysisIdRoute;
  AuthProjectProjectIdAnalysisConceptsOverTimeAnalysisIndexRoute: typeof AuthProjectProjectIdAnalysisConceptsOverTimeAnalysisIndexRoute;
  AuthProjectProjectIdAnalysisTimelineIndexRoute: typeof AuthProjectProjectIdAnalysisTimelineIndexRoute;
}

const AuthProjectProjectIdRouteRouteChildren: AuthProjectProjectIdRouteRouteChildren = {
  AuthProjectProjectIdClassifierRoute: AuthProjectProjectIdClassifierRoute,
  AuthProjectProjectIdImagesearchRoute: AuthProjectProjectIdImagesearchRoute,
  AuthProjectProjectIdLogbookRoute: AuthProjectProjectIdLogbookRoute,
  AuthProjectProjectIdSearchRoute: AuthProjectProjectIdSearchRoute,
  AuthProjectProjectIdSentencesearchRoute: AuthProjectProjectIdSentencesearchRoute,
  AuthProjectProjectIdPerspectivesAspectIdRouteRoute: AuthProjectProjectIdPerspectivesAspectIdRouteRouteWithChildren,
  AuthProjectProjectIdAnalysisAnnotationScalingRoute: AuthProjectProjectIdAnalysisAnnotationScalingRoute,
  AuthProjectProjectIdAnalysisBboxAnnotationsRoute: AuthProjectProjectIdAnalysisBboxAnnotationsRoute,
  AuthProjectProjectIdAnalysisCodeFrequencyRoute: AuthProjectProjectIdAnalysisCodeFrequencyRoute,
  AuthProjectProjectIdAnalysisSentenceAnnotationsRoute: AuthProjectProjectIdAnalysisSentenceAnnotationsRoute,
  AuthProjectProjectIdAnalysisSpanAnnotationsRoute: AuthProjectProjectIdAnalysisSpanAnnotationsRoute,
  AuthProjectProjectIdAnalysisTagRecommendationsRoute: AuthProjectProjectIdAnalysisTagRecommendationsRoute,
  AuthProjectProjectIdAnalysisWordFrequencyRoute: AuthProjectProjectIdAnalysisWordFrequencyRoute,
  AuthProjectProjectIdAnnotationSdocIdRoute: AuthProjectProjectIdAnnotationSdocIdRoute,
  AuthProjectProjectIdToolsDocumentSamplerRoute: AuthProjectProjectIdToolsDocumentSamplerRoute,
  AuthProjectProjectIdToolsDuplicateFinderRoute: AuthProjectProjectIdToolsDuplicateFinderRoute,
  AuthProjectProjectIdToolsHealthRoute: AuthProjectProjectIdToolsHealthRoute,
  AuthProjectProjectIdToolsMlAutomationRoute: AuthProjectProjectIdToolsMlAutomationRoute,
  AuthProjectProjectIdWhiteboardWhiteboardIdRoute: AuthProjectProjectIdWhiteboardWhiteboardIdRoute,
  AuthProjectProjectIdAnalysisIndexRoute: AuthProjectProjectIdAnalysisIndexRoute,
  AuthProjectProjectIdAnnotationIndexRoute: AuthProjectProjectIdAnnotationIndexRoute,
  AuthProjectProjectIdPerspectivesIndexRoute: AuthProjectProjectIdPerspectivesIndexRoute,
  AuthProjectProjectIdWhiteboardIndexRoute: AuthProjectProjectIdWhiteboardIndexRoute,
  AuthProjectProjectIdAnalysisConceptsOverTimeAnalysisCotaIdRoute:
    AuthProjectProjectIdAnalysisConceptsOverTimeAnalysisCotaIdRoute,
  AuthProjectProjectIdAnalysisTimelineAnalysisIdRoute: AuthProjectProjectIdAnalysisTimelineAnalysisIdRoute,
  AuthProjectProjectIdAnalysisConceptsOverTimeAnalysisIndexRoute:
    AuthProjectProjectIdAnalysisConceptsOverTimeAnalysisIndexRoute,
  AuthProjectProjectIdAnalysisTimelineIndexRoute: AuthProjectProjectIdAnalysisTimelineIndexRoute,
};

const AuthProjectProjectIdRouteRouteWithChildren = AuthProjectProjectIdRouteRoute._addFileChildren(
  AuthProjectProjectIdRouteRouteChildren,
);

interface AuthRouteChildren {
  AuthMeRoute: typeof AuthMeRoute;
  AuthProjectsRoute: typeof AuthProjectsRoute;
  AuthProjectProjectIdRouteRoute: typeof AuthProjectProjectIdRouteRouteWithChildren;
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthMeRoute: AuthMeRoute,
  AuthProjectsRoute: AuthProjectsRoute,
  AuthProjectProjectIdRouteRoute: AuthProjectProjectIdRouteRouteWithChildren,
};

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren);

interface PublicRouteChildren {
  PublicLoginRoute: typeof PublicLoginRoute;
  PublicRegisterRoute: typeof PublicRegisterRoute;
  PublicIndexRoute: typeof PublicIndexRoute;
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicLoginRoute: PublicLoginRoute,
  PublicRegisterRoute: PublicRegisterRoute,
  PublicIndexRoute: PublicIndexRoute,
};

const PublicRouteWithChildren = PublicRoute._addFileChildren(PublicRouteChildren);

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
};
export const routeTree = rootRouteImport._addFileChildren(rootRouteChildren)._addFileTypes<FileRouteTypes>();
