name: Check backend database schema
on:
  push:
    branches:
      - main
      - mwp_v1
  pull_request:
    paths:
      - "backend/**"
      - ".github/**"
      - "docker/**"

jobs:
  check-schema:
    runs-on: ubuntu-latest
    env:
      API_PRODUCTION_WORKERS: 1
      RAY_ENABLED: False
      OLLAMA_ENABLED: False
      COMPOSE_PROFILES: "background"
    steps:
      - uses: actions/checkout@v3
      - name: Start Docker Containers
        working-directory: docker
        run: |
          ./setup-folders.sh
          cp .env.example .env
          chmod -R a+rwx backend_repo/ models_cache/ spacy_models/
          python monkey_patch_docker_compose_for_backend_tests.py --disable_ray --disable_ollama
          export GID=$(id -g)
          docker compose -f compose-test.yml up -d --quiet-pull postgres
          echo Waiting for containers to start...
          sleep 10
      - name: Migrate database
        working-directory: docker
        run: |
          docker compose -f compose-test.yml run dats-backend-api PYTHONPATH=/dats_code/src /opt/envs/dats/bin/python migration/run_migrations.py
      - name: Check that database schema is up-to-date
        working-directory: docker
        run: |
          docker compose -f compose-test.yml run dats-backend-api /opt/envs/dats/bin/alembic check
