name: Backend Unit Tests
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches:
      - main
      - mwp_v1
    paths:
      - "backend/**"
      - ".github/**"
      - "docker/**"
  pull_request:
    branches:
      - main
      - mwp_v1

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      logLevel:
        description: "Log level"
        required: true
        default: "warning"
        type: choice
        options:
          - info
          - warning
          - debug
      tags:
        description: "Test scenario tags"
        required: false
        type: boolean
      environment:
        description: "Environment to run tests against"
        type: environment
        required: true

jobs:
  log-the-inputs:
    runs-on: ubuntu-latest
    steps:
      - name: Log the inputs
        env:
          LEVEL: ${{ inputs.logLevel }}
          TAGS: ${{ inputs.tags }}
          ENVIRONMENT: ${{ inputs.environment }}
        run: |
          echo "Log level: $LEVEL"
          echo "Tags: $TAGS"
          echo "Environment: $ENVIRONMENT"
  run-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Set Swap Space to 10GB
        uses: pierotofy/set-swap-space@master
        with:
          swap-size-gb: 10
      - uses: actions/checkout@v3
      - name: Start Docker Containers
        working-directory: docker
        run: |
          ./setup-folders.sh
          cp .env.example .env
          chmod -R a+rwx backend_repo/ models_cache/ spacy_models/
          python monkey_patch_docker_compose_for_backend_tests.py --disable_ray
          export GID=$(id -g)
          export API_PRODUCTION_WORKERS=0
          # disable backend and frontend
          export COMPOSE_PROFILES=
          export RAY_ENABLED=False
          export POSTRES_DB=dwts-test
          docker compose -f compose-test.yml up -d --quiet-pull
          echo Waiting for containers to start...
          sleep 30
      - name: Run unit tests
        working-directory: docker
        run: |
          export RAY_ENABLED=False
          docker compose -f compose-test.yml run -i dwts-backend-api /opt/envs/dwts/bin/python -m pytest
