name: Project Tests
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  paths:
    - 'backend/**'

  # Allows you to run this workflow manually from the Actions tab?
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Set Swap Space to 10GB
        uses: pierotofy/set-swap-space@master
        with:
          swap-size-gb: 10
      - uses: actions/checkout@v3
      - name: Build docker container
        run: |
          cd docker
          ./setup-folders.sh
          chmod -R a+rwx backend_repo/ models_cache/ spacy_models/ tika/
          python compose.py
          export GID=$(id -g)
          export CELERY_TEXT_WORKER_CONCURRENCY=1
          export CELERY_IMAGE_WORKER_CONCURRENCY=1
          export CELERY_SIMSEARCH_WORKER_CONCURRENCY=1
          export CELERY_ARCHIVE_WORKER_CONCURRENCY=1
          export API_PRODUCTION_WORKERS=0
          docker compose -f compose-test.yml up -d --quiet-pull
          sleep 240
          cd ..
      - name: Run CRUD tests
        run: |
          docker exec -i demo-dwts-backend-api-1 /opt/envs/dwts/bin/python -m pytest
      - name: Upload Testdata
        env:
          TESTDATA: ${{ secrets.TESTDATA }}
        run: |
          cd tools/importer
          wget -q http://ltdata1.informatik.uni-hamburg.de/dwts/totalitarismo.zip
          unzip -q -P "$TESTDATA" totalitarismo.zip
          python dwts_importer.py --input_dir images --backend_url http://localhost:13120/ --project_name incel --tag_name totalitarisimo
          python dwts_importer.py --input_dir json --backend_url http://localhost:13120/ --project_name incel --tag_name totalitarismo --is_json
