name: test workflow
on:
  push:
    branches:
      - main
      - mwp_v1
  pull_request:
    paths:
      - ".github/**"

jobs:
  deploy_demo:
    name: deploy_demo
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v3

      - name: Write SSH config & key
        id: write_ssh_keys
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_CONFIG: ${{ secrets.SSH_CONFIG }}
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_ed25519
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_ed25519
          echo "$SSH_CONFIG" > ~/.ssh/config
        shell: bash

      - name: Add server to known hosts
        env:
          SSH_JUMP_HOST: ${{ secrets.SSH_JUMP_HOST }}
        run: |
          ssh-keyscan -H $SSH_JUMP_HOST >> ~/.ssh/known_hosts
        shell: bash

      - name: Deploy
        id: deploy
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
        run: |
          scp -o StrictHostKeyChecking=no -i ~/.ssh/id_ed25519 bin/deploy.sh $DEMO_USER@$SSH_HOST:~/deploy.sh
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_ed25519 $DEMO_USER@$SSH_HOST './deploy.sh'
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_ed25519 $DEMO_USER@$SSH_HOST 'rm ./deploy.sh'
        shell: bash
