name: frontend checks
on:
  push:
    branches:
      - main
      - mwp_v1
  pull_request:
    paths:
      - ".github/**"

jobs:
  deploy_demo:
    name: build_release
    runs-on: ubuntu-latest
    steps:
      - name: Get version from tag
        id: extract_version
        run: |
          echo "version=${GITHUB_REF_NAME#v}" >> "$GITHUB_OUTPUT"
        shell: bash
      # https://stackoverflow.com/questions/60477061/github-actions-how-to-deploy-to-remote-server-using-ssh
      - name: Write SSH config & key
        id: write_ssh_keys
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_ed25519
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          echo "${{ secrets.SSH_CONFIG }}" > ~/.ssh/config
          cat ~/.ssh/config
        shell: bash
      - name: Connect to server
        id: connect_to_server
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_ed25519 ${{ secrets.SSH_HOST }}
          echo "Connected to server" > test.txt
        shell: bash
